# Joshva Ibne Yousuf
## Assignment_1

In [1]:
import numpy as np

## Q-1: Basic Array Operations
### Q-1.1 Create a 1D array, a 2D array, and a 3D array.

In [6]:
dim1 = np. array([1,2,3,4])
dim2 = np. array([[1,2,3,4],[5,6,7,8]])
dim3 = np. array ([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print("1D Array:\n",dim1)
print('2D Array:\n',dim2)
print('3D Array:\n',dim3)

1D Array:
 [1 2 3 4]
2D Array:
 [[1 2 3 4]
 [5 6 7 8]]
3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


### Q-1.2 Perform slicing operations on arrays.

In [20]:
# Sclicing 1D array from index 1 to index 3
print("Sclicing 1D array from index 1 to index 3.\n",dim1[1:3])
# Sclicing 2D array from 1st row and index 1 to index 3
print("Sclicing 2D array from 1st row and index 1 to index 3.\n",dim2[1:,1:3])
# Sclicing 3D array from 1st matrix and both rows from index 1 to index 3
print("Sclicing 3D array from 1st matrix and both rows from index 1 to index 3.\n",dim3[0,0:3,1:3])

Sclicing 1D array from index 1 to index 3.
 [2 3]
Sclicing 2D array from 1st row and index 1 to index 3.
 [[6 7]]
Sclicing 3D array from 1st matrix and both rows from index 1 to index 3.
 [[2 3]
 [6 7]]


### Q-1.3 Perform basic arithmetic operations on arrays.

In [35]:
print ("Addision: \n",dim1,"\n","\n",dim1,"\n","\n","+","\n","\n",dim1+dim1)

Addision: 
 [1 2 3 4] 
 
 [1 2 3 4] 
 
 + 
 
 [2 4 6 8]


In [36]:
print ("Subtraction: \n",dim2,"\n","\n",dim2,"\n","\n","-","\n","\n",dim2-dim2)

Subtraction: 
 [[1 2 3 4]
 [5 6 7 8]] 
 
 [[1 2 3 4]
 [5 6 7 8]] 
 
 - 
 
 [[0 0 0 0]
 [0 0 0 0]]


In [37]:
print ("Subtraction: \n",dim1,"\n","\n",dim3,"\n","\n","x","\n","\n",dim1*dim3)

Subtraction: 
 [1 2 3 4] 
 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 
 
 x 
 
 [[[ 1  4  9 16]
  [ 5 12 21 32]]

 [[ 9 20 33 48]
  [13 28 45 64]]]


In [39]:
print ("Subtraction: \n",dim1,"\n","\n",dim3,"\n","\n","÷","\n","\n",dim1/dim3)

Subtraction: 
 [1 2 3 4] 
 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 
 
 ÷ 
 
 [[[1.         1.         1.         1.        ]
  [0.2        0.33333333 0.42857143 0.5       ]]

 [[0.11111111 0.2        0.27272727 0.33333333]
  [0.07692308 0.14285714 0.2        0.25      ]]]


## Q-2: Array Creation and Manipulation
### Q-2.1 Create arrays using different functions: arange, linspace, zeros, ones, eye, random.

In [45]:
# Array by using np.arange
np.arange(10,50,10)


array([10, 20, 30, 40])

In [48]:
# Array by using np.linspace
np.linspace(10,40,3)


array([10., 25., 40.])

In [52]:
# Array by using np.zeros
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [53]:
# Array by using np.ones
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [54]:
# Array by using np.eye
np.eye(3)   

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
# Array by using np.random
np.random.rand(2,2)

array([[0.71359303, 0.94907213],
       [0.81674566, 0.55798484]])

### Q-2.2 Reshape an array.

In [59]:
arr = np.random.randint(10,100,10)
arr.reshape(2,5)

array([[34, 90, 22, 91, 39],
       [92, 11, 60, 99, 13]], dtype=int32)

### Q-2.3 Concatenate and split arrays.

In [65]:
# Concatenate
arr = np.random.randint(10,100,10)
arr2 = np.random.randint(100,200,10)
arr3 =np.concat((arr,arr2))

array([ 27,  44,  46,  80,  92,  11,  59,  23,  45,  38, 196, 178, 196,
       122, 191, 142, 151, 166, 194, 153], dtype=int32)

In [67]:
# Split
np.split(arr,2)

[array([27, 44, 46, 80, 92], dtype=int32),
 array([11, 59, 23, 45, 38], dtype=int32)]

## Q-3: Statistical Operations
### Q-3.1 Compute mean, median, variance, and standard deviation of an array.

In [77]:
arr= np.random.randint(10,100,10)
print("Mean of array:",np.mean(arr)print("Mean of array:",
print("Median of array:",np.median(arr))
print("Standard Deviation of array:",np.std(arr))
print("Variance of array:",np.var(arr))


Mean of array: 62.9
Median of array: 72.5
Standard Deviation of array: 30.451436747713565
Variance of array: 927.2900000000002


### Q-3.2 Find the minimum and maximum values in an array along with their indices.

In [83]:
arr= np.random.randint(10,100,10)

print(arr)
print("Minimum value of :",arr.min())
print("Maximum value of :",arr.max())

[69 57 50 21 48 50 46 85 72 11]
Minimum value of : 11
Maximum value of : 85


### Q-3.3 Compute the sum and product of array elements.

In [85]:
print("Sumation value of :",arr.sum())
print("Product value of :",arr.prod())

Sumation value of : 509
Product value of : 30692087395200000


In [98]:
arr = np.arange(16)
print (arr)
# Reshape to 2x3 array in C order
c_order = arr.reshape((4, 4), order='C')
print("C order:\n", c_order)

# Reshape to 2x3 array in F order
f_order = arr.reshape((4, 4), order='F')
print("F order:\n", f_order)

A_order = arr.reshape((4, 4), order='A')
print("A order:\n", A_order)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
C order:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
F order:
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
A order:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
