<div align="center">

# Joshva Ibne Yousuf
## Assignment Numpy_02
## Course AIML
</div>

In [57]:
import numpy as np

## Q-1 Sales Data Analysis: You have a NumPy array representing the daily sales of a product over a month. Each element in the array represents the sales for a particular day. Compute the total sales, average sales, and the day with the highest sales.


In [58]:
month_sales = (np.random.randint(1,9,30))*1000
print("Pizza Daily Sale list:",month_sales)

Pizza Daily Sale list: [7000 2000 4000 6000 7000 8000 4000 1000 6000 4000 5000 7000 6000 1000
 6000 4000 1000 8000 8000 8000 7000 6000 1000 1000 4000 5000 2000 3000
 7000 1000]


In [59]:
# Compute the total sales, average sales, and the day with the highest sales.
print("Pizza Total Sales in a Month:",month_sales.sum(),"PKR")
print("Pizza Average Sales per Day in a Month:",month_sales.mean(),"PKR")
max_sales=month_sales.max()
days =(np.where(month_sales == max_sales)[0]+1)
if days.size == 0:
    print("Pizza Sales are same for all days.")
elif days.size > 1:
    print("Pizza Day with Highest Sales are",days.size,".")
    xd=days.size
    while xd>0:
        print("Pizza Day with Highest Sales:",days[xd-1],"Date")
        xd=xd-1
else:
    print("Pizza Day with Highest Sales:",days[0],"Date")
    


Pizza Total Sales in a Month: 140000 PKR
Pizza Average Sales per Day in a Month: 4666.666666666667 PKR
Pizza Day with Highest Sales are 4 .
Pizza Day with Highest Sales: 20 Date
Pizza Day with Highest Sales: 19 Date
Pizza Day with Highest Sales: 18 Date
Pizza Day with Highest Sales: 6 Date


## Q-2 Weather Data Processing: Given a 2D NumPy array where each row represents daily temperature readings for a week (7 days), find the average temperature for each day across all weeks.


In [60]:
temperatures = np.random.randint(20,40,28).reshape(4,7)
print("Weekly Temparatures Readinds For Each Day in a Month:\n",temperatures)
print ("Weekly Average Temparatures Readinds per/Day For a Month:\n",temperatures.mean())

Weekly Temparatures Readinds For Each Day in a Month:
 [[23 38 25 37 39 20 20]
 [20 37 21 21 30 23 28]
 [25 20 34 27 24 20 30]
 [35 37 24 34 20 28 31]]
Weekly Average Temparatures Readinds per/Day For a Month:
 27.535714285714285



## Q-3 Financial Analysis: You have a NumPy array representing the daily closing prices of a stock for a month. Calculate the monthly return, which is the percentage change from the first to the last day of the month.



In [70]:
M_SP = np.random.randint(150,160,30)
print(M_SP)

[155 151 150 152 152 154 159 153 154 152 157 157 159 152 157 156 150 159
 150 155 155 152 153 151 153 151 154 155 158 159]


In [71]:

prise_1 = M_SP[0]
price_30 = M_SP[-1]

r_D30 = ((price_30 - prise_1) / prise_1) * 100
print("Monthly PnL: ",r_D30,"%")

Monthly PnL:  2.5806451612903225 %


## Q-4 Student Grades Analysis: You have a 2D NumPy array where each row represents a student and each column represents their grades in different subjects. Calculate the average grade for each student and the overall class average for each subject.


In [77]:
grades = np.random.randint(60,100,12).reshape(4,3)
print('Students Grade Per-Subject:\n',grades)
print("Avg Grades Per-Students:\n",(np.mean(grades,axis=1).reshape(4,1).astype(int)))
print("Avg Grades Per-Subject:\n",(np.mean(grades, axis=0).astype(int)))

Students Grade Per-Subject:
 [[68 73 90]
 [73 70 94]
 [74 83 88]
 [79 83 90]]
Avg Grades Per-Students:
 [[77]
 [79]
 [81]
 [84]]
Avg Grades Per-Subject:
 [73 77 90]



## Q-5 Image Processing: You have a grayscale image represented as a 2D NumPy array of pixel intensities. Normalize the pixel values to a range of 0 to 1.



In [87]:
picture = np.array ([[0, 128, 255],
                  [64, 192, 128],
                  [255, 255, 0]])

print("2D NumPy array of pixel intensities in a picture:\n",picture)
print("Normalized pixel values range 0 to 1 of picture:\n",(picture /225))

2D NumPy array of pixel intensities:
 [[  0 128 255]
 [ 64 192 128]
 [255 255   0]]
Normalized pixel values range of 0 to 1:
 [[0.         0.56888889 1.13333333]
 [0.28444444 0.85333333 0.56888889]
 [1.13333333 1.13333333 0.        ]]


## Q-6 Population Growth Analysis: You have a NumPy array representing the population of a city over 10 years. Calculate the annual growth rate and identify the year with the highest growth.



In [95]:
P = np.random.randint(10000,15000,10)
print("Population:\n",P)

Population:
 [11071 14735 11204 13918 11167 11684 13299 12767 12957 14469]


In [104]:
# Max Population Years
mx_P=P.max()
Y =(np.where(P == mx_P)[0]+1)
if Y.size > 1:
    print("The years with the highest population are",Y.size,"Years.")
    xY=Y.size
    while xd>0:
        print("The year with the highest population is Year no:",Y[xY-1])
        xY=xY-1
else:
    print("The year with the highest population is Year no:",Y[0])

The year with the highest population is Year no: 2


In [119]:
#Annual Growth Rate = ((End Population − Start Population)/ start Population) × (1 / n-years) ​× 100
AGR =(((P[-1]-P[0])/P[0])/P.size)*100
print("Annual Growth Rate:",AGR,"%")

Annual Growth Rate: 3.069280101165207 %


## Q-7 Traffic Data Analysis: Given a 2D NumPy array where each row represents the number of vehicles passing through a checkpoint in different hours of the day over a week, calculate the total traffic for each day and the busiest hour of the week.



In [184]:
vehicals = np.random.randint(50,100,(24*7))

In [203]:
print("Vehicals Passing by Hourly per-day across a week:\n",vehicals.reshape(7,24))

Vehicals Passing by Hourly per-day across a week:
 [[98 87 54 63 87 69 93 58 82 67 55 86 51 79 55 66 88 90 72 80 69 54 70 92]
 [60 53 72 87 79 91 90 67 90 92 80 79 83 80 96 87 74 66 85 89 79 51 73 58]
 [50 73 87 97 76 75 75 56 74 65 87 91 67 66 98 93 96 55 69 97 72 95 61 61]
 [83 57 76 98 57 97 82 86 68 73 71 52 58 60 55 88 88 86 51 86 55 55 88 85]
 [74 99 65 70 59 54 99 74 80 52 69 53 63 61 63 86 67 76 56 97 84 71 70 92]
 [67 87 75 71 86 54 97 84 61 84 83 96 69 98 61 83 75 83 81 95 56 75 74 95]
 [88 66 73 76 53 76 96 79 52 55 57 65 64 85 89 57 88 79 99 61 53 63 74 54]]


### Busiest hour of the day

In [204]:
b = np.max(vehicals.reshape(24,7), axis=0)
ts = b.size
x=1
while ts>0:
    print("Busiest hour of the day",(x),"passing", b[x-1],"vehicals")
    ts=ts-1
    x=x+1

Busiest hour of the day 1 passing 98 vehicals
Busiest hour of the day 2 passing 99 vehicals
Busiest hour of the day 3 passing 97 vehicals
Busiest hour of the day 4 passing 97 vehicals
Busiest hour of the day 5 passing 99 vehicals
Busiest hour of the day 6 passing 98 vehicals
Busiest hour of the day 7 passing 99 vehicals


### Busiest hour of Week

In [205]:
rdv = vehicals.reshape(1,(24*7))
mvm = np.max(rdv)
w=np.where(vehicals == mvm)[0]
ws = w.size
y=1
while ws>0:
    print("Busiest hour of Week is",w[y-1],"by passing", mvm,"vehicals")
    ws=ws-1
    y=y+1

Busiest hour of Week is 97 by passing 99 vehicals
Busiest hour of Week is 102 by passing 99 vehicals
Busiest hour of Week is 162 by passing 99 vehicals


## Q-8 Product Inventory Management: You have a NumPy array representing the stock levels of different products in a warehouse. Reorder the products with stock levels below a threshold (e.g., 50 units).



In [63]:
stock = np.random.randint(30,75,10)


In [66]:
th = 50
bth = stock < th
index = np.where(bth)[0]
print("List of stocks is:\n",stock)
print("Products that need reordering indexes:",index)
print("Stock levels that need reordeting:", stock[index])


List of stocks is:
 [50 38 70 67 55 36 49 39 73 69]
Products that need reordering indexes: [1 5 6 7]
Stock levels that need reordeting: [38 36 49 39]


## Q-9 Game Score Analysis: You have a NumPy array representing the scores of different players in a game over multiple rounds. Identify the player with the highest average score and the round with the highest total score.

In [7]:
scores = np.random.randint(50,100,(4*3)).reshape(4,3)

In [21]:
print("Four players score list in 3 rounds:\n",scores)
avgs = np.mean(scores,axis=1).reshape(4,1).astype(int)
print("Average score list in 3 rounds per-player:\n",avgs)
x=np.where(avgs == np.max(avgs))[0]
print ("Player no:",int(x),"has Highest Average score.")
print ("Player no:",int(x[0]),"has Highest Score of",int(np.max(scores))," in round no:",int(np.where(scores == np.max(scores))[0]+1))

Four players score list in 3 rounds:
 [[69 86 57]
 [74 91 62]
 [55 87 89]
 [81 69 53]]
Average score list in 3 rounds per-player:
 [[70]
 [75]
 [77]
 [67]]
Player no: 2 has Highest Average score.
Player no: 2 has Highest Score of 91  in round no: 2


/tmp/ipykernel_4030/1613772214.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print ("Player no:",int(x),"has Highest Average score.")
/tmp/ipykernel_4030/1613772214.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print ("Player no:",int(x[0]),"has Highest Score of",int(np.max(scores))," in round no:",int(np.where(scores == np.max(scores))[0]+1))


## Q-10 Financial Portfolio Analysis: You have a NumPy array representing the daily returns of different assets in a financial portfolio over a month. Calculate the portfolio's overall daily return, and identify the asset with the highest volatility.

In [32]:
dr = np.random.randint(30,99,(30*5)).reshape(30,5)
print(dr)

[[46 56 51 52 97]
 [71 49 90 40 87]
 [59 40 61 31 30]
 [59 55 36 38 68]
 [43 71 40 91 47]
 [32 33 87 49 84]
 [81 76 35 98 54]
 [49 72 72 62 35]
 [95 74 84 82 65]
 [44 70 57 37 61]
 [61 42 37 33 45]
 [32 49 70 87 53]
 [77 91 93 56 63]
 [60 38 50 82 30]
 [70 34 87 35 48]
 [75 69 59 80 77]
 [31 92 90 82 36]
 [73 55 93 31 45]
 [41 58 85 84 50]
 [76 37 80 54 61]
 [97 42 55 36 32]
 [38 42 74 80 47]
 [49 76 59 55 30]
 [91 79 80 84 71]
 [60 62 64 70 98]
 [84 85 67 57 31]
 [50 61 80 51 59]
 [77 72 53 69 32]
 [95 66 48 59 50]
 [32 63 65 73 58]]


In [46]:
v = np.std(dr, axis=0) 
mvai = np.where(v==np.max(v))[0]+1 

print("Overall daily returns per-product:\n",v)
print("Product with Highest daily returns is product no",int(mvai))


Overall daily returns per-product:
 [20.24285882 16.75141785 17.83990533 20.1840421  19.44976435]
Product with Highest daily returns is product no 1


/tmp/ipykernel_4030/1998637468.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("Product with Highest daily returns is product no",int(mvai))


<div align="center">

# Assignment Numpy 02

## Status: <span style="color:green;">Completed ✔</span>

Assignment accomplished successfully.

</div>