<div align="center">

# Joshva Ibne Yousuf
## Assignment Numpy
## Course AIML
</div>

In [135]:
import numpy as np

## Q-1: Basic Array Operations
### Q-1.1 Create a 1D array, a 2D array, and a 3D array.

In [136]:
dim1 = np. array([1,2,3,4])
dim2 = np. array([[1,2,3,4],[5,6,7,8]])
dim3 = np. array ([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print("1D Array:\n",dim1)
print('2D Array:\n',dim2)
print('3D Array:\n',dim3)

1D Array:
 [1 2 3 4]
2D Array:
 [[1 2 3 4]
 [5 6 7 8]]
3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


### Q-1.2 Perform slicing operations on arrays.

In [137]:
# Sclicing 1D array from index 1 to index 3
print("Sclicing 1D array from index 1 to index 3.\n",dim1[1:3])
# Sclicing 2D array from 1st row and index 1 to index 3
print("Sclicing 2D array from 1st row and index 1 to index 3.\n",dim2[1:,1:3])
# Sclicing 3D array from 1st matrix and both rows from index 1 to index 3
print("Sclicing 3D array from 1st matrix and both rows from index 1 to index 3.\n",dim3[0,0:3,1:3])

Sclicing 1D array from index 1 to index 3.
 [2 3]
Sclicing 2D array from 1st row and index 1 to index 3.
 [[6 7]]
Sclicing 3D array from 1st matrix and both rows from index 1 to index 3.
 [[2 3]
 [6 7]]


### Q-1.3 Perform basic arithmetic operations on arrays.

In [138]:
print ("Addision: \n",dim1,"\n","\n",dim1,"\n","\n","+","\n","\n",dim1+dim1)

Addision: 
 [1 2 3 4] 
 
 [1 2 3 4] 
 
 + 
 
 [2 4 6 8]


In [139]:
print ("Subtraction: \n",dim2,"\n","\n",dim2,"\n","\n","-","\n","\n",dim2-dim2)

Subtraction: 
 [[1 2 3 4]
 [5 6 7 8]] 
 
 [[1 2 3 4]
 [5 6 7 8]] 
 
 - 
 
 [[0 0 0 0]
 [0 0 0 0]]


In [140]:
print ("Subtraction: \n",dim1,"\n","\n",dim3,"\n","\n","x","\n","\n",dim1*dim3)

Subtraction: 
 [1 2 3 4] 
 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 
 
 x 
 
 [[[ 1  4  9 16]
  [ 5 12 21 32]]

 [[ 9 20 33 48]
  [13 28 45 64]]]


In [141]:
print ("Subtraction: \n",dim1,"\n","\n",dim3,"\n","\n","÷","\n","\n",dim1/dim3)

Subtraction: 
 [1 2 3 4] 
 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 
 
 ÷ 
 
 [[[1.         1.         1.         1.        ]
  [0.2        0.33333333 0.42857143 0.5       ]]

 [[0.11111111 0.2        0.27272727 0.33333333]
  [0.07692308 0.14285714 0.2        0.25      ]]]


## Q-2: Array Creation and Manipulation
### Q-2.1 Create arrays using different functions: arange, linspace, zeros, ones, eye, random.

In [142]:
# Array by using np.arange which arrange all numbers from 0 to 50 by taking step of 10 numbers
np.arange(0,50,10)


array([ 0, 10, 20, 30, 40])

In [143]:
# Array by using np.linspace which arrange 3 equal distensing numbers from 0 to 40
np.linspace(0,39,3)


array([ 0. , 19.5, 39. ])

In [144]:
# Array by using np.zeros
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [145]:
# Array by using np.ones
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [146]:
# Array by using np.eye
np.eye(3)   

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
# Array by using np.random
np.random.rand(2,2)

array([[0.96583488, 0.20886706],
       [0.85999929, 0.57140025]])

### Q-2.2 Reshape an array.

In [148]:
arr = np.random.randint(10,100,10)
arr.reshape(2,5)

array([[65, 43, 14, 71, 21],
       [16, 37, 61, 13, 17]])

### Q-2.3 Concatenate and split arrays.

In [149]:
# Concatenate
arr = np.random.randint(10,100,10)
arr2 = np.random.randint(100,200,10)
arr3 = np.concatenate((arr,arr2))
print (arr3)

[ 48  48  14  55  89  73  89  22  31  26 107 199 184 141 112 192 160 169
 150 171]


In [150]:
# Split
np.split(arr,2)

[array([48, 48, 14, 55, 89]), array([73, 89, 22, 31, 26])]

## Q-3: Statistical Operations
### Q-3.1 Compute mean, median, variance, and standard deviation of an array.

In [151]:
arr= np.random.randint(10,100,10)
print("Mean of array:",np.mean(arr))
print("Median of array:",np.median(arr))
print("Standard Deviation of array:",np.std(arr))
print("Variance of array:",np.var(arr))


Mean of array: 57.9
Median of array: 51.0
Standard Deviation of array: 27.435196372543064
Variance of array: 752.69


### Q-3.2 Find the minimum and maximum values in an array along with their indices.

In [152]:
arr= np.random.randint(10,100,10)

print(arr)
print("Minimum value of :",arr.min())
print("Maximum value of :",arr.max())

[32 93 19 47 36 19 27 12 69 37]
Minimum value of : 12
Maximum value of : 93


### Q-3.3 Compute the sum and product of array elements.

In [153]:
print("Sumation value of :",arr.sum())
print("Product value of :",arr.prod())

Sumation value of : 391
Product value of : 1503613832984064


In [154]:
arr = np.arange(16)
print (arr)
# Reshape to 2x3 array in C order
c_order = arr.reshape((4, 4), order='C')
print("C order:\n", c_order)

# Reshape to 2x3 array in F order
f_order = arr.reshape((4, 4), order='F')
print("F order:\n", f_order)

A_order = arr.reshape((4, 4), order='A')
print("A order:\n", A_order)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
C order:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
F order:
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
A order:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## Q-4 Broadcasting
### Q-4.1

In [155]:
arr_1d = np.array([1, 2, 3])

bdc = arr_1d + 5
print("1D Array + number:")
print(bdc)
# in above sanerio 5 is a scalar value
# but by brodcasting techniquer numpy extend 
# scalar to an array of 3 elements by rupeeting it 3 times.

1D Array + number:
[6 7 8]


In [156]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
bdc_2 = arr_2d + arr_1d
print("\n2D Array + 1D Array:")
print(bdc_2)
# in above sanerio arr_1d is 1D array
# but by brodcasting technique numpy extend 
# 1D array to 2D array by rupeeting it.


2D Array + 1D Array:
[[2 4 6]
 [5 7 9]]


## Q-5 Linear Algebra
### Q-5.1 Perform matrix multiplication.

In [157]:
a= np.random.randint(50,99,4).reshape(2,2)
b= np.random.randint(0,49,4).reshape(2,2)
print (a)
print ("X")
print (b)
print("=")
print(np.dot(a,b))

[[83 50]
 [93 54]]
X
[[28 32]
 [ 9 18]]
=
[[2774 3556]
 [3090 3948]]



### Q-5.2 Compute the determinant, inverse, and eigenvalues of a matrix.

In [158]:
matrix_1 = np.random.randint(50,99,9).reshape(3,3)

#### 5.2.1 Determinant

In [159]:
print("Matrix A:\n",matrix_1)

print("Determinant of Matrix A:", np.linalg.det(matrix_1))

Matrix A:
 [[60 69 67]
 [50 82 63]
 [53 68 62]]
Determinant of Matrix A: 1109.0000000000043



#### 5.2.2 Inverse

In [160]:
print("Matrix A:\n",matrix_1)

print("Inverse of Matrix A:\n", np.linalg.inv(matrix_1))

Matrix A:
 [[60 69 67]
 [50 82 63]
 [53 68 62]]
Inverse of Matrix A:
 [[ 0.7213706   0.25067628 -1.0342651 ]
 [ 0.21550947  0.15238954 -0.3877367 ]
 [-0.85302074 -0.38142471  1.32551849]]



#### 5.2.3 Eigenvalues

In [161]:
print("Matrix A:\n",matrix_1)
value , vactor = np.linalg.eig(matrix_1)
print("Eigenvalues value of Matrix A:\n", value)
print("Eigenvalues Vactor of Matrix A:\n", vactor)

Matrix A:
 [[60 69 67]
 [50 82 63]
 [53 68 62]]
Eigenvalues value of Matrix A:
 [191.27932462  12.24728017   0.47339521]
Eigenvalues Vactor of Matrix A:
 [[-0.59092703 -0.66993334 -0.60731593]
 [-0.58849028  0.70101817 -0.21791189]
 [-0.55180108 -0.2444644   0.76399068]]



### Q-5.3 Solve a system of linear equations.

In [162]:
matrix_A = np.random.randint(50,99,4).reshape(2,2)
matrix_B = np.random.randint(0,49,2)
print("Matrix A:\n",matrix_A)

print("Solve Matrix X of Matrix A:\n", np.linalg.solve(matrix_A,matrix_B))

Matrix A:
 [[96 97]
 [89 57]]
Solve Matrix X of Matrix A:
 [ 0.56501107 -0.54887694]


## Q-6 Advanced Indexing and Slicing
### Q-6.1 Use Boolean indexing to filter an array.

In [163]:
array = np.random.randint(10,100,9)
print (array)
print ("Greater than 45 are:",array[array>45])

[57 82 23 84 13 28 56 97 76]
Greater than 45 are: [57 82 84 56 97 76]


### Q-6.2 Use fancy indexing to select specific elements from an array.


In [164]:
array_1 = np.random.randint(10,100,27).reshape(3,3,3)
print (array_1)
print ("In 3rd Dimension 1st and 2nd row of 2nd and 3rd column is:\n",array_1[2,0:2,1:3])

[[[71 34 34]
  [98 77 13]
  [88 95 90]]

 [[60 73 54]
  [59 20 87]
  [62 30 76]]

 [[83 27 76]
  [25 24 52]
  [12 47 94]]]
In 3rd Dimension 1st and 2nd row of 2nd and 3rd column is:
 [[27 76]
 [24 52]]


### Q-6.3 Perform advanced slicing operations.


In [165]:
array_2 = np.random.randint(10,100,9)
print ("Array is:",array_2)
print ("elementsa at 0th, 4th and last index is:",array_2[[0,4,-1]])

Array is: [74 39 99 67 77 73 86 86 28]
elementsa at 0th, 4th and last index is: [74 77 28]


## Q-7 Random Sampling

### Q-7.1 Generate random numbers from different distributions.


In [166]:
print(np.random.randn(5))
print("np.random.randn( ) genrate random number from standard normal distribution.\n mean = 0\n std = 1")
print(np.random.rand(5) )
print("np.random.rand( ) genrate random number from 0 to 1.")
print(np.random.randint(10,100,5))
print("np.random.randint( ) genrate random number from range given by user.")

[-0.09918554  1.70816373 -0.9420168   0.43683304  0.5065095 ]
np.random.randn( ) genrate random number from standard normal distribution.
 mean = 0
 std = 1
[0.31160214 0.15612858 0.72709485 0.08913007 0.36708777]
np.random.rand( ) genrate random number from 0 to 1.
[37 13 39 96 12]
np.random.randint( ) genrate random number from range given by user.


### Q-7.2 Create random samples from a dataset.


In [167]:
array_3=(np.random.randint(10,100,5))
print(array_3)
print("Random Sellected numbers are:\n",np.random.choice(array_3, 2))

[57 62 89 39 55]
Random Sellected numbers are:
 [39 55]


### Q-7.3 Perform random shuffling of an array.

In [168]:
array_4=np.array([34,56,23,78,45,99,90,34])
print(array_4)
np.random.shuffle(array_4)
print("Re-ordered array is:\n",array_4)


[34 56 23 78 45 99 90 34]
Re-ordered array is:
 [34 78 45 56 34 99 23 90]


<div align="center">

# Assignment Numpy

## Status: <span style="color:green;">Completed</span>

Assignment accomplished successfully.

</div>