# **NumPy**

In [39]:
import numpy as np

**Importing NumPy**

# Array Creation
## Checking
1. Data type_________________| arr.dtype
2. Shape____________________| arr.shape
3. Size______________________| arr.size
4. Numbers of Dimension_____| arr.ndim


## 1D Array

In [51]:
arr1 = np.array([1,2,3,4])
print("This is our 1st Array:",arr1)
print("1st Array Datatype is:(",arr1.dtype,")")
print("1st Array Shape is:",arr1.shape)
print("Our 1st Array Contains",arr1.size,"numbers of elements.")
print("Our 1st Array is",arr1.ndim,"Dimensional Array.")


This is our 1st Array: [1 2 3 4]
1st Array Datatype is:( int64 )
1st Array Shape is: (4,)
Our 1st Array Contains 4 numbers of elements.
Our 1st Array is 1 Dimensional Array.


## 2D Array

In [52]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print("This is our 2nd Array:\n",arr2)
print("2nd Array Datatype is:(",arr2.dtype,")")
print("2nd Array Shape is:",arr2.shape)
print("Our 2nd Array Contains",arr2.size,"numbers of elements.")
print("Our 2nd Array is",arr2.ndim,"Dimensional Array.")

This is our 2nd Array:
 [[1 2 3 4]
 [5 6 7 8]]
2nd Array Datatype is:( int64 )
2nd Array Shape is: (2, 4)
Our 2nd Array Contains 8 numbers of elements.
Our 2nd Array is 2 Dimensional Array.


## 5D Array
- The dimension of an array depends on the number of overlapping “_[]_ ”.
1. Checking Summation_______| arr.sum()


In [53]:
arr3 = np.array([[[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]],[[[17,18,19,20],[21,22,23,24]],[[25,26,27,28],[29,30,31,32]]]],[[[[33,34,35,36],[37,38,39,40]],[[41,42,43,44],[45,46,47,48]]],[[[49,50,51,52],[53,54,55,56]],[[57,58,59,60],[61,62,63,64]]]]])
# print of arr3 is commented below because output is lenghty, if any one wants to view output of arr3 kindly uncoment print function below.
# print("This is our 3rd Array:\n",arr3)
print("3rd Array Datatype is:(",arr3.dtype,")")
print("3rd Array Shape is:",arr3.shape)
print("Summation of 3rd Array is:",arr3.sum())
print("Our 3rd Array Contains",arr3.size,"numbers of elements.")
print("Our 3rd Array is",arr3.ndim,"Dimensional Array.").

3rd Array Datatype is:( int64 )
3rd Array Shape is: (2, 2, 2, 2, 4)
Summation of 3rd Array is: 2080
Our 3rd Array Contains 64 numbers of elements.
Our 3rd Array is 5 Dimensional Array.


## Zeros Array
- The array with all _"0"_ elements.

In [43]:
zeros=np.zeros([2,2])
zeros

array([[0., 0.],
       [0., 0.]])

## Ones Array
- The array with all _"1"_ elements.

In [44]:
ones = np.ones([2,2])
ones

array([[1., 1.],
       [1., 1.]])

## Identity Array
- The array with all _"0"_ elements and _"1"_ on the diagona,

In [45]:
identity = np.eye(2)
identity

array([[1., 0.],
       [0., 1.]])

## Diagonal Array
- The array with all _"0"_ elements and non-zero on the diagonal.

In [48]:
diagonal = np.diag([1,2,3])
diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])