# **Atif Jamil**

**Email:** [aatifkh8n@gmail.com](mailto:aatifkh8n@gmail.com)

**GitHub:** [aatifkh8n](https://github.com/aatifkh8n) |
**Kaggle:** [aatifkh8n](https://kaggle.com/aatifkh8n) |
**LinkedIn:** [Atif Jamil](https://linkedin.com/in/atif--jamil)

### **Purpose:** Basic NumPy

In [1]:
import numpy as np

In [2]:
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
ones = np.ones((4, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
zeros_dot_ones = np.dot(zeros, ones)
zeros_dot_ones

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
marks = np.array([60, 53, 71, 62, 83, 57])

marks

array([60, 53, 71, 62, 83, 57])

In [6]:
marks = marks.reshape(2, 3)

marks

array([[60, 53, 71],
       [62, 83, 57]])

In [7]:
marks.shape

(2, 3)

In [8]:
marks.ndim

2

In [9]:
marks.size

6

In [10]:
np.mean(marks)

np.float64(64.33333333333333)

In [11]:
np.median(marks)

np.float64(61.0)

In [12]:
# mode function doesn't exist in the numpy
# np.mode(marks)

In [13]:
np.min(marks)

np.int64(53)

In [14]:
np.max(marks)

np.int64(83)

In [15]:
np.sum(marks)

np.int64(386)

In [16]:
np.subtract(marks, 5)

array([[55, 48, 66],
       [57, 78, 52]])

In [17]:
np.dtype

numpy.dtype

In [18]:
np.average(marks)

np.float64(64.33333333333333)

In [19]:
marks.conjugate()

array([[60, 53, 71],
       [62, 83, 57]])

In [20]:
# transpose of marks
marks.T

array([[60, 62],
       [53, 83],
       [71, 57]])

In [21]:
# column-wise product of marks
marks.prod(axis=0)

array([3720, 4399, 4047])

In [22]:
# row-wise product of marks
marks.prod(axis=1)

array([225780, 293322])

In [23]:
marks.std()

np.float64(9.994442900376633)