In [25]:
import numpy as np

In [26]:
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
ones = np.ones((4, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
zeros_dot_ones = np.dot(zeros, ones)
zeros_dot_ones

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
marks = np.array([60, 53, 71, 62, 83, 57])

marks

array([60, 53, 71, 62, 83, 57])

In [30]:
marks = marks.reshape(2, 3)

marks

array([[60, 53, 71],
       [62, 83, 57]])

In [31]:
marks.shape

(2, 3)

In [32]:
marks.ndim

2

In [33]:
marks.size

6

In [34]:
np.mean(marks)

np.float64(64.33333333333333)

In [35]:
np.median(marks)

np.float64(61.0)

In [36]:
# mode function doesn't exist in the numpy
# np.mode(marks)

In [37]:
np.min(marks)

np.int64(53)

In [38]:
np.max(marks)

np.int64(83)

In [39]:
np.sum(marks)

np.int64(386)

In [40]:
np.subtract(marks, 5)

array([[55, 48, 66],
       [57, 78, 52]])

In [41]:
np.dtype

numpy.dtype

In [43]:
np.average(marks)

np.float64(64.33333333333333)

In [44]:
marks.conjugate()

array([[60, 53, 71],
       [62, 83, 57]])

In [46]:
# transpose of marks
marks.T

array([[60, 62],
       [53, 83],
       [71, 57]])

In [48]:
# column-wise product of marks
marks.prod(axis=0)

array([3720, 4399, 4047])

In [49]:
# row-wise product of marks
marks.prod(axis=1)

array([225780, 293322])

In [50]:
marks.std()

np.float64(9.994442900376633)