# Abdullah 
### Assingment

In [1]:
import numpy as np

### Problem 1

You have five objects of unknown mass m1, m2, m3, m4, m5. You would like to find the mass of each of these objects using the scale. If you put one or more of the objects on each side of the scale, you will be able to measure the difference in weight. This scale does not work, however, if one side is left empty.

(A) You make a measurement of objects {1, 2} against objects {3, 4} and get a difference of 1kg. Write this as a linear equation for the masses.

In [2]:
masses = np.array([[4, 2, -1, -1, 5]])
mass_1 = np.array([1])
print("Coefficient matrix A:\n",masses)
print("\nRight-hand side vector b:\n",mass_1)

Coefficient matrix A:
 [[ 4  2 -1 -1  5]]

Right-hand side vector b:
 [1]


(B) What is the minimum number of such measurements necessary to recover all five masses?

In [17]:
mass = np.array([[1, 3, -1, -1, 4],[1, -1, 1, 0, -1],[0, 4, 1, -5, -1],[3, 0, 7, -1, 1],[-1, 5, 0, 8, -1]])
all_r = np.array([1, 2, 3, -2, 0])
print("Coefficient matrix Waight experiments:\n",mass)
print("\nRight-hand side vector b:\n",all_r)
print("\nMinimum number of measurements needed to recover all masses:", mass.shape[0])

Coefficient matrix Waight experiments:
 [[ 1  3 -1 -1  4]
 [ 1 -1  1  0 -1]
 [ 0  4  1 -5 -1]
 [ 3  0  7 -1  1]
 [-1  5  0  8 -1]]

Right-hand side vector b:
 [ 1  2  3 -2  0]

Minimum number of measurements needed to recover all masses: 5


(C) If the answer to the above question is N, come up with N − 1 measurements that, when combined with the answer to (A) above would make it possible to recover the masses.

In [15]:
print("\nFirst equation coefficients:", masses)
print("First equation result:", mass_1)


First equation coefficients: [[ 4  2 -1 -1  5]]
First equation result: [1]


(D) What would A and b be in the matrix form of the linear system corresponding to the N measurements?

In [18]:
weight = np.array(['m1', 'm2', 'm3', 'm4', 'm5'])
print("\nFinal system of equations:")
for i in range (all_r.size):
    equation_parts = []
    for j in range(weight.size):
        if mass[i][j] != 0:
            equation_parts.append(f"+({mass[i][j]}*{weight[j]})")
    print(" ".join(equation_parts), "=", all_r[i])


Final system of equations:
+(1*m1) +(3*m2) +(-1*m3) +(-1*m4) +(4*m5) = 1
+(1*m1) +(-1*m2) +(1*m3) +(-1*m5) = 2
+(4*m2) +(1*m3) +(-5*m4) +(-1*m5) = 3
+(3*m1) +(7*m3) +(-1*m4) +(1*m5) = -2
+(-1*m1) +(5*m2) +(8*m4) +(-1*m5) = 0


### Problem 2 

(A) Use arange to create a variable named foo that stores an array of numbers from 0 to 29, inclusive. Print foo and its shape.

In [27]:
foo = np.arange(1,31)
print("The array foo is:\n",foo)
print("The shape of foo is:\n",foo.shape)

The array foo is:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
The shape of foo is:
 (30,)


(B) Use the reshape function to change foo to a validly-shaped two-dimensional matrix and store it in a new variable called bar. Print bar and its shape.

In [28]:
bar = foo.reshape(5,6)
print("The 2-D array bar is:\n",bar)
print("The shape of bar is:\n",bar.shape)

The 2-D array bar is:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
The shape of bar is:
 (5, 6)


(C) Create a third variable, baz that reshapes it into a valid three-dimensional shape. Print baz and its shape.

In [29]:
baz = foo.reshape(3,5,2)

print("The 3-D array baz is:\n",baz)
print("The shape of baz is:\n",baz.shape)

The 3-D array baz is:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]

 [[21 22]
  [23 24]
  [25 26]
  [27 28]
  [29 30]]]
The shape of baz is:
 (3, 5, 2)


(D) There are several different ways to index into NumPy arrays. Use two-dimensional array indexing to set the first value in the second row of bar to -1. Now look at foo and baz. Did they change? Explain what’s going on.

In [30]:
bar[1, 0] = -1
print("bar after after changing:\n", bar)
print("foo after after changing:\n", foo)
print("baz after after changing:\n", baz)

bar after after changing:
 [[ 1  2  3  4  5  6]
 [-1  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
foo after after changing:
 [ 1  2  3  4  5  6 -1  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
baz after after changing:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [-1  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]

 [[21 22]
  [23 24]
  [25 26]
  [27 28]
  [29 30]]]


Foo and Baz did not change

(E) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular).
Write code to do the following:

1.Sum baz over its second dimension and print the result.

2.Sum baz over its third dimension and print the result.

3.Sum baz over both its first and third dimensions and print the result.

In [31]:
print("Sum baz over its second dimension:\n",np.sum(baz, axis=1))
print("Sum baz over its third dimension:\n", np.sum(baz, axis=2))
print("Sum baz over both its first and third dimensions:\n",np.sum(baz, axis=(0, 2)))

Sum baz over its second dimension:
 [[ 17  30]
 [ 75  80]
 [125 130]]
Sum baz over its third dimension:
 [[ 3  7 11  7 19]
 [23 27 31 35 39]
 [43 47 51 55 59]]
Sum baz over both its first and third dimensions:
 [ 69  81  93  97 117]


(F) Along with shaping and indexing, we also do a lot of slicing which is where you index with ranges to get subvectors and sometimes submatrices.
Write code to do the following:

1.Slice out the second row of bar and print it.

2.Slice out the last column of bar using the -1 notation and print it.

3.Slice out the top right 2 × 2 submatrix of bar and print it.

In [32]:
print("Slice out the second row of bar:\n",bar[1, :])
print("Slice out the last column of bar using the -1 notation:\n",bar[:, -1].reshape(5,1))
print("Slice out the top right 2 × 2 submatrix of bar and print it:\n",bar[:2, -2:])

Slice out the second row of bar:
 [-1  8  9 10 11 12]
Slice out the last column of bar using the -1 notation:
 [[ 6]
 [12]
 [18]
 [24]
 [30]]
Slice out the top right 2 × 2 submatrix of bar and print it:
 [[ 5  6]
 [11 12]]


### Problem 3

One feature of NumPy that is powerful but tricky is the ability to perform broadcasting, which really just refers to repeatedly performing an operation over one or more dimensions. Start a new problem in your Colab notebook and when you’re done with the entire assignment, follow the same procedure for appending a PDF and inserting the URL as you did in the previous assignment. The notebook URL is near the end of the assignment. (A) The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [33]:
vec = np.arange(10)+1
print("Vector:", vec)

Vector: [ 1  2  3  4  5  6  7  8  9 10]


(B) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself.

In [34]:
matrix = vec.reshape(10,1) + vec
print("Matrix is:\n", matrix)

Matrix is:
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


(C) A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. First, create a fake “data set” with 50 examples, each with five dimensions.
>1.import numpy.random as npr
>
>2.data = npr.exp(npr.randn(50, 5))

You don’t worry too much bout what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number generation library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent and identically-distributed vectors from a log-normal distribution.

In [35]:
import numpy.random as npr
data = npr.normal(npr.randn(50, 5))
print (data)

[[-1.85958105  1.15164887 -0.16627902  0.75069686  0.26061631]
 [-2.05203263 -0.16300357 -0.91686561  2.98406397  1.30297208]
 [ 1.81076661  0.69465338  0.27834315 -1.31788039  0.79291774]
 [ 0.82910055  1.60656677 -0.94389955  0.92518416  2.68918143]
 [ 0.07251171 -2.68855583 -1.98016137  0.5581767   1.21759151]
 [-2.06541687 -1.58098165 -1.40881401  0.9525369  -2.62767104]
 [-0.85698253  1.5197799   0.75459533 -0.62983878  0.48125287]
 [-2.14236759  3.54199965  0.80826282  2.89572323 -0.97407649]
 [-1.15513033  0.12339075  0.82557577 -1.3088348   1.80304634]
 [ 0.07683163 -2.25060046 -0.15560464  1.03727141  2.84890847]
 [-0.24610317  4.21849574 -1.39019433  0.06826919  1.85950176]
 [-1.33766963 -0.25574433  1.58809023  1.23401112 -0.37146994]
 [-0.89566541 -0.04998856 -2.50584991 -1.45828105  1.33267845]
 [-1.77800497 -1.3839662   2.96016115 -2.40415781  1.44084164]
 [ 1.79489109 -0.73237046 -1.72508625 -0.2115958   1.02151465]
 [-0.3635546   0.05475983  0.33253327 -0.81742534 -0.31

(D) Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit bout how to use the axis argument to mean and std. Store these vectors into variables and print both of them.

In [36]:
d_mean = data.mean(axis=0)
d_std = data.std(axis=0)
print("Mean of each column:\n",d_mean)
print("Standard deviation of each column:\n",d_std)

Mean of each column:
 [0.08229415 0.42431041 0.00960743 0.09161715 0.15193483]
Standard deviation of each column:
 [1.5297531  1.58499238 1.39014362 1.48647142 1.64634334]


(E) Now standardize the data matrix by:

>subtracting the mean off of each column
>
>Dividing each column by its standard deviation.

Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of the columns of normalized and print them out.

In [37]:
normalized = (data - d_mean) / d_std
n_mean = normalized.mean(axis=0)
n_std = normalized.std(axis=0)
print("Mean of each column:\n",n_mean)
print("Standard deviation of each column:\n",n_std)

Mean of each column:
 [-1.33226763e-17 -8.88178420e-18  1.33226763e-17 -3.99680289e-17
  1.99840144e-17]
Standard deviation of each column:
 [1. 1. 1. 1. 1.]


Problem 4

(A) Vandermonde matrix creation using:

def vandermonde(N):

____ vec = np.arange(N)+ 1

In [38]:
def vandermonde(N):
    v = np.arange(1, N + 1)
    
    v_matrix = np.vander(v,N-1)
    return v_matrix
N = 12
# print (vec)
print("Vandermonde matrix ( N =",N,"):\n", vandermonde(N))

Vandermonde matrix ( N = 12 ):
 [[          1           1           1           1           1           1
            1           1           1           1           1]
 [       1024         512         256         128          64          32
           16           8           4           2           1]
 [      59049       19683        6561        2187         729         243
           81          27           9           3           1]
 [    1048576      262144       65536       16384        4096        1024
          256          64          16           4           1]
 [    9765625     1953125      390625       78125       15625        3125
          625         125          25           5           1]
 [   60466176    10077696     1679616      279936       46656        7776
         1296         216          36           6           1]
 [  282475249    40353607     5764801      823543      117649       16807
         2401         343          49           7           1]
 [ 107374