## Abdullah Numpy Scenrio Assingment

>Q.1: Sales Data Analysis: You have a NumPy array representing the daily sales of a product over a month. Each element in the array represents the sales for a particular day. Compute the total sales, average sales, and the day with the highest sales.


In [14]:
import numpy as np

In [2]:
sales_data = np.array([150, 200, 180, 190, 220, 170, 210, 260, 230, 240,190, 180, 170, 160, 220, 250, 210, 240, 230, 300,190, 210, 180, 170, 240, 230, 220, 190, 200, 210])
total_sale = np.sum(sales_data)
avg_sale= np.mean(sales_data)
highest_sale=np.argmax(sales_data) + 1
max_sale= np.max(sales_data)

print("Total sales: \n",total_sale)
print("Average_sale: \n",avg_sale)
print("Highest sale: \n",highest_sale)
print("day",highest_sale,"has the highest sale")


Total sales: 
 6240
Average_sale: 
 208.0
Highest sale: 
 20
day 20 has the highest sale


>Q.2: Weather Data Processing: Given a 2D NumPy array where each row represents daily temperature readings for a week (7 days), find the average temperature for each day across all weeks.


In [8]:
temperature_data = np.array([
    [71, 72, 73, 74, 75, 76, 77],
    [68, 69, 70, 71, 72, 73, 74],
    [75, 76, 77, 78, 79, 80, 81],
    [69, 70, 71, 72, 73, 74, 75]
])
average_temperatures = np.mean(temperature_data, axis=0)

print("Average temperatures for each day:", average_temperatures)

Average temperatures for each day: [70.75 71.75 72.75 73.75 74.75 75.75 76.75]


>Q.3: Financial Analysis: You have a NumPy array representing the daily closing prices of a stock for a month. Calculate the monthly return, which is the percentage change from the first to the last day of the month.

In [9]:
closing_prices = np.array([150.0, 152.3, 153.4, 155.1, 156.7, 154.0, 157.2, 160.3, 161.0, 
                           162.4, 164.2, 162.9, 161.8, 163.5, 165.1, 166.0, 164.9, 163.8,
                           165.2, 167.3, 168.5, 169.2, 170.1, 172.0, 171.5, 173.2, 175.0, 
                           174.1, 176.8, 178.2])

first_day_price = closing_prices[0]
last_day_price = closing_prices[-1]

monthly_return = ((last_day_price - first_day_price) / first_day_price) * 100

print(f"Monthly return: {monthly_return:.2f}%")

Monthly return: 18.80%


>Q.4: Student Grades Analysis: You have a 2D NumPy array where each row represents a student and each column represents their grades in different subjects. Calculate the average grade for each student and the overall class average for each subject.


In [10]:
grades = np.array([
    [85, 90, 78], 
    [88, 92, 80], 
    [84, 85, 82],
    [90, 91, 79], 
    [78, 85, 88]  
])

average_per_student = np.mean(grades, axis=1)

average_per_subject = np.mean(grades, axis=0)

print("Average grade for each student:", average_per_student)
print("Overall class average for each subject:", average_per_subject)

Average grade for each student: [84.33333333 86.66666667 83.66666667 86.66666667 83.66666667]
Overall class average for each subject: [85.  88.6 81.4]


>Q.5: Image Processing: You have a grayscale image represented as a 2D NumPy array of pixel intensities. Normalize the pixel values to a range of 0 to 1.

Normalized Value= 
Max Value−Min Value/
Pixel Value−Min Value
​

In [12]:
image = np.array([
    [110, 220, 250],
    [130, 155, 170],
    [60,  80,  90]
])

normalized_image = image / 255.0

print("Normalized Image:")
print(normalized_image)

Normalized Image:
[[0.43137255 0.8627451  0.98039216]
 [0.50980392 0.60784314 0.66666667]
 [0.23529412 0.31372549 0.35294118]]


>Q.6: Population Growth Analysis: You have a NumPy array representing the population of a city over 10 years. Calculate the annual growth rate and identify the year with the highest growth.


In [13]:
population = np.array([10000, 10500, 11000, 11550, 12300, 13000, 13500, 14000, 15000, 16000])

annual_growth_rate = np.diff(population) / population[:-1] * 100

year_of_highest_growth = np.argmax(annual_growth_rate) + 1  

print("Annual Growth Rate (%):", annual_growth_rate)
print(f"The year with the highest growth is Year {year_of_highest_growth + 1} with a growth rate of {annual_growth_rate[year_of_highest_growth]:.2f}%")

Annual Growth Rate (%): [5.         4.76190476 5.         6.49350649 5.69105691 3.84615385
 3.7037037  7.14285714 6.66666667]
The year with the highest growth is Year 9 with a growth rate of 6.67%


>Q.7: Traffic Data Analysis: Given a 2D NumPy array where each row represents the number of vehicles passing through a checkpoint in different hours of the day over a week, calculate the total traffic for each day and the busiest hour of the week.


In [15]:
traffic_data = np.array([
    [100, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340],
    [90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320],
    [80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310],
    [70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300],
    [60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
    [50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280],
    [40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270]
])

total_traffic_per_day = np.sum(traffic_data, axis=1)

busiest_hour_index = np.argmax(traffic_data)
busiest_hour_day = busiest_hour_index // traffic_data.shape[1]  # Row index (day)
busiest_hour_time = busiest_hour_index % traffic_data.shape[1]   # Column index (hour)

print("Total traffic for each day:", total_traffic_per_day)
print(f"Busiest hour of the week: Day {busiest_hour_day + 1}, Hour {busiest_hour_time + 1}, Vehicles: {traffic_data[busiest_hour_day, busiest_hour_time]}")

Total traffic for each day: [5390 4920 4680 4440 4200 3960 3720]
Busiest hour of the week: Day 1, Hour 24, Vehicles: 340


>Q.8: Product Inventory Management: You have a NumPy array representing the stock levels of different products in a warehouse. Reorder the products with stock levels below a threshold (e.g., 50 units).

In [16]:
stock_levels = np.array([60, 20, 75, 45, 90, 10, 55, 30, 5, 80])

reorder_threshold = 50

products_to_reorder = np.where(stock_levels < reorder_threshold)[0] 

print("Products that need to be reordered (indices):", products_to_reorder)

print("Stock levels of products that need reordering:", stock_levels[products_to_reorder])

Products that need to be reordered (indices): [1 3 5 7 8]
Stock levels of products that need reordering: [20 45 10 30  5]


>Q.9: Game Score Analysis: You have a NumPy array representing the scores of different players in a game over multiple rounds. Identify the player with the highest average score and the round with the highest total score.

In [17]:
scores = np.array([
    [10, 20, 30, 40],  # Player 1
    [15, 25, 35, 45],  # Player 2
    [10, 30, 50, 40],  # Player 3
    [20, 25, 35, 50]   # Player 4
])

average_score_per_player = np.mean(scores, axis=1)

total_score_per_round = np.sum(scores, axis=0)

player_with_highest_avg_score = np.argmax(average_score_per_player)

round_with_highest_total_score = np.argmax(total_score_per_round)

print("Average score per player:", average_score_per_player)
print(f"Player with the highest average score: Player {player_with_highest_avg_score + 1}")

print("Total score per round:", total_score_per_round)
print(f"Round with the highest total score: Round {round_with_highest_total_score + 1}")

Average score per player: [25.  30.  32.5 32.5]
Player with the highest average score: Player 3
Total score per round: [ 55 100 150 175]
Round with the highest total score: Round 4


>Q.10: Financial Portfolio Analysis: You have a NumPy array representing the daily returns of different assets in a financial portfolio over a month. Calculate the portfolio's overall daily return, and identify the asset with the highest volatility.

In [18]:
returns = np.array([
    [0.01, 0.02, 0.015],  # Day 1
    [-0.005, 0.01, 0.02],  # Day 2
    [0.02, -0.01, 0.025],  # Day 3
    [0.015, 0.03, 0.02],   # Day 4
    [0.005, -0.015, 0.01], # Day 5
    [-0.01, 0.005, 0.03],  # Day 6
    [0.02, 0.01, -0.005],  # Day 7
    [0.01, -0.02, 0.015],  # Day 8
    [-0.01, 0.015, 0.01],  # Day 9
    [0.005, 0.025, 0.02],  # Day 10
    [0.03, -0.005, 0.01],  # Day 11
    [-0.005, 0.02, -0.01], # Day 12
    [0.025, 0.01, 0.015],  # Day 13
    [0.02, -0.015, 0.03],  # Day 14
    [0.005, 0.03, 0.025],  # Day 15
    [0.015, -0.005, 0.02], # Day 16
    [0.01, 0.015, 0.01],   # Day 17
    [-0.005, 0.02, -0.005],# Day 18
    [0.025, 0.01, 0.03],   # Day 19
    [-0.01, -0.02, 0.015], # Day 20
    [0.02, 0.03, 0.02],    # Day 21
    [-0.005, 0.02, 0.025], # Day 22
    [0.01, 0.01, -0.01],   # Day 23
    [0.015, 0.03, 0.03],   # Day 24
    [0.02, -0.01, 0.025],  # Day 25
    [0.005, 0.025, 0.01],  # Day 26
    [0.03, 0.01, 0.015],   # Day 27
    [-0.005, 0.02, -0.005],# Day 28
    [0.025, -0.01, 0.03],  # Day 29
    [0.02, 0.03, 0.015]    # Day 30
])

overall_daily_return = np.mean(returns, axis=1)

volatility_per_asset = np.std(returns, axis=0)

asset_with_highest_volatility = np.argmax(volatility_per_asset)

print("Overall daily return for the portfolio over 30 days:")
print(overall_daily_return)

print("\nVolatility (standard deviation) per asset:")
print(volatility_per_asset)

print(f"\nAsset with the highest volatility: Asset {asset_with_highest_volatility + 1}")

Overall daily return for the portfolio over 30 days:
[ 1.50000000e-02  8.33333333e-03  1.16666667e-02  2.16666667e-02
  5.78241159e-19  8.33333333e-03  8.33333333e-03  1.66666667e-03
  5.00000000e-03  1.66666667e-02  1.16666667e-02  1.66666667e-03
  1.66666667e-02  1.16666667e-02  2.00000000e-02  1.00000000e-02
  1.16666667e-02  3.33333333e-03  2.16666667e-02 -5.00000000e-03
  2.33333333e-02  1.33333333e-02  3.33333333e-03  2.50000000e-02
  1.16666667e-02  1.33333333e-02  1.83333333e-02  3.33333333e-03
  1.50000000e-02  2.16666667e-02]

Volatility (standard deviation) per asset:
[0.01234796 0.01603901 0.01186615]

Asset with the highest volatility: Asset 2
