# Abdullah 
### Numpy assingment 1

In [3]:
import numpy as np

Q1.1: Create a 1D array, a 2D array, and a 3D array.

In [4]:
arr1 = np.array([1, 2, 3, 8])
arr2 = np.array([[1, 6, 2,3], [4, 3, 6,1]])
arr3 = np.array([[[3, 5,4,7], [3, 8, 5, 9]],[[5, 4, 6, 9], [7, 8, 3,1]]])


arr1, arr2, arr3

(array([1, 2, 3, 8]),
 array([[1, 6, 2, 3],
        [4, 3, 6, 1]]),
 array([[[3, 5, 4, 7],
         [3, 8, 5, 9]],
 
        [[5, 4, 6, 9],
         [7, 8, 3, 1]]]))

Q1.2: Perform slicing operations on arrays.

In [147]:
print("slicing arr1")
print(arr1[1:3])
print("slicing arr2")
print(arr2[1:,1:3])
print("slicing arr3")
print(arr3[1:3,1:3])


slicing arr1
[2 3]
slicing arr2
[[3 6]]
slicing arr3
[[[7 8 3 1]]]


Q1.3: Perform basic arithmetic operations on arrays.

In [89]:
print("Addition: \n",arr1+arr1)

Addition: 
 [ 2  4  6 16]


In [90]:
print("Subraction: \n",arr2-arr2)

Subraction: 
 [[0 0 0 0]
 [0 0 0 0]]


In [91]:
print("Multipication: \n",arr1*arr3)

Multipication: 
 [[[ 3 10 12 56]
  [ 3 16 15 72]]

 [[ 5  8 18 72]
  [ 7 16  9  8]]]


In [92]:
print("Division \n",arr2/arr3)

Division 
 [[[0.33333333 1.2        0.5        0.42857143]
  [1.33333333 0.375      1.2        0.11111111]]

 [[0.2        1.5        0.33333333 0.33333333]
  [0.57142857 0.375      2.         1.        ]]]


Q2: Array Creation and Manipulation

Q2.1: Create arrays using different functions: arange, linspace, zeros, ones, eye, random.

In [62]:
np.arange(5,50,10)

array([ 5, 15, 25, 35, 45])

In [67]:
np.linspace(5,50,4)

array([ 5., 20., 35., 50.])

In [69]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [70]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.eye(4)   

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
np.random.rand(2,2)

array([[0.45099678, 0.96854074],
       [0.25096087, 0.759649  ]])

Q2.2: Reshape an array.

In [125]:
arrray = np.random.randint(10,80,10)
arrray.reshape(2,5)

array([[39, 20, 19, 39, 37],
       [13, 37, 69, 62, 40]], dtype=int32)

Q2.3: Concatenate and split arrays.

In [120]:
# Concatenate
arr_1 = np.random.randint(10,80,10)
arr_2 = np.random.randint(90,200,10)
arr_3 =np.concatenate((arr,arr_2))
arr_3

array([ 17,  59,  24,  10,  13,  56,  21,  21,  23,  60, 177,  98,  97,
       123, 116,  99, 105, 122, 111, 159], dtype=int32)

In [123]:
# Split
np.split(arr_2,2)

[array([177,  98,  97, 123, 116], dtype=int32),
 array([ 99, 105, 122, 111, 159], dtype=int32)]

Q3: Statistical Operations

Q3.1: Compute mean, median, variance, and standard deviation of an array.

In [142]:
arr= np.random.randint(10,90,10)
print("Mean of array: ",np.mean(arr))
print("Median of array: ",np.median(arr))
print("Standard Deviation of array:",np.std(arr))
print("Variance of array:",np.var(arr))

Mean of array:  44.7
Median of array:  45.5
Standard Deviation of array: 24.645689278249044
Variance of array: 607.41


Q3.2: Find the minimum and maximum values in an array along with their indices.

In [145]:
arr= np.random.randint(10,90,10)

print(arr)
print("Min value is :",arr.min())
print("Max value is :",arr.max())

[50 89 75 80 56 77 31 20 15 26]
Min value is : 15
Max value is : 89


Q3.3: Compute the sum and product of array elements.

In [146]:
print("Sumation value of :",arr.sum())
print("Product value of :",arr.prod())

Sumation value of : 519
Product value of : 27838530720000000


Q4: Broadcasting

Q4.1: Demonstrate broadcasting with examples of different shapes of arrays.

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10], [20], [30]])

result = A + B
print(result)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


Q4.2: Explain the concept of broadcasting and how it works in NumPy.

Broadcasting operates on the principle of aligning arrays by their dimensions, starting from the trailing dimensions (i.e., from right to left). If the dimensions of two arrays differ, NumPy tries to "expand" the smaller array to match the shape of the larger one by applying the following rules:

Q5: Linear Algebra

Q5.1: Perform matrix multiplication.

In [8]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
result = A @ B


print(result)

[[ 58  64]
 [139 154]]


Q5.2: Compute the determinant, inverse, and eigenvalues of a matrix.

In [10]:
A = np.array([[1, 6],
              [9, 4]])
determinant = np.linalg.det(A)
inverse = np.linalg.inv(A)
eigenvalues = np.linalg.eigvals(A)
print("Determinant:", determinant)
print("Inverse:")
print(inverse)
print("Eigenvalues:", eigenvalues)

Determinant: -50.000000000000014
Inverse:
[[-0.08  0.12]
 [ 0.18 -0.02]]
Eigenvalues: [-5. 10.]


Q5.3: Solve a system of linear equations.

In [12]:
A = np.array([[1, 3], [7, 4]])
b = np.array([5, 6])
x = np.linalg.solve(A, b)

print("Solution for x and y:", x)

Solution for x and y: [-0.11764706  1.70588235]


Q6: Advanced Indexing and Slicing

Q6.1: Use Boolean indexing to filter an array.

In [14]:
array = np.array([50, 20, 30, 40, 50, 60])
condition = array > 30
filtered_array = array[condition]

print("Original array:", array)
print("Condition:", condition)
print("Filtered array:", filtered_array)

Original array: [50 20 30 40 50 60]
Condition: [ True False False  True  True  True]
Filtered array: [50 40 50 60]


Q6.2: Use fancy indexing to select specific elements from an array.

In [15]:
array = np.array([10, 20, 30, 40, 50, 60])
indices = [0, 2, 4]
selected_elements = array[indices]

print("Selected elements:", selected_elements)

Selected elements: [10 30 50]


Q6.3: Perform advanced slicing operations.

In [18]:
array = np.array([10, 20, 30, 40, 50, 60])
basic_slice = array[1:4]
print("Original array:", array)
print("Sliced array (index 1 to 4):", basic_slice)

Original array: [10 20 30 40 50 60]
Sliced array (index 1 to 4): [20 30 40]


Q7: Random Sampling

Q7.1: Generate random numbers from different distributions.

In [19]:
uniform_random = np.random.uniform(0, 1, 5)
print("Uniform Distribution:", uniform_random)

Uniform Distribution: [0.69016918 0.0613245  0.71040916 0.45760564 0.06469782]


In [22]:
array = np.array([1, 4, 3, 6, 5, 2, 7, 1, 8, 10])
print("Original array:", array)
np.random.shuffle(array)
print("Shuffled array:", array)

Original array: [ 1  4  3  6  5  2  7  1  8 10]
Shuffled array: [ 4  6  8 10  5  7  1  3  1  2]
