# problem 1

In [1]:
import numpy as np

# a. Create a NumPy array of shape (4, 5)

In [2]:
array_1 = np.random.randint(1, 101, size=(4, 5))
print("Original Array (4x5):\n", array_1)

Original Array (4x5):
 [[ 35  39  27 100   3]
 [ 69  77   4   4  54]
 [ 56  75  88  44  74]
 [ 67  81  35  70   3]]


# b. Reshape the array into a shape of (2, 10) and explain how reshaping works in NumPy

In [3]:
reshaped_array = array_1.reshape(2, 10)
print("\nReshaped Array (2x10):\n", reshaped_array)


Reshaped Array (2x10):
 [[ 35  39  27 100   3  69  77   4   4  54]
 [ 56  75  88  44  74  67  81  35  70   3]]


# c. Perform element-wise addition with another array of shape (2, 10)

In [4]:
array_2 = np.random.randint(1, 101, size=(2, 10))
added_array = reshaped_array + array_2
print("\nElement-wise Addition with another Array (2x10):\n", added_array)


Element-wise Addition with another Array (2x10):
 [[ 73  91 116 132  56 164 169  68  56 109]
 [ 73 167  95  79  94 163 148  47 119  13]]


# d. Calculate the dot product of two compatible arrays

In [5]:
array_3 = np.random.randint(1, 101, size=(5, 4))
dot_product = np.dot(array_1, array_3)
print("\nDot Product of two Arrays (4x5) . (5x4):\n", dot_product)


Dot Product of two Arrays (4x5) . (5x4):
 [[12593  4737 13277  7516]
 [ 8106  6772 12745 12737]
 [17474 15699 16345 14369]
 [12435  7177 15399 11696]]


# e. Create a masked array from the original array, masking all values below the median

In [6]:
median_value = np.median(array_1)
masked_array = np.ma.masked_less(array_1, median_value)
print("\nMasked Array (Values below Median are masked):\n", masked_array)


Masked Array (Values below Median are masked):
 [[-- -- -- 100 --]
 [69 77 -- -- --]
 [56 75 88 -- 74]
 [67 81 -- 70 --]]


**# problem 2**

***# A***

In [7]:
import numpy as np


array_1 = np.array([1, 2, 3])  # Shape (3,)
array_2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  # Shape (3, 3)

result = array_1 + array_2
print("Broadcasting Result:\n", result)




Broadcasting Result:
 [[11 22 33]
 [41 52 63]
 [71 82 93]]


# b. Create two arrays with different shapes that can be broadcasted together and perform an arithmetic


In [8]:

array_1 = np.array([[5], [10]])


array_2 = np.array([[1, 2, 3]])


result = array_1 + array_2
print("\nBroadcasted Arrays Addition Result:\n", result)





Broadcasted Arrays Addition Result:
 [[ 6  7  8]
 [11 12 13]]


# c. Discuss how strides in NumPy arrays affect memory access patterns when slicing an array.


In [ ]:
#Strides define how many bytes the NumPy array should move in memory to access the next element along each dimension. Strides impact how the array slices and how efficiently data is accessed in memory.

# d. Create an example to demonstrate the impact of strides on array slicing and performance.

In [9]:

large_array = np.arange(100).reshape(10, 10)


normal_slice = large_array[::2, ::2]
print("\nNormal Slice Result:\n", normal_slice)


from numpy.lib.stride_tricks import as_strided

strided_slice = as_strided(large_array, shape=(5, 5), strides=(20, 8))
print("\nStrided Slice Result:\n", strided_slice)






Normal Slice Result:
 [[ 0  2  4  6  8]
 [20 22 24 26 28]
 [40 42 44 46 48]
 [60 62 64 66 68]
 [80 82 84 86 88]]

Strided Slice Result:
 [[          0           1           2           3           4]
 [12884901888 17179869184 21474836480 25769803776 30064771072]
 [          5           6           7           8           9]
 [34359738368 38654705664 42949672960 47244640256 51539607552]
 [         10          11          12          13          14]]


# e. Analyze how changing the order of dimensions’ affects broadcasting and provide a scenario


In [10]:

array_1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
array_2 = np.array([10, 20, 30])  # Shape (3,)
result = array_1 + array_2
print("\nBroadcasting with Matching Last Dimension:\n", result)
array_1_transposed = array_1.T  # Now array_1 has shape (3, 2)
try:
    result = array_1_transposed + array_2
    print("\nBroadcasting with Transposed Array:\n", result)
except ValueError as e:
    print("\nBroadcasting Error with Transposed Array:", e)





Broadcasting with Matching Last Dimension:
 [[11 22 33]
 [14 25 36]]

Broadcasting Error with Transposed Array: operands could not be broadcast together with shapes (3,2) (3,) 


## ***problem*** 3

# A

In [11]:

image = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)
print("RGB Image Array:\n", image)


red_channel = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel = image[:, :, 2]

print("\nRed Channel:\n", red_channel)
print("\nGreen Channel:\n", green_channel)
print("\nBlue Channel:\n", blue_channel)




RGB Image Array:
 [[[ 98  13 149]
  [185 234  13]
  [ 73 195 255]
  [123 213   3]]

 [[206 120 121]
  [122  25 119]
  [ 38 194  27]
  [183  39 219]]

 [[108  11 186]
  [ 55 189  13]
  [163 229 212]
  [173  32 242]]

 [[ 43  86 218]
  [183  26 162]
  [ 46 240 202]
  [ 38  13  39]]]

Red Channel:
 [[ 98 185  73 123]
 [206 122  38 183]
 [108  55 163 173]
 [ 43 183  46  38]]

Green Channel:
 [[ 13 234 195 213]
 [120  25 194  39]
 [ 11 189 229  32]
 [ 86  26 240  13]]

Blue Channel:
 [[149  13 255   3]
 [121 119  27 219]
 [186  13 212 242]
 [218 162 202  39]]


# B

In [12]:

flattened_image = image.flatten()
print("\nFlattened Image Array (1D):\n", flattened_image)




Flattened Image Array (1D):
 [ 98  13 149 185 234  13  73 195 255 123 213   3 206 120 121 122  25 119
  38 194  27 183  39 219 108  11 186  55 189  13 163 229 212 173  32 242
  43  86 218 183  26 162  46 240 202  38  13  39]


# c

In [13]:

sub_array = image[1:3, 1:3, :]
print("\nSub-array (2x2 section):\n", sub_array)


sub_array[:, :, 0] = 255

print("\nModified Sub-array:\n", sub_array)
print("\nOriginal Image after Modifying Sub-array:\n", image)





Sub-array (2x2 section):
 [[[122  25 119]
  [ 38 194  27]]

 [[ 55 189  13]
  [163 229 212]]]

Modified Sub-array:
 [[[255  25 119]
  [255 194  27]]

 [[255 189  13]
  [255 229 212]]]

Original Image after Modifying Sub-array:
 [[[ 98  13 149]
  [185 234  13]
  [ 73 195 255]
  [123 213   3]]

 [[206 120 121]
  [255  25 119]
  [255 194  27]
  [183  39 219]]

 [[108  11 186]
  [255 189  13]
  [255 229 212]
  [173  32 242]]

 [[ 43  86 218]
  [183  26 162]
  [ 46 240 202]
  [ 38  13  39]]]


# D

In [14]:
import time


list_data = list(range(1000000))
array_data = np.arange(1000000)


start = time.time()
sum(list_data)
print("Sum using lists:", time.time() - start, "seconds")


start = time.time()
np.sum(array_data)
print("Sum using NumPy:", time.time() - start, "seconds")


Sum using lists: 0.010526895523071289 seconds
Sum using NumPy: 0.001245737075805664 seconds


# E

In [15]:
def normalize_image(image):
    """
    Normalize pixel values of the image to the range [0, 1].
    """
    normalized_image = image / 255.0
    return normalized_image


normalized_image = normalize_image(image)
print("\nNormalized Image Array (Values between 0 and 1):\n", normalized_image)





Normalized Image Array (Values between 0 and 1):
 [[[0.38431373 0.05098039 0.58431373]
  [0.7254902  0.91764706 0.05098039]
  [0.28627451 0.76470588 1.        ]
  [0.48235294 0.83529412 0.01176471]]

 [[0.80784314 0.47058824 0.4745098 ]
  [1.         0.09803922 0.46666667]
  [1.         0.76078431 0.10588235]
  [0.71764706 0.15294118 0.85882353]]

 [[0.42352941 0.04313725 0.72941176]
  [1.         0.74117647 0.05098039]
  [1.         0.89803922 0.83137255]
  [0.67843137 0.1254902  0.94901961]]

 [[0.16862745 0.3372549  0.85490196]
  [0.71764706 0.10196078 0.63529412]
  [0.18039216 0.94117647 0.79215686]
  [0.14901961 0.05098039 0.15294118]]]


## problem **4** *italicized text*

#a

In [16]:

data = np.random.randn(1000)


mean_value = np.mean(data)
median_value = np.median(data)
variance_value = np.var(data)

print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Variance: {variance_value}")




Mean: -0.0033194490640080796
Median: 0.03841451236806097
Variance: 0.9882090124972832


# B

In [17]:

population_variance = np.var(data)


sample_variance = np.var(data, ddof=1)

print(f"Population Variance: {population_variance}")
print(f"Sample Variance: {sample_variance}")




Population Variance: 0.9882090124972832
Sample Variance: 0.9891982107079912


#C

In [18]:
import matplotlib.pyplot as plt


plt.hist(data, bins=30, edgecolor='black')
plt.title("Histogram of Random Numbers")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()




#d

In [19]:

Q1 = np.percentile(data, 25)
Q3 = np.percentile(data, 75)


IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR


outliers = data[(data < lower_bound) | (data > upper_bound)]

print(f"Number of Outliers: {len(outliers)}")
print("Outliers:\n", outliers)



Number of Outliers: 5
Outliers:
 [ 2.66709864  2.83564592 -2.8897859  -3.38671861 -2.65757629]


## ***problem 5***

#A

In [20]:
import numpy as np


n, d = 5, 3
m = 4


X = np.random.rand(n, d)
Y = np.random.rand(m, d)


D = np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :]) ** 2, axis=2))

print("Pairwise Euclidean Distance Matrix D:\n", D)




Pairwise Euclidean Distance Matrix D:
 [[0.58933311 0.33234042 0.83176523 0.78129521]
 [0.86787531 0.66440253 0.7396835  0.24344764]
 [0.82100384 0.7178939  0.61705854 0.38410867]
 [0.87255198 0.77884663 0.27881826 0.47360226]
 [0.78360264 0.74284418 0.44204504 0.99223469]]


#B

In [21]:
def sliding_window_mean(arr, window_size):

    shape = arr.shape[0] - window_size + 1, window_size
    strides = arr.strides[0], arr.strides[0]

    windows = np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)
    return np.mean(windows, axis=1)


arr = np.random.rand(10)
window_size = 3
means = sliding_window_mean(arr, window_size)

print(f"Array: {arr}")
print(f"Sliding Window Means (Window Size {window_size}): {means}")




Array: [0.56158021 0.86681881 0.50893923 0.40467518 0.37685235 0.51778138
 0.50966879 0.08623135 0.17192641 0.59402982]
Sliding Window Means (Window Size 3): [0.64577942 0.59347774 0.43015559 0.43310297 0.46810084 0.37122717
 0.25594218 0.28406253]


#D

In [22]:

D_modified = np.copy(D)
D_modified[D_modified < 5] = 0
D_modified[D_modified > 100] = 1

count_values_between_5_and_100 = np.sum((D_modified > 0) & (D_modified < 1))

print(f"Number of values between 5 and 100: {count_values_between_5_and_100}")




Number of values between 5 and 100: 0
