In [146]:
import pandas as pd
import numpy as np

# one D,two D and three D array

In [147]:
array_1d = np.array([1, 8, 3, 2, 5])

In [148]:
array_1d

array([1, 8, 3, 2, 5])

# two d

In [149]:
array_2d = np.array([[1, 7, 3], [9, 5, 6]])
array_2d

array([[1, 7, 3],
       [9, 5, 6]])

# three D

In [150]:
array_3d = np.array([[[1, 8], [2, 4]], [[5, 6], [3, 8]]])
array_3d

array([[[1, 8],
        [2, 4]],

       [[5, 6],
        [3, 8]]])

# slicing operat

In [151]:

arr = np.array([4, 6, 3, 8, 9, 1, 2,5, 9, 10])


slice1 = arr[2:5]  # Elements from index 2 to 4

slice2 = arr[:4]   # First four elements

slice3 = arr[5:]   # Elements from index 5 to the end

slice4 = arr[::2]  # Every second element

slice5 = arr[::-1] # Reverse the array

print(slice1)
print(slice2)
print(slice3)
print(slice4)
print(slice5)


[3 8 9]
[4 6 3 8]
[ 1  2  5  9 10]
[4 3 9 2 9]
[10  9  5  2  1  9  8  3  6  4]


# arithmetic basic 

In [152]:




array1 = np.array([40, 20, 30, 10])
array2 = np.array([1, 3, 5, 4])


addition = array1 + array2

subtraction = array1 - array2


multiplication = array1 * array2


division = array1 / array2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Addition: [41 23 35 14]
Subtraction: [39 17 25  6]
Multiplication: [ 40  60 150  40]
Division: [40.          6.66666667  6.          2.5       ]


# Creation and Manipulation

In [153]:

array_arange = np.arange(10)

array_linspace = np.linspace(0, 1, 5)

array_zeros = np.zeros((2, 2))

array_ones = np.ones((2, 2))

array_eye = np.eye(3)  # Identity matrix



array_random = np.random.random((2, 3))

print(array_arange)
print(array_linspace)
print(array_zeros)
print(array_ones)
print(array_eye)
print(array_random)


[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.3497142  0.19544791 0.93153002]
 [0.70339158 0.74439804 0.18880345]]


# reshaped


In [154]:

array_reshaped = array_arange.reshape(2, 5)
print(array_reshaped)


[[0 1 2 3 4]
 [5 6 7 8 9]]


# Concatenate and split arrays.

In [155]:

array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

concatenated_array = np.concatenate((array1, array2))



split_arrays = np.array_split(concatenated_array, 2)

print("Concatenated Array:", concatenated_array)
print("Split Arrays:", split_arrays)


Concatenated Array: [1 2 3 4 5 6]
Split Arrays: [array([1, 2, 3]), array([4, 5, 6])]


# Statistical Operations mean ,median ,mode and std dev

In [156]:



array = np.array([1, 2, 3, 4, 5, 6, 7, 8])


mean_value = np.mean(array)

print("Mean:", mean_value)

median_value = np.median(array)

print("Median:", median_value)




std_deviation = np.std(array)

print("Standard Deviation:", std_deviation)




Mean: 4.5
Median: 4.5
Standard Deviation: 2.29128784747792


# find max and min value

In [157]:

array = np.array([3, 1, 7, 0, 5, 9])


min_value,
min_index = np.min(array), np.argmin(array)
max_value,
max_index = np.max(array), np.argmax(array)

print(f"Min: {min_value} at index {min_index}")
print(f"Max: {max_value} at index {max_index}")


NameError: name 'min_value' is not defined

In [13]:

arr = np.array([3, 1, 7, 0, 5, 9])

min_value = arr.min()
min_index = arr.argmin()
max_value = arr.max()
max_index = arr.argmax()

print("Min:", min_value, "at index", min_index)
print("Max:", max_value, "at index", max_index)


Min: 0 at index 3
Max: 9 at index 5


# sum and product of array element

In [14]:

arr = np.array([1, 2, 3, 4])


array_sum = arr.sum()     

array_product = arr.prod() 

print("Sum:", array_sum)

print("Product:", array_product)


Sum: 10
Product: 24


# brodcasting in different shape

In [15]:


arr1 = np.array([1, 2, 3])


arr2 = np.array([[10], [20], [30]])

result = arr1 + arr2

print("1D Array:\n", arr1)

print("2D Array:\n", arr2)

print("Result of Broadcasting:\n", result)


1D Array:
 [1 2 3]
2D Array:
 [[10]
 [20]
 [30]]
Result of Broadcasting:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


# matrix multiplication

In [16]:



matrix1 = np.array([[1, 2], [3, 4]])

matrix2 = np.array([[5, 6], [7, 8]])

result = matrix1 * matrix2 

print(result)


[[ 5 12]
 [21 32]]


# determinant

In [121]:

matrix = np.array([[1, 2], [3, 4]])

determinant = np.linalg.det(matrix)

print("The determinant of the matrix is:", determinant)


The determinant of the matrix is: -2.0000000000000004


# inverse

 # linear equations.

In [158]:
import numpy as np


A = np.array([[2, 1], [1, -1]])

B = np.array([4, 1])

solution = np.linalg.solve(A, B)

print("The solution is:", solution)


The solution is: [1.66666667 0.66666667]


# Advanced Indexing and Slicing

In [22]:

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 2])
result = array[row_indices, col_indices]


sliced_array = array[1:, 1:]

print("Advanced Indexing Result:", result)
print("Sliced Array:\n", sliced_array)


Advanced Indexing Result: [2 4 9]
Sliced Array:
 [[5 6]
 [8 9]]



# Use Boolean indexing to filter an array.

In [23]:

import numpy as np

array = np.array([10, 20, 30, 40, 50, 60])

condition = array > 30

filtered_array = array[condition]

print(filtered_array)


[40 50 60]


# fancing index

In [24]:

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

selected_elements = array[[0, 1, 2], [1, 0, 2]]
print(selected_elements)


[2 4 9]


# random sampling

In [25]:



sample = random.sample(range(1, 101), 5)
print(sample)


NameError: name 'random' is not defined

In [26]:


import random

sample = random.sample(range(1, 101), 5)
print(sample)


[48, 29, 21, 35, 1]


# Generate random numbers from different distributions.

In [27]:

uniform_random = np.random.uniform(low=0, high=1, size=5)
print("Uniform Distribution:", uniform_random)

normal_random = np.random.normal(loc=0, scale=1, size=5)
print("Normal Distribution:", normal_random)

binomial_random = np.random.binomial(n=10, p=0.5, size=5)
print("Binomial Distribution:", binomial_random)



Uniform Distribution: [0.43954633 0.07097568 0.29759225 0.92673809 0.95649303]
Normal Distribution: [-0.75113023 -0.35950332 -2.38613548  0.06758872  0.01903416]
Binomial Distribution: [6 4 5 5 5]


# random set from dataset

In [28]:



data = {
    'A': np.random.rand(100),
    'B': np.random.rand(100),
    'C': np.random.rand(100)
}
df = pd.DataFrame(data)


random_samples = df.sample(n=10, random_state=1)
print(random_samples)


           A         B         C
80  0.179966  0.663310  0.224088
84  0.685648  0.230706  0.093205
33  0.172875  0.293538  0.538120
81  0.011278  0.982729  0.173158
93  0.052812  0.356797  0.319218
17  0.140231  0.331661  0.444282
36  0.945085  0.749508  0.409717
82  0.828526  0.577864  0.060020
69  0.706879  0.900367  0.305813
65  0.449368  0.722581  0.029756


# random shaffeling on array

In [29]:
import random

def shuffle_array(arr):
    random.shuffle(arr)
    return arr

array = [1, 2, 3, 4, 5]
shuffled_array = shuffle_array(array)
print(shuffled_array)


[2, 5, 3, 1, 4]
