Rimsha Saleem
Shrimsha110@gmail.com

#### Assignment # 1 Sales data analysis

In [151]:
import numpy as np

In [152]:
sale_data = np.array([1500,6000,8000,7000,4000,6000,1300,2500,4500,3600,8000,9000,7000,5000,4000,10000,5600,7200,6500,3200,7500,90000,6700,5500,5800,4100,8000,3000,1000,42000])

In [153]:
sale_data

array([ 1500,  6000,  8000,  7000,  4000,  6000,  1300,  2500,  4500,
        3600,  8000,  9000,  7000,  5000,  4000, 10000,  5600,  7200,
        6500,  3200,  7500, 90000,  6700,  5500,  5800,  4100,  8000,
        3000,  1000, 42000])

In [154]:
Total_sale = np.sum (sale_data)
Total_sale

np.int64(283500)

In [155]:
average_sale = np.mean(sale_data)
average_sale

np.float64(9450.0)

In [156]:
highestsale = np.argmax(sale_data) 
highestamount = sale_data[highestsale]
highestamount


np.int64(90000)

#### Question # 2
Weather data processing

In [157]:
twodarray = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
twodarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [158]:
average_temp = np.mean(twodarray, axis=1)
average_temp

array([ 3.,  8., 13., 18., 23., 28., 33.])

In [159]:
highest_temp = np.argmax(average_temp)
highest_temps = average_temp[highest_temp]
highest_temps

np.float64(33.0)

Question # 3 Financial analysis

In [160]:
grades = np.array([[11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25],
                     [26,27,28,29,30],
                     [31,32,33,34,35]])
grades

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [161]:
average_grade = np.mean(grades, axis=1)
average_grade

array([13., 18., 23., 28., 33.])

In [162]:
overallclass = np.mean(grades, axis=0)
overallclass

array([21., 22., 23., 24., 25.])

In [163]:
highest_avererage = np.argmax(average_grade)
y = average_grade[highest_avererage]
y


np.float64(33.0)

Question # 4 image processing

In [164]:
image = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
image

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [165]:
normal_image = image/255.0
normal_image

array([[0.00392157, 0.00784314, 0.01176471, 0.01568627, 0.01960784],
       [0.02352941, 0.02745098, 0.03137255, 0.03529412, 0.03921569]])

In [166]:
highest_image = np.max(image)
highimage =np.unravel_index(np.argmax (image), image.shape)
highimage

(np.int64(1), np.int64(4))

#### Question #  6 population of growth 

In [167]:
an = np.array([1,2,3,4,5,6,7,8,9,10])
an

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [168]:
an_growth = np.diff(an)
an_growth_rate = (an_growth/an[:-1])*100
an_growth_rate

array([100.        ,  50.        ,  33.33333333,  25.        ,
        20.        ,  16.66666667,  14.28571429,  12.5       ,
        11.11111111])

In [169]:
max_growth = np.max(an_growth)
max_growth_yearly = np.argmax(an_growth) + 1
max_growth_yearly

np.int64(1)

In [170]:
average_rate = np.mean(an_growth_rate)
average_rate

np.float64(31.432980599647262)

Question # 7  traffic data analysis

In [171]:
trafic_data = np.array([[1,2,3,4,5],[7,8,9,70,10]])
trafic_data

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 70, 10]])

In [172]:
total_traficday = np.sum(trafic_data, axis=1)
total_traficday

array([ 15, 104])

In [173]:
total_trafichour = np.sum(trafic_data,axis=0)
total_trafichour

array([ 8, 10, 12, 74, 15])

In [174]:
max_traficdata = np.argmax(total_trafichour)
max_traficdata

np.int64(3)

Question # 8 product invertory managment

In [175]:
wearhouse = np.array([10,20,30,40,50,60,70,80,90,100])
wearhouse

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [176]:
lowthreshold = 50
highthreshold = 100

In [177]:
thresholdlowproduct = wearhouse<lowthreshold
thresholdlowproduct

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [178]:
wearhouse[thresholdlowproduct] = highthreshold
wearhouse

array([100, 100, 100, 100,  50,  60,  70,  80,  90, 100])

Question # 9 game scoure managment

In [181]:
scoure = np.array([[1,20,50,40,70,80,90],[40,60,70,30,50,73,90]])
scoure

array([[ 1, 20, 50, 40, 70, 80, 90],
       [40, 60, 70, 30, 50, 73, 90]])

In [182]:
average_scoure = np.mean(scoure, axis=1)
average_scoure

array([50.14285714, 59.        ])

In [185]:
highestaverage = np.argmax(average_scoure)
high = average_scoure[highestaverage]
high

np.float64(59.0)

In [192]:
totalscoure = np.sum(scoure, axis=0)
totalscoures = np.argmax(totalscoure)
highs = totalscoure[totalscoures]
highs

np.int64(180)

Question # 10 Financical portfolio

In [199]:
sum = np.array([[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]])
sum

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [201]:
portfolio = np.sum(sum, axis=0)
portfolio

array([17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45])

In [207]:
assest = np.std(sum, axis=1)
highvol = np.argmax(assest)
highestvol = assest[highvol]
highestvol

np.float64(4.320493798938574)

In [211]:
highpol = np.argmax(portfolio)
highestpol = portfolio[highpol]
highpol

np.int64(14)