# Assignment 1
## Nmae: Neha Izhar
### nehaizhar123@gmail.com

### Question No 01

In [1]:
import numpy as np

In [7]:
A=np.array([[2,8,6,7,8],[8,6,7,7,7],[1,2,9,7,10],[14,6,8,3,4],[11,8,6,3,2]])
A

array([[ 2,  8,  6,  7,  8],
       [ 8,  6,  7,  7,  7],
       [ 1,  2,  9,  7, 10],
       [14,  6,  8,  3,  4],
       [11,  8,  6,  3,  2]])

In [8]:
B=np.array([10,6,9,4,12])
B

array([10,  6,  9,  4, 12])

In [9]:
sol = np.linalg.solve(A, B)
print("Masses\n",sol)


Masses
 [-1.75952203  1.0545183   4.17998506  2.27035101 -4.48618372]


### Question No 02

#### (A) Use arange to create a variable named foo that stores an array of numbers from 0 to 29, inclusive. Print foo and its shape.

In [10]:
foo=np.arange(30)
print("foo =", foo)

foo = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


#### (B) Use the reshape function to change foo to a validly-shaped two-dimensional matrix and store it in a new variable called bar. Print bar and its shape.

In [13]:
bar=foo.reshape(6,5)
print("bar\n",bar)

bar
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [14]:
g=np.shape(bar)
print("Shape of Bar\n",g)

Shape of Bar
 (6, 5)


### (C) Create a third variable, baz that reshapes it into a valid three-dimensional shape. Print baz and its shape.

In [18]:
baz=foo.reshape(5,2,3)
print("baz\n",bar)

baz
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [19]:
v=np.shape(baz)
print("Shape of Baz\n",v)

Shape of Baz
 (5, 2, 3)
