Name : Minhas Ahmed

In [2]:
import numpy as np

In [ ]:
A - You make a measurement of objects {1, 2} against objects {3, 4} and get a difference of 1kg.
Write this as a linear equation for the masses.

# Part (A):-
  Set up the linear equation based on the measurement
# Measurement:-
  {1, 2} vs {3, 4} with a difference of 1kg 
# Linear equation:-
  m1 + m2 - (m3 + m4) = 1
# we have the equation:-
 m1 + m2 - m3 - m4 = 1

# Part (D):-
  Matrix representation
# Let's assume we have the following measurements:
# Measurement 1:-
  m1 + m2 - m3 - m4 = 1
# Measurement 2:-
  m1 - m5 = 2
# Measurement 3:-
  m2 - m4 = -1
# Measurement 4:-
  m1 + m3 - m5 = 0

In [10]:
A = np.array([
    [1, 1, -1, 0],
    [1, 0, 0, -1],
    [0, 1, -1, 0],
    [1, 0, 1, -1]
])

b = np.array([1, 2, -1, 0])

# Solve the system of linear equations
masses = np.linalg.solve(A, b)
print("Masses of the objects:", masses)


Masses of the objects: [ 2. -3. -2. -0.]


B - What is the minimum number of such measurements necessary to recover all five masses?

# Part (A):-
  Create foo array

# Part (B):-
  Reshape foo into a 2D array (6 rows, 5 columns)

# Part (C):-
  Reshape bar into a 3D array

# Part (D):-
  Indexing into arrays

# Part (E):-
  Summing over dimensions

# Part (F):-
  Slicing arrays

In [11]:
# Part (A)

foo = np.arange(30)
print("foo:", foo)
print("Shape of foo:", foo.shape)

# Part (B)

bar = foo.reshape(6, 5)
print("bar:\n", bar)
print("Shape of bar:", bar.shape)

# Part (C)

baz = bar.reshape(2, 3, 5)
print("baz:\n", baz)
print("Shape of baz:", baz.shape)

# Part (D)

bar[1, 0] = -1
print("bar after change:\n", bar)
print("Did foo change?", foo)
print("Did baz change?", baz)

# Part (E)

print("Sum over second dimension:", np.sum(baz, axis=1))
print("Sum over third dimension:", np.sum(baz, axis=2))
print("Sum over first and third dimensions:", np.sum(baz, axis=(0, 2)))

# Part (F):-

print("Second row of bar:", bar[1, :])
print("Last column of bar:", bar[:, -1])
print("Top right 2x2 submatrix of bar:", bar[:2, -2:])

foo: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Shape of foo: (30,)
bar:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Shape of bar: (6, 5)
baz:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
Shape of baz: (2, 3, 5)
bar after change:
 [[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Did foo change? [ 0  1  2  3  4 -1  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Did baz change? [[[ 0  1  2  3  4]
  [-1  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
Sum over second dimension: [[ 9 18 21 24 27]
 [60 63 66 69 72]]
Sum over third dimension: [[ 10  29  60]
 [ 85 110 135]]
Sum over first and third dimensions: [ 95 139 195]
Second row of bar: [-1  6  7  8  9]
Last column of bar:

C - If the answer to the above question is N, come up with N − 1 measurements that, when combined with the answer to (A) above would make it possible to recover the masses.

# Part (A):-
  Broadcasting a scalar with a vector

# Part (B):- 
  Create a 10x10 matrix A with Ai,j = i + j

# Part (C):- 
  Standardizing data


In [12]:
# Part (A)

vec = np.arange(10) + 1
print("Vector:", vec)

# Part (B)

A = vec.reshape(-1, 1) + vec
print("Matrix A:\n", A)

# Part (C)

import numpy.random as npr

data = np.exp(npr.randn(50, 5))  
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

print("Mean of columns:", mean)
print("Standard deviation of columns:", std)

normalized = (data - mean) / std
print("Normalized data:", normalized)
print("Mean of normalized data:", np.mean(normalized, axis=0))
print("Standard deviation of normalized data:", np.std(normalized, axis=0))

Vector: [ 1  2  3  4  5  6  7  8  9 10]
Matrix A:
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]
Mean of columns: [1.31438343 1.79558797 2.29980558 1.13643832 1.68699645]
Standard deviation of columns: [1.3292558  2.24658657 3.71537185 0.85969017 1.72776612]
Normalized data: [[ 0.09104665 -0.50864188 -0.46159522 -1.17770428 -0.33258835]
 [-0.22104039 -0.55765932 -0.17063839  0.87085612 -0.816217  ]
 [-0.86581959 -0.19803229 -0.20874921 -0.80881918  0.50580554]
 [-0.6563572   0.36105352 -0.10786578  2.09181769  0.1084469 ]
 [ 0.95322089  0.30442916 -0.26316155 -0.73509361 -0.81306862]
 [ 1.2989264  -0.46219189  1.05567237 -1.2476143  -0.8214083 ]
 [-0.51968875 -0.48633405 -0.34476973 -0.44814713  0.38893435

D - What would A and b be in the matrix form of the linear system corresponding to the N measurements?
That is, if you were to set this up as Am = b where m is the vector of unknown masses. Denote the result
of the ith measurement as bi. (Typeset these using the bmatrix environment.)

# Part (A):-
  Create a Vandermonde matrix

# Part (B):-
  Create a vector of ones and multiply with the Vandermonde matrix

# Part (C):- 
  Solve the linear system using matrix inversion

# Part (D):- 
  Solve using np.linalg.solve

In [14]:
# Part (A)

vander = np.vander(np.arange(12), increasing=True)
print("Vandermonde matrix:\n", vander)

# Part (B)

x = np.ones(12)
b = np.dot(vander, x)
print("Vector b:", b)

# Part (C)

inv_vander = np.linalg.inv(vander)
x_naive = np.dot(inv_vander, b)
print("Naive solution (using inverse):", x_naive)

# Part (D)

x_solve = np.linalg.solve(vander, b)
print("Solution using solve:", x_solve)

Vandermonde matrix:
 [[           1            0            0            0            0
             0            0            0            0            0
             0            0]
 [           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 

Time spent on the assignment: 2 hours