In [21]:
import numpy as np
foo=np.arange(0,30)
print(foo)
print("Shape of foo is :",foo.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Shape of foo is : (30,)


In [22]:
bar=foo.reshape(5,6)
print(bar)
print("shape of bar is ",bar.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
shape of bar is  (5, 6)


In [23]:
baz=foo.reshape(2,3,5)
print(baz)
print("Shape of baz is :",baz.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
Shape of baz is : (2, 3, 5)


In [24]:
bar[1,0]= -1
print("bar after changing value:\n",bar)
print("foo after bar modification:\n",foo)
print("baz after foo modification:\n ",baz)

bar after changing value:
 [[ 0  1  2  3  4  5]
 [-1  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
foo after bar modification:
 [ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
baz after foo modification:
  [[[ 0  1  2  3  4]
  [ 5 -1  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [25]:
sd2=np.sum(baz,axis=1)
print("Sum of baz over second dimension is :",sd2)

Sum of baz over second dimension is : [[15 11 21 24 27]
 [60 63 66 69 72]]


In [26]:
sd3=np.sum(baz,axis=2)
print("Sum of baz over third dimension is :",sd3)

Sum of baz over third dimension is : [[ 10  28  60]
 [ 85 110 135]]


In [27]:
sd13=np.sum(baz,axis=(0,2))
print("Sum of baz over first and third dimension is :",sd13)

Sum of baz over first and third dimension is : [ 95 138 195]


In [28]:
row2=bar[1,:]
print(row2)


[-1  7  8  9 10 11]


In [29]:
last_col=bar[:,-1]
print(last_col)

[ 5 11 17 23 29]


In [30]:
sm=bar[:2,-2:]
print(sm)

[[ 4  5]
 [10 11]]


In [34]:
vector=np.arange(10)+1
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
i=vector.reshape(10,1)
j=vector
A=i+j
print("A is :\n",A)

A is :
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [37]:
import numpy.random as npr
data=np.exp(npr.randn(50,5))
mean=np.mean(data,axis=0)
print("Mean :",mean)
SD=np.std(data,axis=0)
print("Standard Deviation:",SD)

Mean : [1.69604668 1.66411699 1.27971971 1.67756145 1.61203234]
Standard Deviation: [2.33646139 1.88540386 1.12937834 2.22274077 2.08601665]


In [38]:
normalized=(data-mean)/SD
normalized_Mean=np.mean(normalized,axis=0)
normalized_SD=np.std(normalized,axis=0)
print("Mean of each coloumn in normalized data:",normalized_Mean)
print("Standard deviation of each coloumn in normalized data:",normalized_SD)

Mean of each coloumn in normalized data: [-1.68753900e-16 -2.44249065e-16  2.95319325e-16  1.50990331e-16
  1.38777878e-16]
Standard deviation of each coloumn in normalized data: [1. 1. 1. 1. 1.]
