In [1]:
import numpy as np

In [4]:
# Create a 1D array, a 2D array, and a 3D array.

One_dim=np.array([1,2,3,4,5,6,7,8,9,0])

two_dim = np.array([[1,2,3,4,5], [6,7,8,9,0]])

three_dim = np.array([[1,2,3,4], [5,6,7,8], [9,0,1,2]])

print("one dimensional array", One_dim)
print("two dimensional array", two_dim)
print("three dimensional array", three_dim)

one dimensional array [1 2 3 4 5 6 7 8 9 0]
two dimensional array [[1 2 3 4 5]
 [6 7 8 9 0]]
three dimensional array [[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]


In [13]:
# Perform slicing operations on arrays.
marks = np.array([1,2,3,4,5,6,7])
#marks[6] # locating position
marks[2:]


array([3, 4, 5, 6, 7])

In [21]:
# Perform basic arithmetic operations on arrays (addition, subtraction, multiplication, division).

marks1 = np.array([12,11,13,14,15,16,17])
sum =marks+marks1
print("Addition", sum)

subtraction =marks-marks1
print("Subtraction", subtraction)

mutliply =marks*marks1
print("Multiplication", mutliply)

division =marks/marks1
print("Division", division)

Addition [13 13 16 18 20 22 24]
Subtraction [-11  -9 -10 -10 -10 -10 -10]
Multiplication [ 12  22  39  56  75  96 119]
Division [0.08333333 0.18181818 0.23076923 0.28571429 0.33333333 0.375
 0.41176471]


In [25]:
# Array Creation and Manipulation

#array creation
array1 = np.array([[1,2,3,4,5], [6,7,8,9,0]])
array1


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [31]:
# arrange
array1=np.arange(5)
print(array1)

[0 1 2 3 4]


In [29]:
array2=array1.reshape(2,3)
print(array2)

[[0 1 2]
 [3 4 5]]


In [42]:
# linspace

np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [46]:
#zero
np.zeros(4)

array([0., 0., 0., 0.])

In [48]:
#ones
np.ones(4)

array([1., 1., 1., 1.])

In [52]:
#eye
identity=np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# random


In [ ]:
# concate 

In [53]:
#split
array1=np.split

TypeError: split() missing 1 required positional argument: 'indices_or_sections'