Name : Minhas Ahmed

In [9]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd

In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
arr1 = np.array([1, 2, 3, 4, 5])  # Corrected the brackets from square brackets to parentheses
arr2 = np.array([[1, 2], [3, 4]])  # Wrapped the inner lists in additional brackets

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2]
 [3 4]]


In [22]:
arr2 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr2.shape

(2, 3, 3)

In [23]:
emp = np.empty(3)
emp

array([ 1.16919188e-311,  1.16919204e-311, -0.00000000e+000])

In [24]:
arr2.size

18

In [26]:
arr0 = np.zeros([2,3])
arr0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr_identity = np.eye(5)
arr_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Add a new dimension to the end
arr2_reshaped = arr2[..., np.newaxis]

print(arr2_reshaped.shape)

(2, 3, 1)


In [ ]:
array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]]])

In [3]:
arr_random = np.random.rand(2, 3)
print(arr_random)

[[0.3815383  0.70307732 0.10903488]
 [0.19159847 0.54212035 0.11420097]]


In [11]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.ndim)

2


In [13]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
empty_array = np.ndarray((2, 3), dtype=float)
print(empty_array)

[[0.3815383  0.70307732 0.10903488]
 [0.19159847 0.54212035 0.11420097]]


In [16]:
arr3[5] = 9
arr3

array([0, 1, 2, 3, 4, 9, 6, 7, 8, 9])

In [20]:
arr3 = np.arange(10)

for b in arr3:
    print(b)

0
1
2
3
4
5
6
7
8
9


In [21]:
arr3[4] = 18
print(arr3)

[ 0  1  2  3 18  5  6  7  8  9]
