## ***Problem2(25pts)***


In [90]:
import numpy as np

foo = np.arange(0,29)

print(foo)
print(foo.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28]
(29,)


In [91]:
bar = foo.reshape(1,29)
print(bar)
print(bar.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28]]
(1, 29)


In [92]:
baz = foo.reshape(1,29,1)
print(baz)
print(baz.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]]]
(1, 29, 1)


In [93]:


bar[0, 0] = -1
print("Original foo array after modification" ,  foo)


Original foo array after modification [-1  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28]


In [94]:
np.sum(baz, axis=1)

array([[405]])

In [95]:
np.sum(baz, axis =2)

array([[-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [96]:
np.sum(baz , axis = (0,2))

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [97]:
bar1 = np.arange(0, 20).reshape(5, 4)
second_row = bar1[1:]
print(second_row)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [98]:
bar1 = np.arange(0, 20).reshape(5, 4)
second_row = bar1[1:] -1
print(second_row)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]


## ***Problem3(25pts)***

In [99]:
values =np.arange(0,10)

Added = values + 1 
print(values)
print(Added)

Vector = Added.reshape(10,1)
ten_by_ten = Added + Vector
print(ten_by_ten)



[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [100]:
import numpy as np
import numpy.random as npr

# Step 1: Create a fake dataset with 50 examples, each with 5 dimensions
data = np.exp(npr.randn(50, 5))

# Print the original data
print("Original Data:\n", data)


Original Data:
 [[ 1.99684438  0.78618007  1.13215193  0.55849992  2.50122677]
 [ 0.36396607  7.14224872  0.34599126  0.82044037  1.88026961]
 [ 2.71424092  2.1652508   1.28708077  0.30448904  2.85008829]
 [ 1.59530078  0.31342851  0.8277558   3.03690284  5.90264278]
 [ 0.5031546   2.28731878  0.36255867  1.43621585  0.6277012 ]
 [ 0.50111448  0.52273669  2.25852077  0.89164008  4.61039003]
 [ 0.17362717  0.87036799  6.58740187  0.68600758  1.57546074]
 [ 0.51695984  4.88670904  0.25522369  2.24110628  1.27731906]
 [ 1.892768    1.40900036  0.57751162  0.24907912  1.55170333]
 [ 0.50403191  0.11636157  0.67575746  1.77086281  0.56484948]
 [ 7.29380965  0.55051609  1.91597215  2.33879466  0.92607608]
 [ 0.26130856  2.12447506  0.55483246  0.19824453  2.86524013]
 [ 4.18390689  0.14164796  1.20400832  2.80415757  0.35149417]
 [ 0.6241676   1.4628429   0.39894392  0.88649134  0.21796451]
 [ 0.27836698  1.78093707  0.47555366  0.3861989   1.11946198]
 [ 1.61223975  0.56828921 12.96343404  

In [101]:
MEAN = np.mean(data, axis=0)
MEAN

array([1.53321286, 1.87283626, 1.70577428, 1.31628099, 1.36304727])

In [102]:
STD = np.std(data, axis=0)
STD

array([1.94355789, 3.36997768, 2.14797183, 1.42505272, 1.1356624 ])

In [103]:
normalized = (data -     MEAN) / STD
print(normalized)

[[ 2.38547829e-01 -3.22452047e-01 -2.67053015e-01 -5.31756514e-01
   1.00221642e+00]
 [-6.01601216e-01  1.56363423e+00 -6.33054399e-01 -3.47945456e-01
   4.55436710e-01]
 [ 6.07662917e-01  8.67704671e-02 -1.94925047e-01 -7.10003170e-01
   1.30940412e+00]
 [ 3.19454948e-02 -4.62735336e-01 -4.08766293e-01  1.20740926e+00
   3.99731074e+00]
 [-5.29985893e-01  1.22992659e-01 -6.25341350e-01  8.41617011e-02
  -6.47504102e-01]
 [-5.31035578e-01 -4.00625673e-01  2.57334143e-01 -2.97982597e-01
   2.85942614e+00]
 [-6.99534446e-01 -2.97470303e-01  2.27266834e+00 -4.42280766e-01
   1.87039278e-01]
 [-5.22882818e-01  8.94330191e-01 -6.75311736e-01  6.48976191e-01
  -7.54874041e-02]
 [ 1.84998420e-01 -1.37637679e-01 -5.25268834e-01 -7.48885888e-01
   1.66119843e-01]
 [-5.29534498e-01 -5.21212561e-01 -4.79529948e-01  3.18992983e-01
  -7.02847767e-01]
 [ 2.96394403e+00 -3.92382472e-01  9.78587646e-02  7.17526908e-01
  -3.84772081e-01]
 [-6.54420593e-01  7.46707617e-02 -5.35827242e-01 -7.84557961e-01

## ***Problem4(25pts)***

In [117]:
def vandermonde(N):
 vec = np.arange(N)+1
 vander = vec ** np.arange(N)
 return vander


N = 12
vander = vandermonde(N)
print("Vandermonde Matrix for N=12:\n", vander)

x = np.ones(N)
b = np.dot(vander,x)
print(b)



Vandermonde Matrix for N=12:
 [           1            2            9           64          625
         7776       117649      2097152     43046721   1000000000
  25937424601 743008370688]
769991065288.0


In [116]:
vander_inv = np.linalg.inv(vander)  
x_naive = np.dot(vander_inv, b).reshape(-1, 1)  


x_solved = np.linalg.solve(vander, b).reshape(-1, 1)  


print("Result from naive method (using inverse):")
print(x_naive)

print("\nResult from numpy.linalg.solve:")
print(x_solved)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

## ***Problem1(23pts)***

In [119]:
import numpy as np

A = np.array([
    [1, 1, -1, -1, 0],  
    [1, -1, 1, 0, -1],  
    [-1, 1, 0, 1, -1],  
    [-1, 0, 1, 0, 1],   
    [1, 0, -1, 1, 0]    
])

b = np.array([1, 2, 3, 4, 5])  

m = np.linalg.solve(A, b)

print("Masses (m1, m2, m3, m4, m5):")
print(m)



Masses (m1, m2, m3, m4, m5):
[6.  7.  6.5 5.5 3.5]
