# Assignment Numpy

#### Name : Hira Arif

#### Email. hiraarif077@gmail.com

## Install Library 

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Import 

In [2]:
import numpy as np

# Basic Array Operation

## Create a 1D array, a 2D array, and a 3D array.

### 1D Array 

In [3]:
a=np.array([1,3,5,7,9,11])
print("1d Array is \n ",a)


1d Array is 
  [ 1  3  5  7  9 11]


### 2D Array

In [4]:
b=np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

### 3D Array

In [5]:
c=np.array([[1,4,7],[2,5,8],[3,6,9]])
print("3d Array is \n ",c)



3d Array is 
  [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Slicing

In [6]:
a[1:2]

array([3])

In [7]:
a[1:3]

array([3, 5])

In [8]:
b[1:3]

array([[4, 5, 6]])

In [9]:
b[0:1]

array([[1, 2, 3]])

In [10]:
b[1:2]

array([[4, 5, 6]])

In [11]:
c[0:2]

array([[1, 4, 7],
       [2, 5, 8]])

In [12]:
c[1:3]

array([[2, 5, 8],
       [3, 6, 9]])

## Indexing

In [13]:
c[1,2]

np.int64(8)

In [14]:
c[2][2]

np.int64(9)

# Basic Arithmetic Operations On Arrays 

## Addition 

In [15]:

d=np.array([[1,2,3],[2,5,8]])
d

array([[1, 2, 3],
       [2, 5, 8]])

In [16]:
e=b+d
e

array([[ 2,  4,  6],
       [ 6, 10, 14]])

## Subtraction

In [17]:
f=b-d
f

array([[ 0,  0,  0],
       [ 2,  0, -2]])

## Multiplication 

In [18]:
g=np.dot(b,c)
g

array([[ 14,  32,  50],
       [ 32,  77, 122]])

## Division

In [19]:
u=np.divide(b,d)
u

array([[1.  , 1.  , 1.  ],
       [2.  , 1.  , 0.75]])

### 4x+3y=8x+1y

In [20]:
w=np.array([4,3])
w

array([4, 3])

In [21]:
r=np.array([8,1])
r

array([8, 1])

In [22]:
result= np.linalg.solve(w, r)


LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

# Array Creation and Manipulation

## Ones

In [64]:
ones=np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Zeros

In [70]:
zeros=np.zeros((3,6))
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Identity Matrix

In [69]:
p=np.eye(3)
p

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random

In [68]:
s=np.random.rand(5,3)
s

array([[0.79737261, 0.38036912, 0.20837574],
       [0.6020611 , 0.33431096, 0.46831754],
       [0.44028723, 0.09000484, 0.82493156],
       [0.08861305, 0.67481586, 0.1358722 ],
       [0.45829682, 0.00957742, 0.49414293]])

## Arrange

In [72]:
t=np.arange(4,9)
t

array([4, 5, 6, 7, 8])

## linspace

In [82]:
r=np.linspace(2,1)
r

array([2.        , 1.97959184, 1.95918367, 1.93877551, 1.91836735,
       1.89795918, 1.87755102, 1.85714286, 1.83673469, 1.81632653,
       1.79591837, 1.7755102 , 1.75510204, 1.73469388, 1.71428571,
       1.69387755, 1.67346939, 1.65306122, 1.63265306, 1.6122449 ,
       1.59183673, 1.57142857, 1.55102041, 1.53061224, 1.51020408,
       1.48979592, 1.46938776, 1.44897959, 1.42857143, 1.40816327,
       1.3877551 , 1.36734694, 1.34693878, 1.32653061, 1.30612245,
       1.28571429, 1.26530612, 1.24489796, 1.2244898 , 1.20408163,
       1.18367347, 1.16326531, 1.14285714, 1.12244898, 1.10204082,
       1.08163265, 1.06122449, 1.04081633, 1.02040816, 1.        ])

## Shape

In [57]:
b.shape

(2, 3)

## ReShape

In [86]:
y=b.reshape(3,2)
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
a

array([1, 3, 5, 7, 9])

In [91]:
j=np.array([2,4,5,6,7,8])
j

array([2, 4, 5, 6, 7, 8])

In [102]:
p=a.reshape(5,1)
p


array([[1],
       [3],
       [5],
       [7],
       [9]])

In [104]:
e=np.array([[1,2,3,4],[1,4,7,8],[4,6,9,8]])
e

array([[1, 2, 3, 4],
       [1, 4, 7, 8],
       [4, 6, 9, 8]])

In [106]:
i=e.reshape(4,3)
i

array([[1, 2, 3],
       [4, 1, 4],
       [7, 8, 4],
       [6, 9, 8]])

In [107]:
i=e.reshape(4,3)
i

array([[1, 2, 3],
       [4, 1, 4],
       [7, 8, 4],
       [6, 9, 8]])

## Reshape 1d to 2d

In [42]:
j=a.reshape(2,3)
j

array([[ 1,  3,  5],
       [ 7,  9, 11]])

## Reshape 1d to 3d

In [9]:
n=a.reshape(3,2)
n

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

## Reshape 2d to 1d

In [40]:
m=b.reshape(6)
m

array([1, 2, 3, 4, 5, 6])

## Concatenate arrays

In [67]:
z=np.concatenate ([b,d], axis=0)
z

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [2, 5, 8]])

In [61]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
d

array([[1, 2, 3],
       [2, 5, 8]])

In [66]:
l=np.concatenate ([b,d],axis=1)
l

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 2, 5, 8]])

In [68]:
a

array([ 1,  3,  5,  7,  9, 11])

## Split arrays

In [70]:
ar=np.array_split(a,3)
ar

[array([1, 3]), array([5, 7]), array([ 9, 11])]

In [71]:
arr=np.array_split(a,2)
arr


[array([1, 3, 5]), array([ 7,  9, 11])]

In [77]:
rr=np.array_split(a,4)
rr


[array([1, 3]), array([5, 7]), array([9]), array([11])]

In [78]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
uu=np.array_split(b,2)
uu


[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [87]:
c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [88]:
kk=np.array_split(c,1)
kk

[array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])]

In [91]:
ff=np.array_split(c,2)
ff

[array([[1, 4, 7],
        [2, 5, 8]]),
 array([[3, 6, 9]])]

In [92]:
bb=np.array_split(c,3)
bb

[array([[1, 4, 7]]), array([[2, 5, 8]]), array([[3, 6, 9]])]

# Statistical Operations


In [102]:
np.mean(a)

np.float64(6.0)

In [103]:
np.mean(b)

np.float64(3.5)

In [104]:
np.mean(c)

np.float64(5.0)

In [105]:
np.mean(d)

np.float64(3.5)

In [106]:
np.median(a)

np.float64(6.0)

In [107]:
np.median(b)

np.float64(3.5)

In [115]:
np.std(c)

np.float64(2.581988897471611)

In [114]:
np.std(d)

np.float64(2.362907813126304)

In [116]:
np.var(a)

np.float64(11.666666666666666)

In [117]:
np.var(b)

np.float64(2.9166666666666665)

In [119]:
np.min(a)

np.int64(1)

In [120]:
np.max(c)

np.int64(9)

## Linear Algebra

## 5x+7y=9     4x+6y=5


In [121]:
A=np.array([[5,7],[4,6]])
B=np.array([9,5])
solution = np.linalg.solve(A, B)
solution




array([ 9.5, -5.5])

In [122]:
A=np.array([[5,-7],[4,6]])
B=np.array([9,-5])
solution = np.linalg.solve(A, B)
solution

array([ 0.32758621, -1.05172414])

In [125]:
determinat = np.linalg.det(A)
determinat


np.float64(57.999999999999986)

In [127]:
inverse= np.linalg.inv(A)
inverse


array([[ 0.10344828,  0.12068966],
       [-0.06896552,  0.0862069 ]])

In [129]:
eignvalues= np.linalg.eigvals(A)
eignvalues


array([5.5+5.26782688j, 5.5-5.26782688j])

In [133]:
eignvector= np.linalg.eig(A)
eignvector

EigResult(eigenvalues=array([5.5+5.26782688j, 5.5-5.26782688j]), eigenvectors=array([[ 0.79772404+0.j        ,  0.79772404-0.j        ],
       [-0.05698029-0.60032459j, -0.05698029+0.60032459j]]))

In [134]:
C=np.array([[3,2],[6,-1]])
C


array([[ 3,  2],
       [ 6, -1]])

In [135]:
eignvalues= np.linalg.eigvals(C)
eignvalues

array([ 5., -3.])

## Broadcasting


In [136]:
a

array([ 1,  3,  5,  7,  9, 11])

In [137]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
tt=np.array([1,2,3])
tt

array([1, 2, 3])

In [141]:
b+tt

array([[2, 4, 6],
       [5, 7, 9]])

In [143]:
ww=np.array([1])
ww

array([1])

In [145]:
ww-a

array([  0,  -2,  -4,  -6,  -8, -10])

In [146]:
ww*a

array([ 1,  3,  5,  7,  9, 11])

In [149]:
ww/a

array([1.        , 0.33333333, 0.2       , 0.14285714, 0.11111111,
       0.09090909])

In [144]:
ww+a

array([ 2,  4,  6,  8, 10, 12])

In [151]:
ee=np.array([2,4,6,8])
ee

array([2, 4, 6, 8])

In [152]:
ee+2

array([ 4,  6,  8, 10])

In [153]:
ee-2

array([0, 2, 4, 6])

In [154]:
ee*2

array([ 4,  8, 12, 16])

In [155]:
ee/2

array([1., 2., 3., 4.])

In [163]:
yy=ee.reshape(4,1)
yy

array([[2],
       [4],
       [6],
       [8]])

In [167]:
qq=np.array([[1,2,3,4],[4,5,6,7,],[7,8,9,5],[9,8,5,2]])
qq

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 5],
       [9, 8, 5, 2]])

In [168]:
qq+yy

array([[ 3,  4,  5,  6],
       [ 8,  9, 10, 11],
       [13, 14, 15, 11],
       [17, 16, 13, 10]])

In [169]:
c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Generate Random Data from distributions

In [173]:
nn=np.random.rand(2,3)
nn

array([[0.80679493, 0.95307253, 0.34340982],
       [0.76452586, 0.41865734, 0.24194165]])

In [23]:
mm=np.random.normal(2,8)
mm


3.619426155018232

In [24]:
mm=np.random.binomial(n=2,p=0.5,size=5)
mm


array([1, 0, 2, 0, 1], dtype=int32)

In [26]:
pp=np.random.uniform(3,2)
pp

2.1945117241200687

## Create random samples from a dataset.


In [32]:
lk=np.array([1,2,3,4,7,5,8,9,7,6])
lk
n=3
sample=np.random.choice(lk,n,replace=False)
sample

array([9, 2, 3])

## Perform random shuffling of an array.

In [35]:
yt=np.array([1,5,8,9])
np.random.shuffle(yt)
yt

array([8, 5, 1, 9])

In [36]:
b

array([[1, 2, 3],
       [4, 5, 6]])

## Advanced Indexing and Slicing


In [43]:
mp = np.array([25, 30, 35, 28, 40, 22, 33])
mo=mp>30
re = mp[mo]
re



array([35, 40, 33])