## Title: assignment1

### Name: Ayesha

In [58]:
import numpy as np

**1. Sales Data Analysis**

In [59]:
sale=np.array([50,78,56,300,130,780,890,560,89,900,
               100,67,90,230,789,350,1000,670,560,3490,
               67,23,45,67,89,90,12,89,90,140])
sale

array([  50,   78,   56,  300,  130,  780,  890,  560,   89,  900,  100,
         67,   90,  230,  789,  350, 1000,  670,  560, 3490,   67,   23,
         45,   67,   89,   90,   12,   89,   90,  140])

In [3]:
sale.size

30

In [4]:
total_sale=np.sum(sale)
total_sale

11891

In [5]:
average_sale=np.mean(sale)
average_sale

396.3666666666667

In [6]:
highest_sales=np.argmax(sale)
highest_sales


19

In [7]:
sales_amount=np.max(sale)
sales_amount

3490

**2. Weather Data Processing**

In [4]:
weather=np.array([[90, 32, 29, 35],
                  [28, 31, 30, 33],
                  [15, 27, 26, 29],
                  [33, 34, 32, 36],
                  [29, 90, 28, 31],
                  [31, 33, 30, 34],
                  [27, 29, 26, 30]])
weather

array([[90, 32, 29, 35],
       [28, 31, 30, 33],
       [15, 27, 26, 29],
       [33, 34, 32, 36],
       [29, 90, 28, 31],
       [31, 33, 30, 34],
       [27, 29, 26, 30]])

In [5]:
average_temperature=np.mean(weather, axis=1)
average_temperature

array([46.5 , 30.5 , 24.25, 33.75, 44.5 , 32.  , 28.  ])

In [6]:
highest_temperature=np.max(weather)
highest_temperature

90

**3. Financial Analysis**

In [8]:
closing_prices=np.array([100, 102, 101, 103, 105, 100, 108, 107, 109, 111,
                           110, 112, 715, 118, 120, 121, 192, 119, 117, 116,
                           114, 113, 115, 198, 119, 120, 122, 124, 125, 127])
closing_prices

array([100, 102, 101, 103, 105, 100, 108, 107, 109, 111, 110, 112, 715,
       118, 120, 121, 192, 119, 117, 116, 114, 113, 115, 198, 119, 120,
       122, 124, 125, 127])

In [9]:
closing_prices[0]

100

In [10]:
closing_prices[-1]

127

In [11]:
monthly_return = ((closing_prices[-1] - closing_prices[0]) / closing_prices[0]) * 100
monthly_return

27.0

In [12]:
daily_percentage=(np.diff(closing_prices) / closing_prices[:-1]) * 100
daily_percentage

array([  2.        ,  -0.98039216,   1.98019802,   1.94174757,
        -4.76190476,   8.        ,  -0.92592593,   1.86915888,
         1.83486239,  -0.9009009 ,   1.81818182, 538.39285714,
       -83.4965035 ,   1.69491525,   0.83333333,  58.67768595,
       -38.02083333,  -1.68067227,  -0.85470085,  -1.72413793,
        -0.87719298,   1.7699115 ,  72.17391304, -39.8989899 ,
         0.84033613,   1.66666667,   1.63934426,   0.80645161,
         1.6       ])

**4. Student Grades Analysis**

In [13]:
grades=np.array([[85, 90, 78, 92],
                [88, 76, 95, 89],
                [70, 75, 85, 80],
                [90, 88, 92, 85],
                [75, 85, 80, 70]])
grades

array([[85, 90, 78, 92],
       [88, 76, 95, 89],
       [70, 75, 85, 80],
       [90, 88, 92, 85],
       [75, 85, 80, 70]])

In [14]:
average_grade=np.mean(grades, axis=1)
average_grade

array([86.25, 87.  , 77.5 , 88.75, 77.5 ])

In [15]:
class_average=np.mean(grades, axis=0)
class_average

array([81.6, 82.8, 86. , 83.2])

In [16]:
highest_grade=np.argmax(average_grade)
highest_grade

3

**5. Image Processing**

In [18]:
image=np.array([[120, 130, 140, 150, 160],
                [110, 115, 135, 145, 155],
                [100, 105, 125, 135, 145],
                [90, 95, 105, 115, 125],
                [80, 85, 95, 100, 110]])
image

array([[120, 130, 140, 150, 160],
       [110, 115, 135, 145, 155],
       [100, 105, 125, 135, 145],
       [ 90,  95, 105, 115, 125],
       [ 80,  85,  95, 100, 110]])

In [19]:
normalize=image/255
normalize

array([[0.47058824, 0.50980392, 0.54901961, 0.58823529, 0.62745098],
       [0.43137255, 0.45098039, 0.52941176, 0.56862745, 0.60784314],
       [0.39215686, 0.41176471, 0.49019608, 0.52941176, 0.56862745],
       [0.35294118, 0.37254902, 0.41176471, 0.45098039, 0.49019608],
       [0.31372549, 0.33333333, 0.37254902, 0.39215686, 0.43137255]])

In [20]:
highest_intensity=np.max(image)
highest_intensity

160

**6. Population Growth Analysis**

In [21]:
population=np.array([50000, 52000, 54000, 58000, 60000, 62000, 65000, 68000, 72000, 75000])
population

array([50000, 52000, 54000, 58000, 60000, 62000, 65000, 68000, 72000,
       75000])

In [22]:
population[:-1]

array([50000, 52000, 54000, 58000, 60000, 62000, 65000, 68000, 72000])

In [23]:
annual_growth=np.diff(population) / population[:-1] * 100
annual_growth

array([4.        , 3.84615385, 7.40740741, 3.44827586, 3.33333333,
       4.83870968, 4.61538462, 5.88235294, 4.16666667])

In [24]:
highest_growth=np.argmax(annual_growth)
highest_growth

2

In [25]:
average_growth=np.mean(annual_growth)
average_growth

4.615364927734517

**7. Traffic Data Analysis**

In [26]:
traffic=np.random.randint(50, 200, size=(8, 24))
traffic

array([[ 90, 138,  74, 171, 102,  54, 194, 172, 142, 175, 153, 197,  79,
        114,  75,  69, 138, 108, 125, 151, 140,  60,  87,  82],
       [131, 104, 107,  51, 120, 137,  58,  51, 172, 111, 182, 104,  93,
        137, 154, 194,  86, 118, 122, 150, 107, 195,  65, 112],
       [162, 150, 172,  93,  81, 104, 188, 126, 152, 160, 126,  92, 178,
         73,  91, 118, 196,  67,  62, 185, 163,  99, 154, 100],
       [112,  52, 156,  69, 146,  97, 117, 123, 114, 136,  65, 126, 122,
        103,  93, 166, 196, 174,  99, 147,  52, 161, 120, 197],
       [ 57,  70,  68,  95, 110, 113,  95, 192,  62, 147,  61,  67,  91,
        147, 109, 125, 110,  59, 164, 162, 114, 178,  83, 161],
       [ 81, 148,  68, 119,  99, 151, 193,  87, 147,  93,  94,  71,  92,
         98,  82,  75,  75, 106, 118, 157, 139, 195, 147,  66],
       [ 66,  82, 110, 127, 180, 126,  70, 194, 137, 173,  87, 194, 161,
        111, 151,  53, 186, 126, 128, 197, 117, 198,  75,  62],
       [121, 167, 124, 189, 176,  77, 178

In [27]:
total_traffic=np.sum(traffic, axis=1)
total_traffic


array([2890, 2861, 3092, 2943, 2640, 2701, 3111, 3302])

In [28]:
busiest_hour=np.max(traffic)
busiest_hour

198

**8. Product Inventory Management**

In [29]:
stock_levels=np.array([40, 55, 70, 30, 100, 25, 80])
stock_levels


array([ 40,  55,  70,  30, 100,  25,  80])

In [30]:
threshold=50

In [31]:
required_threshold=100

In [32]:
products_below_threshold=np.where(stock_levels<threshold)
products_below_threshold


(array([0, 3, 5], dtype=int64),)

In [35]:
required_level=stock_levels[stock_levels< threshold]
required_level

array([40, 30, 25])

**9. Game Score Analysis**

In [36]:
scores=np.array([[80, 90, 85, 95],
                [75, 85, 88, 90],
                [90, 92, 85, 87],
                [78, 85, 80, 88],
                [85, 87, 89, 90]])
scores

array([[80, 90, 85, 95],
       [75, 85, 88, 90],
       [90, 92, 85, 87],
       [78, 85, 80, 88],
       [85, 87, 89, 90]])

In [37]:
average_score=np.mean(scores, axis=1)
average_score

array([87.5 , 84.5 , 88.5 , 82.75, 87.75])

In [38]:
highest_average_score=np.argmax(average_score)
highest_average_score

2

In [40]:
highest_total_score=np.argmax(np.sum(scores, axis=0))
highest_total_score

3

**10. Financial Portfolio Analysis**

In [41]:
daily_returns=np.random.rand(3, 30)  
daily_returns

array([[0.39959209, 0.7069516 , 0.33563405, 0.73309765, 0.0793518 ,
        0.4438801 , 0.94053525, 0.83758036, 0.19002858, 0.40663966,
        0.43068411, 0.91203186, 0.58609994, 0.01886768, 0.63936751,
        0.32270016, 0.1658823 , 0.53904707, 0.23908519, 0.15521916,
        0.57116764, 0.62449313, 0.47543039, 0.55593938, 0.09648586,
        0.52439075, 0.00807149, 0.93722566, 0.06043116, 0.42382857],
       [0.23333229, 0.93921355, 0.64257348, 0.75575375, 0.85589525,
        0.69892081, 0.32056003, 0.81552479, 0.81656153, 0.97179809,
        0.51395662, 0.11500418, 0.03714376, 0.07542467, 0.61960114,
        0.03714384, 0.73777663, 0.10081406, 0.85594145, 0.13583269,
        0.52112055, 0.76761511, 0.24889865, 0.65011907, 0.06152422,
        0.79954669, 0.48067002, 0.64776868, 0.81422038, 0.36527693],
       [0.83047478, 0.2057106 , 0.6097981 , 0.92870148, 0.52659153,
        0.76668952, 0.58692317, 0.42412808, 0.25139653, 0.52777974,
        0.73683675, 0.76492388, 0.79781594, 0.

In [42]:
overalldaily_return=np.sum(daily_returns, axis=0)
overalldaily_return

array([1.46339915, 1.85187575, 1.58800563, 2.41755288, 1.46183857,
       1.90949043, 1.84801844, 2.07723323, 1.25798664, 1.9062175 ,
       1.68147748, 1.79195992, 1.42105964, 0.20348132, 1.84521439,
       0.95259011, 1.26415387, 1.57508983, 1.29607508, 1.2604229 ,
       1.45201366, 2.38760342, 0.92202929, 1.30485455, 1.08751197,
       1.44793345, 1.08100783, 2.26685737, 1.6005466 , 1.42010034])

In [43]:
highest_volatility=np.argmax(np.std(daily_returns, axis=1))
highest_volatility 

1

In [47]:
highest_portfolioreturn=np.argmax(overalldaily_return)
highest_portfolioreturn

3

**11. Healthcare Data Analysis**

In [48]:
patients=np.random.randint(30, 200, size=365)
patients

array([ 53, 191,  85, 167,  47,  62, 198, 155,  77, 141,  56, 124, 168,
        48, 184,  44,  57, 130, 124,  40, 125,  79, 198, 146,  50, 190,
        68,  42, 148,  47,  97, 180,  97,  97,  31,  44,  86, 117,  32,
        41, 102,  39, 199,  42,  85, 187, 122,  62,  43,  62, 134, 147,
       105, 165,  90, 126,  49, 185, 162, 108, 184, 145, 140,  73, 198,
       139,  86,  72,  90, 102,  38, 102,  88, 134, 131, 167, 178, 119,
        73,  64,  53,  53, 118, 105, 185, 188, 114,  44, 163, 157, 113,
        95,  99, 132,  31, 163, 105, 181, 196, 175,  33, 187,  32, 199,
        91, 169,  53, 141, 186,  45, 117,  37, 174, 125,  31, 160, 183,
       143, 101, 100,  71, 155, 196, 137, 121, 135, 128,  48,  38, 194,
        86,  64, 195,  55, 138,  30,  87, 177, 162, 108, 129, 192, 148,
       192, 136,  67, 134, 181, 153, 197, 198, 129,  45, 148, 186, 177,
        34, 196,  83, 130,  60,  50,  34,  40,  35,  42, 138,  47,  64,
       124, 178,  85, 104,  39,  80,  57, 183, 175, 179, 168,  5

In [49]:
total_patients=np.sum(patients)
total_patients


41485

In [50]:
average_patients=np.mean(patients)
average_patients

113.65753424657534

In [51]:
highest_patients=np.argmax(patients)
highest_patients

42

In [52]:
average_daily_count=np.max(patients)
average_daily_count

199