Name : Minhas Ahmed

In [4]:
pip install pandas

  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 1.1 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/11.5 MB 907.1 kB/s eta 0:00:12
   -- ------------------------------------- 0.8/11.5 MB 907.1 kB/s eta 0:00:12
   --- ------------------------------------ 1.0/11.5 MB 812.4 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/11.5 MB 812.4 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/11.5 MB 812.4 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/11.5 MB 658.2 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/11.5 MB 658.2 kB/s eta 0:00:16
   ----- ----------------

In [5]:
import numpy as np
import pandas as pd

In [2]:
pip install numpy

  Using cached numpy-2.1.1-cp312-cp312-win_amd64.whl.metadata (59 kB)
Using cached numpy-2.1.1-cp312-cp312-win_amd64.whl (12.6 MB)
Note: you may need to restart the kernel to use updated packages.


In [9]:
arr1 = np.array([1, 2, 3, 4, 5])  # Corrected the brackets from square brackets to parentheses
arr2 = np.array([[1, 2], [3, 4]])  # Wrapped the inner lists in additional brackets

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2]
 [3 4]]


In [22]:
arr2 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr2.shape

(2, 3, 3)

In [23]:
emp = np.empty(3)
emp

array([ 1.16919188e-311,  1.16919204e-311, -0.00000000e+000])

In [24]:
arr2.size

18

In [26]:
arr0 = np.zeros([2,3])
arr0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr_identity = np.eye(5)
arr_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Add a new dimension to the end
arr2_reshaped = arr2[..., np.newaxis]

print(arr2_reshaped.shape)

(2, 3, 1)


In [ ]:
array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]]])

In [29]:
arr_random = np.random.rand(2, 3)
print(arr_random)

[[0.9151277  0.76361427 0.49747162]
 [0.27006267 0.39232303 0.92682199]]
