Name : Minhas Ahmed

In [2]:
import numpy as np

In [3]:
# Step 1: Create a NumPy array representing daily sales for a month (30 days)

sales_data = np.array([200, 220, 250, 300, 280, 310, 400, 
                       150, 160, 170, 180, 190, 200, 
                       210, 220, 230, 240, 250, 260, 
                       270, 280, 290, 300, 310, 320, 
                       330, 340, 350, 360, 370, 380])

# Step 2: Compute total sales

total_sales = np.sum(sales_data)

# Compute average sales

average_sales = np.mean(sales_data)

# Find the day with the highest sales

highest_sales_day = np.argmax(sales_data)  
highest_sales_value = sales_data[highest_sales_day]  


print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
print("Day with Highest Sales:", highest_sales_day + 1) 
print("Highest Sales Value:", highest_sales_value)

Total Sales: 8320
Average Sales: 268.38709677419354
Day with Highest Sales: 7
Highest Sales Value: 400


In [4]:
temperature_data = np.array([[30, 32, 31, 29, 30, 31, 32],  
                              [28, 30, 29, 31, 32, 30, 29],  
                              [31, 29, 30, 32, 31, 30, 28],  
                              [29, 31, 30, 30, 29, 32, 31]]) 

# Step 2: Compute the average temperature for each day across all weeks

average_temperature = np.mean(temperature_data, axis=0)


print("Average Temperature for Each Day (across all weeks):", average_temperature)

Average Temperature for Each Day (across all weeks): [29.5  30.5  30.   30.5  30.5  30.75 30.  ]


In [5]:
closing_prices = np.array([100.0, 102.5, 101.0, 103.0, 104.5, 
                            105.0, 107.0, 108.0, 107.5, 109.0, 
                            110.0, 111.5, 112.0, 113.0, 115.0, 
                            116.0, 117.0, 118.0, 119.0, 120.0, 
                            121.0, 122.5, 123.0, 124.0, 125.0, 
                            126.0, 127.0, 128.0, 129.0, 130.0, 
                            131.0])

# Step 2: Calculate the monthly return
first_price = closing_prices[0]  
last_price = closing_prices[-1]   

# Monthly return calculation
monthly_return = ((last_price - first_price) / first_price) * 100 

print("Monthly Return (%):", monthly_return)

Monthly Return (%): 31.0


In [6]:
grades_data = np.array([[85, 90, 78, 92],  
                        [88, 76, 95, 89],  
                        [90, 88, 84, 91],  
                        [70, 80, 75, 78],  
                        [95, 92, 88, 85]]) 

# Step 2: Compute the average grade for each student

average_grades_per_student = np.mean(grades_data, axis=1)

# Compute the overall class average for each subject

overall_class_average_per_subject = np.mean(grades_data, axis=0)


print("Average Grade for Each Student:", average_grades_per_student)
print("Overall Class Average for Each Subject:", overall_class_average_per_subject)

Average Grade for Each Student: [86.25 87.   88.25 75.75 90.  ]
Overall Class Average for Each Subject: [85.6 85.2 84.  87. ]


In [7]:
image = np.array([[50, 200, 150, 100, 255],
                  [0, 100, 200, 100, 50],
                  [255, 255, 0, 0, 100],
                  [50, 100, 150, 200, 250],
                  [0, 255, 255, 255, 0]])


# Step 2: Normalize the pixel values to a range of 0 to 1
min_pixel = np.min(image)
max_pixel = np.max(image)


# Normalization formula
normalized_image = (image - min_pixel) / (max_pixel - min_pixel)


print("Original Image:\n", image)
print("\nNormalized Image:\n", normalized_image)

Original Image:
 [[ 50 200 150 100 255]
 [  0 100 200 100  50]
 [255 255   0   0 100]
 [ 50 100 150 200 250]
 [  0 255 255 255   0]]

Normalized Image:
 [[0.19607843 0.78431373 0.58823529 0.39215686 1.        ]
 [0.         0.39215686 0.78431373 0.39215686 0.19607843]
 [1.         1.         0.         0.         0.39215686]
 [0.19607843 0.39215686 0.58823529 0.78431373 0.98039216]
 [0.         1.         1.         1.         0.        ]]


In [8]:
population_data = np.array([100000, 105000, 110250, 115500, 
                             121000, 127000, 134000, 140000, 
                             147000, 155000])


# Step 2: Calculate the annual growth rate
annual_growth_rate = np.zeros(len(population_data) - 1) 

for i in range(1, len(population_data)):
    annual_growth_rate[i - 1] = ((population_data[i] - population_data[i - 1]) / population_data[i - 1]) * 100


# Step 3: Identify the year with the highest growth
highest_growth_index = np.argmax(annual_growth_rate)
highest_growth_rate = annual_growth_rate[highest_growth_index]
year_of_highest_growth = highest_growth_index + 1



print("Annual Growth Rates (%):", annual_growth_rate)
print("Year with Highest Growth:", year_of_highest_growth)
print("Highest Growth Rate (%):", highest_growth_rate)

Annual Growth Rates (%): [5.         5.         4.76190476 4.76190476 4.95867769 5.51181102
 4.47761194 5.         5.44217687]
Year with Highest Growth: 6
Highest Growth Rate (%): 5.511811023622047


In [9]:
traffic_data = np.array([[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240],  # Day 1
                          [15, 25, 35, 45, 55, 65, 75, 85, 95, 105, 115, 125, 135, 145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245],  # Day 2
                          [12, 22, 32, 42, 52, 62, 72, 82, 92, 102, 112, 122, 132, 142, 152, 162, 172, 182, 192, 202, 212, 222, 232, 242],  # Day 3
                          [20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250],  # Day 4
                          [18, 28, 38, 48, 58, 68, 78, 88, 98, 108, 118, 128, 138, 148, 158, 168, 178, 188, 198, 208, 218, 228, 238, 248],  # Day 5
                          [25, 35, 45, 55, 65, 75, 85, 95, 105, 115, 125, 135, 145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255],  # Day 6
                          [30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260]]) # Day 7


# Step 2: Calculate the total traffic for each day
total_traffic_per_day = np.sum(traffic_data, axis=1)

# Calculate the busiest hour of the week
busiest_hour_index = np.argmax(np.sum(traffic_data, axis=0))  
busiest_hour_vehicles = np.sum(traffic_data, axis=0)[busiest_hour_index]  



print("Total Traffic for Each Day:", total_traffic_per_day)
print("Busiest Hour of the Week (Hour Index):", busiest_hour_index)
print("Number of Vehicles during Busiest Hour:", busiest_hour_vehicles)

Total Traffic for Each Day: [3000 3120 3048 3240 3192 3360 3480]
Busiest Hour of the Week (Hour Index): 23
Number of Vehicles during Busiest Hour: 1740


In [10]:
stock_levels = np.array([100, 45, 30, 80, 60, 10, 75, 90, 20, 55])

# Step 2: Define the reorder threshold
reorder_threshold = 50

# Identify products that need to be reordered
products_to_reorder = np.where(stock_levels < reorder_threshold)[0]  
reorder_quantities = reorder_threshold - stock_levels[products_to_reorder]  


print("Current Stock Levels:", stock_levels)
print("Products to Reorder (Indices):", products_to_reorder)
print("Reorder Quantities:", reorder_quantities)

Current Stock Levels: [100  45  30  80  60  10  75  90  20  55]
Products to Reorder (Indices): [1 2 5 8]
Reorder Quantities: [ 5 20 40 30]


In [11]:
scores_data = np.array([[50, 60, 70, 80],  
                        [80, 70, 90, 100], 
                        [60, 80, 70, 90],  
                        [90, 100, 95, 85],  
                        [70, 60, 80, 75]])  


# Step 2: Calculate the average score for each player
average_scores = np.mean(scores_data, axis=1)


# Identify the player with the highest average score
highest_average_index = np.argmax(average_scores)
highest_average_score = average_scores[highest_average_index]


# Step 3: Calculate the total score for each round
total_scores_per_round = np.sum(scores_data, axis=0)


# Identify the round with the highest total score
highest_total_index = np.argmax(total_scores_per_round)
highest_total_score = total_scores_per_round[highest_total_index]


print("Average Scores for Each Player:", average_scores)
print("Player with Highest Average Score (Index):", highest_average_index)
print("Highest Average Score:", highest_average_score)

print("Total Scores for Each Round:", total_scores_per_round)
print("Round with Highest Total Score (Index):", highest_total_index)
print("Highest Total Score:", highest_total_score)

Average Scores for Each Player: [65.   85.   75.   92.5  71.25]
Player with Highest Average Score (Index): 3
Highest Average Score: 92.5
Total Scores for Each Round: [350 370 405 430]
Round with Highest Total Score (Index): 3
Highest Total Score: 430


In [12]:
daily_returns = np.array([[0.01, -0.02, 0.03, 0.02, 0.01, -0.01, 0.04, 0.03, -0.02, 0.01, 
                           0.02, -0.01, 0.03, 0.02, 0.01, -0.02, 0.03, 0.02, -0.01, 0.01],  
                          [0.02, 0.01, -0.01, 0.03, 0.02, -0.02, 0.01, 0.04, 0.03, -0.01, 
                           0.02, 0.01, 0.03, -0.01, 0.01, 0.02, 0.03, -0.01, 0.02, 0.01],  
                          [-0.01, 0.02, 0.01, -0.02, 0.03, 0.01, 0.02, 0.01, 0.02, 0.03, 
                           -0.01, 0.02, 0.01, 0.03, 0.02, 0.01, -0.02, 0.01, 0.03, 0.02],  
                          [0.03, 0.01, 0.02, -0.01, 0.02, 0.01, 0.03, 0.01, -0.01, 0.02, 
                           0.01, 0.02, 0.01, 0.03, -0.01, 0.02, 0.01, 0.02, 0.01, 0.03],  
                          [0.01, 0.02, -0.01, 0.01, 0.02, 0.03, 0.01, 0.02, 0.01, 0.03, 
                           0.01, -0.02, 0.01, 0.02, 0.03, 0.01, 0.02, 0.01, 0.03, 0.01]]) 


# Step 2: Calculate the overall daily return of the portfolio
# Assuming equal weights for simplicity
weights = np.ones(daily_returns.shape[0]) / daily_returns.shape[0]
overall_daily_return = np.dot(weights, daily_returns)

# Calculate the volatility (standard deviation) for each asset
volatility = np.std(daily_returns, axis=1)

# Identify the asset with the highest volatility
highest_volatility_index = np.argmax(volatility)
highest_volatility_value = volatility[highest_volatility_index]


print("Overall Daily Return of the Portfolio:", overall_daily_return)
print("Asset with Highest Volatility (Index):", highest_volatility_index)
print("Highest Volatility Value:", highest_volatility_value)

Overall Daily Return of the Portfolio: [0.012 0.008 0.008 0.006 0.02  0.004 0.022 0.022 0.006 0.016 0.01  0.004
 0.018 0.018 0.012 0.008 0.014 0.01  0.016 0.016]
Asset with Highest Volatility (Index): 0
Highest Volatility Value: 0.018439088914585774
