## Title: Assignment 2

#### Name: Ayesha

In [1]:
import numpy as np

## Question 1

In [46]:
N = 12

In [47]:

x = np.arange(1, N + 1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
vander=np.vander(x, increasing=True)
vander

array([[          1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,
                  1,           1],
       [          1,           2,           4,           8,          16,
                 32,          64,         128,         256,         512,
               1024,        2048],
       [          1,           3,           9,          27,          81,
                243,         729,        2187,        6561,       19683,
              59049,      177147],
       [          1,           4,          16,          64,         256,
               1024,        4096,       16384,       65536,      262144,
            1048576,     4194304],
       [          1,           5,          25,         125,         625,
               3125,       15625,       78125,      390625,     1953125,
            9765625,    48828125],
       [          1,           6,          36,         216,        1296,
               7776,  

In [49]:
ones=np.ones(N)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
b=np.dot(vander,ones)
b

array([1.20000000e+01, 4.09500000e+03, 2.65720000e+05, 5.59240500e+06,
       6.10351560e+07, 4.35356467e+08, 2.30688120e+09, 1.22713351e+09,
       9.43953692e+08, 3.73692871e+09, 3.10225064e+08, 3.10073456e+09])

## Question 2

In [3]:
example_vector=np.array([50.0, 1.4, 0.4, 0.23, 1.04])
example_vector

array([50.  ,  1.4 ,  0.4 ,  0.23,  1.04])

In [5]:
example_matrix = np.array([[ 3.4, 1.10, 0.8 ] ,
                        [ 4.2, 100.0, -1.4],
                        [ 1.1, 0.44, 9.4]])
example_matrix

array([[  3.4 ,   1.1 ,   0.8 ],
       [  4.2 , 100.  ,  -1.4 ],
       [  1.1 ,   0.44,   9.4 ]])

In [6]:
example_vector.shape 

(5,)

In [7]:
example_matrix.shape

(3, 3)

**A**

In [8]:
foo=np.arange(30)
foo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:

foo.shape

(30,)

**B**

In [10]:
bar=foo.reshape(5, 6)
bar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [11]:
bar.shape

(5, 6)

**C**

In [12]:
baz = bar.reshape(2, 3, 5)
baz

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [13]:

baz.shape

(2, 3, 5)

**D**

In [51]:
bar[1, 0] = -1
bar

array([[ 0,  1,  2,  3,  4,  5],
       [-1,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [15]:

foo

array([ 0,  1,  2,  3,  4,  5, -1,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
baz.sum()

428

**E**

In [22]:
sum_over_2nd_dim=np.sum(baz, axis=1)
sum_over_2nd_dim



array([[15, 11, 21, 24, 27],
       [60, 63, 66, 69, 72]])

In [23]:

sum_over_3rd_dim=np.sum(baz, axis=2)
sum_over_3rd_dim


array([[ 10,  28,  60],
       [ 85, 110, 135]])

In [24]:

sum_over_1st_3rd_dim=np.sum(baz, axis=(0, 2))
sum_over_1st_3rd_dim

array([ 95, 138, 195])

**F**

In [27]:
second_row=bar[1, :]
second_row


array([-1,  7,  8,  9, 10, 11])

In [28]:

last_column=bar[:, -1]
last_column

array([ 5, 11, 17, 23, 29])

In [29]:


top_right_submatrix=bar[:2, -2:]
top_right_submatrix

array([[ 4,  5],
       [10, 11]])

## Question 3

**A**

In [30]:
vector = np.arange(1, 11)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**B**

In [32]:
A=vector.reshape(-1, 1)+vector
A

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])


**C**

In [38]:
data=np.random.rand(20, 5)
data

array([[0.75224559, 0.48323278, 0.11575392, 0.19399484, 0.46750528],
       [0.63170016, 0.74959232, 0.21826229, 0.13009878, 0.18729742],
       [0.03586367, 0.78125756, 0.99856717, 0.28617453, 0.10677915],
       [0.91105796, 0.33357298, 0.43264895, 0.05684886, 0.92340326],
       [0.76559229, 0.76855857, 0.8081891 , 0.51741543, 0.85292   ],
       [0.38049596, 0.55799665, 0.37982397, 0.66887158, 0.28787667],
       [0.76788787, 0.05171652, 0.22219158, 0.75126502, 0.18254756],
       [0.27549824, 0.97706641, 0.31910376, 0.96934755, 0.18946155],
       [0.82522429, 0.50404059, 0.90261937, 0.21244541, 0.2996677 ],
       [0.16381837, 0.2292416 , 0.76875009, 0.61756932, 0.85871673],
       [0.30115796, 0.65648008, 0.80661919, 0.06303891, 0.30597531],
       [0.96046405, 0.32650846, 0.87561388, 0.80561014, 0.60309779],
       [0.06710109, 0.23436763, 0.45236131, 0.78584509, 0.52872547],
       [0.0116864 , 0.26494056, 0.94348747, 0.01979736, 0.35088521],
       [0.02542595, 0.73738344, 0.

**D**

In [39]:
mean = np.mean(data, axis=0)
mean

array([0.46916361, 0.50396979, 0.60145585, 0.4667478 , 0.45841304])

In [40]:

std=np.std(data, axis=0)
std

array([0.33702851, 0.2726749 , 0.28247228, 0.31020582, 0.28305006])

**E**

In [41]:
normalize=(data - mean)/std
normalize

array([[ 8.39934831e-01, -7.60502879e-02, -1.71946760e+00,
        -8.79264470e-01,  3.21223491e-02],
       [ 4.82263525e-01,  9.00788939e-01, -1.35657049e+00,
        -1.08524405e+00, -9.57836283e-01],
       [-1.28564774e+00,  1.01691712e+00,  1.40584173e+00,
        -5.82107944e-01, -1.24230282e+00],
       [ 1.31114830e+00, -6.24908310e-01, -5.97605208e-01,
        -1.32137731e+00,  1.64278436e+00],
       [ 8.79535919e-01,  9.70345213e-01,  7.31870910e-01,
         1.63335502e-01,  1.39377095e+00],
       [-2.63086497e-01,  1.98136544e-01, -7.84614645e-01,
         6.51579562e-01, -6.02495442e-01],
       [ 8.86347167e-01, -1.65858050e+00, -1.34266016e+00,
         9.17188523e-01, -9.74617268e-01],
       [-5.74626063e-01,  1.73502079e+00, -9.99574533e-01,
         1.62021377e+00, -9.50190549e-01],
       [ 1.05647051e+00,  2.59643012e-04,  1.06617016e+00,
        -8.19785984e-01, -5.60838389e-01],
       [-9.05992330e-01, -1.00753016e+00,  5.92250102e-01,
         4.86198205e-01

## Question 4

In [42]:
a=np.array([[3, 1, 2],
            [1, 2, 3],
            [2, 3, 1]])
a

array([[3, 1, 2],
       [1, 2, 3],
       [2, 3, 1]])

In [43]:

b = np.array([9, 7, 8])
b

array([9, 7, 8])

In [45]:

x = np.linalg.solve(a, b)
x

array([2., 1., 1.])