Name : Minhas Ahmed

In [1]:
import numpy as np

In [2]:
# Creating a 1D array

array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]


In [3]:
# Creating a 2D array

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)


2D Array:
[[1 2 3]
 [4 5 6]]


In [4]:
# Creating a 3D array

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(array_3d)


3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nSlicing rows (first and second row):")
print(array_2d[0:2, :])


Slicing rows (first and second row):
[[1 2 3]
 [4 5 6]]


In [7]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[7, 8, 9], [10, 11, 12]])
array_add = array_a + array_b

print("\nAddition (Array A + Array B):")
print(array_add)
array_subtract = array_a - array_b

print("\nSubtraction (Array A - Array B):")
print(array_subtract)
array_multiply = array_a * array_b

print("\nMultiplication (Array A * Array B):")
print(array_multiply)
array_divide = array_a / array_b

print("\nDivision (Array A / Array B):")
print(array_divide)


Addition (Array A + Array B):
[[ 8 10 12]
 [14 16 18]]

Subtraction (Array A - Array B):
[[-6 -6 -6]
 [-6 -6 -6]]

Multiplication (Array A * Array B):
[[ 7 16 27]
 [40 55 72]]

Division (Array A / Array B):
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [3]:
zeros_array = np.zeros((3, 4))  
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
ones_array = np.ones((2, 3)) 
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
range_array = np.arange(12).reshape(3, 4)
print(range_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = array_2d[1, 2]
print(element)

6


In [8]:
sliced_array = array_2d[:2, :2]
print(sliced_array)

[[1 2]
 [4 5]]


In [9]:
array_sum = array_2d + 5
print(array_sum)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [10]:
array_product = array_2d * 2
print(array_product)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
transposed = array_2d.T
print(transposed)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
array_arange = np.arange(10)
print("np.arange(10):", array_arange)

np.arange(10): [0 1 2 3 4 5 6 7 8 9]


In [14]:
array_linspace = np.linspace(0, 1, 5)
print("np.linspace(0, 1, 5):")

np.linspace(0, 1, 5):


In [15]:
array_zeros = np.zeros(5)
print("np.zeros(5):", array_zeros)

np.zeros(5): [0. 0. 0. 0. 0.]


In [16]:
array_ones = np.ones(5)
print("np.ones(5):", array_ones)

np.ones(5): [1. 1. 1. 1. 1.]


In [17]:
array_eye = np.eye(3).diagonal()
print("np.eye(3).diagonal():", array_eye)

np.eye(3).diagonal(): [1. 1. 1.]


In [18]:
array_random = np.random.rand(5)
print("np.random.rand(5):", array_random)

np.random.rand(5): [0.64847874 0.55038753 0.33342981 0.13127962 0.00346891]


In [20]:
array_1d = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(array_1d)
median_value = np.median(array_1d)
variance_value = np.var(array_1d)  
sample_variance_value = np.var(array_1d, ddof=1)
std_dev_value = np.std(array_1d)  
sample_std_dev_value = np.std(array_1d, ddof=1)

print("Mean:", mean_value)
print("Median:", median_value)
print("Variance (Population):", variance_value)
print("Variance (Sample):", sample_variance_value)
print("Standard Deviation (Population):", std_dev_value)
print("Standard Deviation (Sample):", sample_std_dev_value)

Mean: 3.0
Median: 3.0
Variance (Population): 2.0
Variance (Sample): 2.5
Standard Deviation (Population): 1.4142135623730951
Standard Deviation (Sample): 1.5811388300841898


In [23]:
array_1d = np.array([1, 2, 3])
scalar = 10
result1 = array_1d + scalar
print("Adding scalar to 1D array:", result1)


array_a = np.array([1, 2, 3])  
array_b = np.array([10, 20, 30])  
result2 = array_a + array_b
print("Adding two 1D arrays:", result2)


array_a = np.array([[1], [2], [3]])  
array_b = np.array([10, 20, 30])    
result3 = array_a + array_b
print("Broadcasting a 2D array with a 1D array:\n", result3)


array_2d = np.array([[1, 2, 3], [4, 5, 6]])  
array_1d = np.array([10, 20, 30])             
result4 = array_2d + array_1d
print("Adding a 1D array to a 2D array:\n", result4)

Adding scalar to 1D array: [11 12 13]
Adding two 1D arrays: [11 22 33]
Broadcasting a 2D array with a 1D array:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
Adding a 1D array to a 2D array:
 [[11 22 33]
 [14 25 36]]


In [2]:
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

result_dot = np.dot(A, B)


result_at = A @ B

print("Result using np.dot():")
print(result_dot)

print("\nResult using @ operator:")
print(result_at)

Result using np.dot():
[[19 22]
 [43 50]]

Result using @ operator:
[[19 22]
 [43 50]]


In [3]:

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])


condition = data > 50


filtered_data = data[condition]

print("Original array:")
print(data)

print("\nFiltered array (values greater than 50):")
print(filtered_data)

Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Filtered array (values greater than 50):
[ 60  70  80  90 100]


In [4]:
uniform_random = np.random.uniform(0, 1, 5)
print("Uniform Distribution (0 to 1):", uniform_random)

Uniform Distribution (0 to 1): [0.40046693 0.37140982 0.34037836 0.42219242 0.75289017]
