In [183]:
import numpy as np


In [184]:
arr2 = np.array([[1,2], [3,4]])
arr2

array([[1, 2],
       [3, 4]])

## ***Shape function***

In [185]:
arr2.shape

(2, 2)

## ***Size function*** ( number of values in array)

In [186]:
arr2.size

4

## ***dtypes***
 whether  strings etc

In [187]:
arr2.dtype

dtype('int64')

## ***NUmpy operations***
sum 
addition
multiplication

In [188]:
arr1= np.array([1,2,3,4])
arr3 = np.array([4,5,6,7])
sum = arr1 + arr3
sum

array([ 5,  7,  9, 11])

In [189]:
multiplication = np.dot(arr3, arr1)
multiplication

np.int64(60)

## ***Array indexing and slicing***

In [190]:
arr1[0]

np.int64(1)

In [191]:
arr3[0:2]

array([4, 5])

In [192]:
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [193]:
# Identity
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [194]:
# random
random_arr = np.random.rand(2,10)
random_arr

array([[0.66677006, 0.56140045, 0.49961039, 0.61065542, 0.75936545,
        0.98259253, 0.93306859, 0.40814468, 0.82782678, 0.59800778],
       [0.86069707, 0.29896808, 0.19751553, 0.12426194, 0.8108604 ,
        0.79382281, 0.95608571, 0.71888183, 0.79003877, 0.37819283]])

In [195]:
# Mean
np.mean(arr1)

np.float64(2.5)

In [196]:
# Median
np.median(arr1)

np.float64(2.5)

In [197]:
# STD
np.std(arr1)

np.float64(1.118033988749895)

In [198]:
# min max function
np.max(arr1), np.min(arr1)

(np.int64(4), np.int64(1))

## ***filtering and conditional operators***

In [199]:
arr4 = np.array([20,40,50,60,70])
filtered = arr4[arr4 > 30]
print(filtered)

condition = arr4 > 40
print(condition)
filtered1 = arr4[(arr4 > 30) & ( arr4 < 60)]
print(filtered1)
condition2 = arr4[(arr4 > 20) & (arr4 < 60)]
print(condition2)




[40 50 60 70]
[False False  True  True  True]
[40 50]
[40 50]


## ***data reshaping***

In [200]:
arr4 = np.array([20,40,50,60,70,80,90,100,110,120,130,140,150,160])

reshaped = arr4.reshape(7,2)
print(reshaped)

flat = reshaped.flatten()
print(flat)

transposed = reshaped.transpose()
print(transposed)

arr4.resize(2, 7)

[[ 20  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]
 [110 120]
 [130 140]
 [150 160]]
[ 20  40  50  60  70  80  90 100 110 120 130 140 150 160]
[[ 20  50  70  90 110 130 150]
 [ 40  60  80 100 120 140 160]]


## ***How to create a basic array***
This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [201]:
np.zeros(3)

array([0., 0., 0.])

In [202]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a


2

## ***Array attributes***
This section covers the ndim, shape, size, and dtype attributes of an array.

The number of dimensions of an array is contained in the ndim attribute.

In [204]:
a.ndim

2

The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [203]:
a.shape
len(a.shape) == a.ndim

True

The fixed, total number of elements in array is contained in the size attribute.

In [205]:
a.size

12

## ***How to create a basic array***
This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [210]:
r =np.zeros(2)
print(r)

rr = np.ones(3)
print(rr)

[0. 0.]
[1. 1. 1.]


#### Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [209]:
np.empty(2)


array([0., 0.])

In [212]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [218]:

np.linspace(0, 15, num =5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

#### Specifying your data type

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [224]:
# x = np.ones(2, dtype=np.int64)

x = np.ones(20, dtype=np.int64 )
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

## ***Adding, removing, and sorting elements***
This section covers np.sort(), np.concatenate()

Sorting an array is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

If you start with this array:

In [228]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [231]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])


np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Or, if you start with these arrays:

In [236]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate([x, y], axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## ***How do you know the shape and size of an array?***
This section covers ndarray.ndim, ndarray.size, ndarray.shape

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

For example, if you create this array:

In [237]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [238]:
array_example.ndim

3

In [239]:
array_example.size

24

In [240]:
array_example.shape

(3, 2, 4)

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

If you start with this array:

In [250]:
a = np.arange(6)
print(a)
b = a.reshape(2,3)
print(b)



[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


With np.reshape, you can specify a few optional parameters:

In [247]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


### ***How to convert a 1D array into a 2D array (how to add a new axis to an array)***
This section covers np.newaxis, np.expand_dims

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

For example, if you start with this array:

In [251]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [252]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [253]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack([a1,a2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [254]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using hsplit. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

Let’s say you have this array:

In [265]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [266]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [275]:

np.hsplit(x, (6,7))

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7],
        [19]]),
 array([[ 8,  9, 10, 11, 12],
        [20, 21, 22, 23, 24]])]

## ***You can use the view method to create a new array object that looks at the same data as the original array (a shallow copy).***

Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!

Let’s say you create this array:

In [270]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])