In [1]:
import numpy as np 

<h3>Create a 1D array, a 2D array, and a 3D array.<h3>

In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2],[3,4],[5,6]]])
print("1D Array :\n",arr1)
print("2D Array :\n",arr2)
print("3D Array :\n",arr3)

1D Array :
 [1 2 3 4 5]
2D Array :
 [[1 2 3]
 [4 5 6]]
3D Array :
 [[[1 2]
  [3 4]
  [5 6]]]


<h3>Perform slicing operations on arrays.<h3>

In [3]:
a = arr1[:3]
print("Before the Indexes:",a)
b= arr1[3:]
print("After the Indexes:",b)

Before the Indexes: [1 2 3]
After the Indexes: [4 5]


<h3>Perform basic arithmetic operations on arrays <h3>

In [4]:
x= np.array([1,2,3,4,5]) 
y= np.array([6,7,8,9,10]) 
print("Array1:",x)
print("Array2:",y)

Array1: [1 2 3 4 5]
Array2: [ 6  7  8  9 10]


<h3>Addition.<h3>

In [5]:
add_arr = np.add(x,y) 
print("Added Arrays:",add_arr)

Added Arrays: [ 7  9 11 13 15]


<h3>Subtraction<h3>

In [6]:
sub_arr = np.subtract(x,y) 
print("Added Arrays:",sub_arr)

Added Arrays: [-5 -5 -5 -5 -5]


<h3>Multiplication<h3>

In [7]:
multi_arr = np.multiply(x,y) 
print("Multiplied Arrays:",multi_arr)

Multiplied Arrays: [ 6 14 24 36 50]


<h3>Division<h3>

In [8]:
div_arr =x[x%2] 
print("Divided Arrays:",div_arr)

Divided Arrays: [2 1 2 1 2]


<h3>Array Creation and Manipulation<h3>

In [9]:
new_arr = np.array([1,2,3,4,5,6,7,8,9])
print("Array creation", new_arr)

Array creation [1 2 3 4 5 6 7 8 9]


<h3> arange, linspace, zeros, ones, eye, random.<h3>

In [10]:
new_arr[4]= 10
print("Array Manipulation", new_arr)

Array Manipulation [ 1  2  3  4 10  6  7  8  9]


<h3>Create arrays using different functions:<h3>

<h3> Arange, Linspace, Zeros, Ones, Eye, Random.<h3>

In [11]:
arr_arrange = np.arange(10)
arr_linspace = np.linspace(0,20,num=5)
arr_zeroes = np.zeros(3)
arr_ones = np.ones(2)
arr_indentity = np.eye(5)
arr_random =np.random.rand(3,2)
print("Arranged Array:\n", arr_arrange)
print("Linespace Array \n", arr_linspace)
print("Zeroes Array \n", arr_zeroes)
print("ones Array \n", arr_ones)
print("Indentity Array \n", arr_indentity)
print("Random Array \n", arr_random)

Arranged Array:
 [0 1 2 3 4 5 6 7 8 9]
Linespace Array 
 [ 0.  5. 10. 15. 20.]
Zeroes Array 
 [0. 0. 0.]
ones Array 
 [1. 1.]
Indentity Array 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Random Array 
 [[0.47727413 0.45598106]
 [0.77103772 0.04178609]
 [0.518777   0.99228815]]


<h3>Reshape an array.<h3>

In [12]:
narr= np.array([1,2,3,4,5,6])
print(narr)
reshp_arr = narr.reshape(3,2)
print("Reshaped Array \n", reshp_arr)

[1 2 3 4 5 6]
Reshaped Array 
 [[1 2]
 [3 4]
 [5 6]]


<h3>Concatenate and split arrays.<h3>

In [13]:
a=np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
c=np.array([1,2,3,4,5,6,7,8,9])
print(c)
split_array=np.array_split(c,3)
print("Splited array\n",split_array)

[1 2 3 4 5 6 7 8 9]
Splited array
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


<h3>Statistical Operation<h3>

In [4]:
d=np.array([1,2,3,4,5,6,7,8,9])
print(d)
print("Mean :",np.mean(d))
print("Median :",np.median(d))
print("Stard_Deviation :",np.std(d))
print("Varience :",np.var(d))


[1 2 3 4 5 6 7 8 9]
Mean : 5.0
Median : 5.0
Stard_Deviation : 2.581988897471611
Varience : 6.666666666666667


<h3>Minimum and Maximum values in an array a<h3>

In [8]:
d=np.array([1,2,3,4,5,6,7,8,9])
print(d)
print("Maximum :",np.max(d))
print("Minimum :",np.min(d))

[1 2 3 4 5 6 7 8 9]
Maximum : 9
Minimum : 1


<h3>Compute the sum and product of array elements.<h3>

In [10]:
d=np.array([1,2,3,4,5,6,7,8,9])
print(d)
print("Sum :",np.sum(d))
print("Product :",np.prod(d))


[1 2 3 4 5 6 7 8 9]
Sum : 45
Product : 362880


<h3>Broadcasting<h3>

In [12]:
Bd_arr = np.array([1.4,3.6])
print("Broad Casting :",Bd_arr*1.6)

Broad Casting : [2.24 5.76]


<h3>Broadcasting with examples<h3>

In [13]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2],[3,4],[5,6]]])
print("1D Array :\n",arr1*1.5)
print("2D Array :\n",arr2*1.5)
print("3D Array :\n",arr3*1.5)

1D Array :
 [1.5 3.  4.5 6.  7.5]
2D Array :
 [[1.5 3.  4.5]
 [6.  7.5 9. ]]
3D Array :
 [[[1.5 3. ]
  [4.5 6. ]
  [7.5 9. ]]]


<h3>Linear Algebra<h3>

In [22]:
mx_arr= np.array([[1,2],[4,5]])
print(mx_arr)
print("Matriz Multiplication:\n",np.multiply(mx_arr,mx_arr))
print("Determinat :",np.linalg.det(mx_arr))
print("Inverse :",np.linalg.inv(mx_arr))

[[1 2]
 [4 5]]
Matriz Multiplication:
 [[ 1  4]
 [16 25]]
Determinat : -2.9999999999999996
Inverse : [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


<h3>Solve a system of linear equations.

In [30]:
s_x = np.array([1,2])
s_y = np.array([[1,2],[9,8]])
sys= np.linalg.solve(s_y,s_x)
print("x:",sys[0])
print("y:",sys[1])

x: -0.39999999999999997
y: 0.7


<h3>Advanced Indexing and Slicing
<h4>Fancy Indexing<br>Silicing

In [43]:
n_arr = np.arange(10)
print(n_arr)
silice = n_arr[0:8:2]
index = n_arr[n_arr<5]
print("Advanced Silicing" , silice)
print("Fancy Indexing" , index)


[0 1 2 3 4 5 6 7 8 9]
Advanced Silicing [0 2 4 6]
Fancy Indexing [0 1 2 3 4]


<h3>Boolean indexing to filter an array

In [48]:
print(n_arr)
boolean_arr = n_arr> 5
print(boolean_arr)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]


<h3>Random Sampling<br>Generate random numbers

In [45]:
r_sample = np.random.uniform(low=0,high=10,size=5)
print("Random sapling :", r_sample)

Random sapling : [2.73728982 9.35900236 7.32787192 7.72184297 9.9048615 ]


<h3>Create random samples from a dataset

In [47]:
print(n_arr)
rand_sam = np.random.choice(n_arr,size=3,replace=False)
print("Random Samples :", rand_sam)


[0 1 2 3 4 5 6 7 8 9]
Random Samples : [5 9 2]


<h3>Random shuffling of an array.

In [ ]:
print(n_arr)
np.random.shuffle(n_arr)
print(n_arr)
