# Numpy Assignment # 01
## Name: Hammad Raza
### Email: hammad.razikhan@gmail.com
#### Topic: AI Numpy

In [1]:
import numpy as np

### Q.1: Sales Data Analysis: 
### You have a NumPy array representing the daily sales of a product over a month. Each element in the array represents the sales for a particular day. Compute the total sales, average sales, and the day with the highest sales


In [9]:
# Daily Sales dataframe for a month (30 days)

Monthly_Sales = np.random.randint(500,3000,30)

print("Monthly Sales:", Monthly_Sales)

Monthly Sales: [2126 1236 2481 2824  852 1392 1568 1982 1241 2490 1091 1929 1035 1964
 1415 1827 1492 2867  869 2843  740 2293 2494  677  616  515 2936 1676
 1657  729]


In [174]:
# Compute the total sales
total_sales = np.sum(Monthly_Sales)
print("Compute the total sales:", total_sales)

# Average sales 
average_sales = np.mean(Monthly_Sales)
print("Average Sales:", average_sales)

# day with the highest sales & Amount

day_with_highest_sales = np.argmax(Monthly_Sales) + 1
print("Day with Highest Sales:", day_with_highest_sales)

highest_sales_amount = np.max(Monthly_Sales)
print("Highest Sales Amount:",highest_sales_amount)


Compute the total sales: 49857
Average Sales: 1661.9
Day with Highest Sales: 27
Highest Sales Amount: 2936


### Q.2: Weather Data Processing: 
### Given a 2D NumPy array where each row represents daily temperature readings for a week (7 days), find the average temperature for each day across all weeks

In [173]:
# daily temperature readings 

daily_temp_reading = np.random.randint(22,45, size=(4,7))
print("Daily Temp Readings for Every Week:", daily_temp_reading)

# average temperature for each day across all weeks
average_temp  =  np.mean(daily_temp_reading, axis=0)
print("Average Temperature for 07 Day:", average_temp)

# Identify the highest temperature recorded and the corresponding day

highest_temperature = np.max(daily_temp_reading)
print("Highest Temperature:", highest_temperature) 

highest_temperature_day = np.unravel_index(np.argmax(daily_temp_reading), daily_temp_reading.shape)
print("Highest Temperature on Day:", highest_temperature_day[-1] + 1)

Daily Temp Readings for Every Week: [[34 24 34 30 34 44 44]
 [26 37 31 36 42 37 23]
 [44 35 31 37 41 33 41]
 [35 26 37 36 29 28 23]]
Average Temperature for 07 Day: [34.75 30.5  33.25 34.75 36.5  35.5  32.75]
Highest Temperature: 44
Highest Temperature on Day: 6


### Q.3: Financial Analysis: 
### You have a NumPy array representing the daily closing prices of a stock for a month. Calculate the monthly return, which is the percentage change from the first to the last day of the month

In [188]:
# NumPy array representing the daily closing prices of a stock for a month.

stock_closing = np.random.randint(1000,8000,30)
print("Daily Closing Prices of a Stock For Month:", stock_closing)

# Monthly return: percentage change from the first to the last day

monthly_return = (stock_closing[-1] - stock_closing[0]) / stock_closing[0] * 100
print("Monthly Return (%):", monthly_return)

# daily percentage of changes throughout the month

daily_percentage_changes = np.diff(stock_closing) / stock_closing[:-1] * 100
print("Daily Percentage of Changes (%):", daily_percentage_changes)


Daily Closing Prices of a Stock For Month: [1263 4871 4594 7641 6582 7708 4685 3536 5819 5287 6155 1548 6486 7328
 3362 3034 2593 3428 1741 7823 6534 5235 1198 2560 2449 2350 4863 4814
 4950 2103]
Monthly Return (%): 66.5083135391924
Daily Percentage of Changes (%): [285.66904196  -5.68671731  66.32564214 -13.85944248  17.10726223
 -39.21899325 -24.52508004  64.56447964  -9.14246434  16.41762814
 -74.84971568 318.99224806  12.98180697 -54.12117904  -9.75609756
 -14.53526697  32.20208253 -49.21236873 349.33946008 -16.47705484
 -19.88062443 -77.11556829 113.68948247  -4.3359375   -4.04246631
 106.93617021  -1.00760847   2.82509348 -57.51515152]


### Q.4: Student Grades Analysis: 
### You have a 2D NumPy array where each row represents a student and each column represents their grades in different subjects. Calculate the average grade for each student and the overall class average for each subject

In [206]:
# 2D array where each row represents a student and each column represents grades in different subjects.
student_grades = np.random.randint(40,100, size=(5,10))
print("Student Grades of Different Subjects:", student_grades)

# Average grade for each student.
average_grade = np.mean(student_grades, axis=1)
print("Average Grade for Each Student:", average_grade)

# Overall class average for each subject.
class_average_each_subject  = np.mean(student_grades, axis=0)
print("Class Average Each Subject:", class_average_each_subject)

# Identify the student with the highest average grade
highest_avg_student = np.argmax(average_grade) 
highest_avg_grade = np.max(average_grade) 
print("Student With Highest Average Grade:", highest_avg_student + 1, "With an Average Of:", highest_avg_grade)

Student Grades of Different Subjects: [[68 66 45 90 48 96 88 89 59 94]
 [65 53 79 83 46 94 41 58 60 88]
 [63 61 46 88 92 90 56 79 57 66]
 [88 93 67 94 61 70 89 67 87 56]
 [70 56 43 95 68 57 46 54 86 71]]
Average Grade for Each Student: [74.3 66.7 69.8 77.2 64.6]
Class Average Each Subject: [70.8 65.8 56.  90.  63.  81.4 64.  69.4 69.8 75. ]
Student With Highest Average Grade: 4 With an Average Of: 77.2


### Q.5: Image Processing: 
### You have a grayscale image represented as a 2D NumPy array of pixel intensities. Normalize the pixel values to a range of 0 to 1.

In [11]:
# Grayscale image (2D Numpy array) with pixel intensities ranging from 0 to 255.
grayscale_image = np.random.randint(0,255, size=(4,5))
print("Grayscale Image:", grayscale_image)

# Normalize the pixel values to a range of 0 to 1.
normalize_image = grayscale_image / 255.0
print("normalize_image:", normalize_image)

# Identify the pixel with the highest intensity and its location.
highest_intensity = np.max(grayscale_image)
print("Highest Intensity:", highest_intensity)

# Highest intensity Location. 
highest_intensity_location = np.unravel_index(np.argmax(grayscale_image), grayscale_image.shape)
print("Highest Intensity Location:", highest_intensity_location)

Grayscale Image: [[182 153 113  18 106]
 [169 199  33 248 229]
 [201 114 223 188 238]
 [ 50 127  86  91 164]]
normalize_image: [[0.71372549 0.6        0.44313725 0.07058824 0.41568627]
 [0.6627451  0.78039216 0.12941176 0.97254902 0.89803922]
 [0.78823529 0.44705882 0.8745098  0.7372549  0.93333333]
 [0.19607843 0.49803922 0.3372549  0.35686275 0.64313725]]
Highest Intensity: 248
Highest Intensity Location: (np.int64(1), np.int64(3))


### Q.6: Population Growth Analysis
### You have a NumPy array representing the population of a city over 10 years.

In [42]:
# Population of a city over 10 years.

city_population = np.array([15,10,12,18,20,27,32,38,40,43])
print("Population of a City Over 10 Years:", city_population)

# Annual growth rate for each year
annual_growth_rate = np.diff(city_population) / city_population[:-1] * 100
print("Annual Growth Rate for Each Year (%):", annual_growth_rate)

#Identify the year with the highest growth.
highest_growth_year_index = np.argmax(annual_growth_rate)
highest_growth_rate = annual_growth_rate[highest_growth_year_index]
print("Year with Highest Growth is:", highest_growth_year_index + 1, "with a growth rate of:", highest_growth_rate)

# Compute the average annual growth rate over the 10-year period.
average_growth_rate = np.mean(annual_growth_rate)
print("Average Annual Growth Rate Over 10-Years:", average_growth_rate)

Population of a City Over 10 Years: [15 10 12 18 20 27 32 38 40 43]
Annual Growth Rate for Each Year (%): [-33.33333333  20.          50.          11.11111111  35.
  18.51851852  18.75         5.26315789   7.5       ]
Year with Highest Growth is: 3 with a growth rate of: 50.0
Average Annual Growth Rate Over 10-Years: 14.756606021225902


### Q.7: Traffic Data Analysis\n",
### Given a 2D NumPy array where each row represents the number of vehicles passing through a checkpoint during different hours of the day over a week.Calculate the total traffic for each day and the busiest hour of the week.

In [50]:
# 2D array representing traffic data for 1 Week 24*7 a Day.
traffic_data = np.random.randint(20,80, (7,24))
print("Daily vehicles passing through a checkpoint:", traffic_data)

# Total traffic for each day.
total_traffic_per_day = np.sum(traffic_data, axis=1)
print("Total traffic For Each Day:", total_traffic_per_day)

# Busiest hour of the week.
busiest_hour_index = np.argmax(np.sum(traffic_data, axis=0))
busiest_hour_traffic = np.sum(traffic_data, axis=0)[busiest_hour_index]
print("Busiest Hour of the Week:", busiest_hour_index, "with traffic of:", busiest_hour_traffic)

Daily vehicles passing through a checkpoint: [[54 38 32 38 43 26 24 32 45 28 55 47 22 58 55 33 42 78 29 61 77 61 60 63]
 [24 46 32 76 51 79 46 59 65 31 65 43 50 76 70 47 73 25 26 30 59 68 45 27]
 [71 63 56 35 52 24 74 79 40 50 45 59 77 48 32 40 56 30 28 74 22 65 47 74]
 [33 20 29 68 34 56 35 79 20 58 61 35 22 27 29 20 50 55 38 50 43 33 78 42]
 [41 39 42 21 77 58 43 45 71 24 50 66 42 44 25 72 68 48 65 33 48 43 52 49]
 [38 75 29 66 36 74 46 60 53 57 62 52 70 27 52 53 67 75 35 29 52 59 77 36]
 [62 53 76 34 79 64 61 70 51 68 46 62 45 25 49 23 36 25 36 23 62 29 37 40]]
Total traffic For Each Day: [1101 1213 1241 1015 1166 1280 1156]
Busiest Hour of the Week: 7 with traffic of: 424


### Q.8: Product Inventory Management.
### You have a NumPy array representing the stock levels of different products in a warehouse. 
### Identify the products with stock levels below a threshold (e.g., 50 units).
### Increse the Stock Levels of These Products to the Required threshold (e.g, 100 units)