### Title: Numpy Assignment

#### Submitted By: Ayesha

**Importing numpy library**

In [4]:
import numpy as np

#### Array Creation & Operations

In [3]:
a=np.array([1,3,4,6,7,9])
a

array([1, 3, 4, 6, 7, 9])

**Access individual element of array**

In [5]:
a[0]

1

**Assigning value to array**

In [7]:
a[5]=13
a

array([ 1,  3,  4,  6,  7, 13])

**Array slicing**

In [8]:
a[:4]

array([1, 3, 4, 6])

In [9]:
a[4:]

array([ 7, 13])

**Create 1D array, 2D array,and 3D array**

In [11]:
a

array([ 1,  3,  4,  6,  7, 13])

In [12]:
b=np.array([[1,3,4],[4,6,7]])
b

array([[1, 3, 4],
       [4, 6, 7]])

In [15]:
c=np.array([[2,4,7,8],[5,78,4,5],[8,7,0,4]])
c

array([[ 2,  4,  7,  8],
       [ 5, 78,  4,  5],
       [ 8,  7,  0,  4]])

In [20]:
c[2,3]

4

In [65]:
c[c>5]

array([ 7,  8, 78,  8,  7])

In [27]:
d=np.array([[2,4,7,8],[5,78,4,5],[8,7,0,4],[4,6,8,9]])
d

array([[ 2,  4,  7,  8],
       [ 5, 78,  4,  5],
       [ 8,  7,  0,  4],
       [ 4,  6,  8,  9]])

**Array attributes**

**ndim: number of dimensions of an array**

In [30]:
b.ndim

2

**shape: number of elements along each dimension**

In [32]:
c.shape

(3, 4)

In [33]:
len(a.shape) == a.ndim

True

**size: total number of elements in array**

In [35]:
d.size

16

**dtype: data types**

In [36]:
b.dtype

dtype('int32')

#### Create array using functions

**np.zeros(): an array filled with 0’s**

In [40]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [41]:
zeros=np.zeros([6,7])
zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**np.ones(): an array filled with 1’s**

In [42]:
np.ones(3)

array([1., 1., 1.])

In [112]:
ones=np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**np.eye(): Identity matrix**

In [114]:
identity=np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**np.empty(): creates an empty array**

In [44]:
np.empty(6)

array([6.23042070e-307, 9.99988867e-321, 0.00000000e+000, 1.15293773e-311,
       0.00000000e+000, 1.94693963e-308])

In [45]:
empty=np.empty(3)
empty

array([1., 1., 1.])

**np.random.rand(): Random Array**

In [115]:
arr=np.random.rand(3,4)
arr

array([[0.13713582, 0.11352124, 0.09750968, 0.64898688],
       [0.2379075 , 0.29364811, 0.45728545, 0.27688539],
       [0.23388089, 0.99425544, 0.14663125, 0.61949917]])

**np.arange(): create an array with a range of elements**

In [46]:
np.arange(4)

array([0, 1, 2, 3])

**an array that contains a range of evenly spaced intervals, specify the first number, last number, and the step size.**



In [48]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

**np.linspace(): create an array with values that are spaced linearly in a specified interval**

In [50]:
np.linspace(0,20,num=5)

array([ 0.,  5., 10., 15., 20.])

####  Array Manipulation

#### Adding, removing, and sorting elements

**np.sort(): sorting an array**

In [51]:
arr=np.array([1,3,4,65,7,8,0,9])
np.sort(arr)

array([ 0,  1,  3,  4,  7,  8,  9, 65])

#### Concatenate

**np.concatenate(): concatenate the array**

In [108]:
a=np.array([1,3,4,5])
b=np.array([7,8,9,5])
np.concatenate((a,b))

array([1, 3, 4, 5, 7, 8, 9, 5])

In [109]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenating along axis=0 (rows) axis=1 (column)
result = np.concatenate((arr1, arr2), axis=0)
result

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### Split array

In [110]:
arr = np.array([1, 2, 3, 4, 5, 6])
split= np.split(arr, 3)
split

[array([1, 2]), array([3, 4]), array([5, 6])]

In [111]:
split = np.split(arr, [2, 4])
split

[array([1, 2]), array([3, 4]), array([5, 6])]

**Reshape an array**

In [63]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [64]:
b=a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [118]:
arr = np.arange(6)
reshape= arr.reshape(2, 3)  # Reshapes 1D array into 2x3 matrix
reshape


array([[0, 1, 2],
       [3, 4, 5]])

#### Transposing

In [120]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transpose = arr.T
transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Indexing

In [128]:
data=np.array([1,4,6,78,8])
data[3]

78

In [75]:
data[3]

78

####  Slicing

In [68]:
data[0:4]

array([ 1,  4,  6, 78])

In [69]:
data[2:]

array([ 6, 78,  8])

#### Logical Operators

In [73]:
e=b[(b>0) &(b<15)]
e

array([1, 2, 3, 4, 5])

In [74]:
e=d[(d>7)| (d==0)]
e

array([ 8, 78,  8,  0,  8,  9])

In [76]:
e=np.nonzero(b<6)
e

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 0, 1, 0, 1], dtype=int64))

In [77]:
a[b]

array([[0, 1],
       [2, 3],
       [4, 5]])

#### Create an array from existing data

In [78]:
arr1=a[3:4]
arr1

array([3])

In [79]:
a1 = np.array([[1, 1], [2, 2]])

a2 = np.array([[3, 3],[4, 4]])

In [80]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [81]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [89]:
np.hsplit(a1,2)

[array([[1],
        [2]]),
 array([[1],
        [2]])]

In [91]:
a1=a2.copy()
a1

array([[3, 3],
       [4, 4]])

#### Array operations (Arithmetic operations on arrays (addition, subtraction, multiplication, division))

In [92]:
a1+a2

array([[6, 6],
       [8, 8]])

In [93]:
a1-a2

array([[0, 0],
       [0, 0]])

In [94]:
a1*a2

array([[ 9,  9],
       [16, 16]])

In [95]:
a1/a2

array([[1., 1.],
       [1., 1.]])

In [96]:
a1.sum()

14

#### Element-wise operation: compute the sum and product of array elements.

In [123]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr1 + arr2


array([5, 7, 9])

In [124]:
arr1 * arr2

array([ 4, 10, 18])

#### Matrix Multiplication

In [125]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.dot(arr1, arr2)
result

array([[19, 22],
       [43, 50]])

#### Statistical Operations: mean, median, variance, and standard deviation of an array.

In [104]:
np.mean(a1)

3.5

In [101]:
np.median(a1)

3.5

In [103]:
np.unique(a2)

array([3, 4])

In [105]:
np.std(a1)

0.5

In [126]:
np.sum(a1)

14

In [127]:
np.var(a1)

0.25

#### Find the minimum and maximum values in an array along with their indices.

In [106]:
np.min(a1)

3

In [107]:
np.max(a1)

4

#### Broadcasting

In [133]:
x=np.ones((4,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [131]:
y=np.array([3,2,5])
y

array([3, 2, 5])

In [134]:
row_add=(x+y)
row_add

array([[4., 3., 6.],
       [4., 3., 6.],
       [4., 3., 6.],
       [4., 3., 6.]])

**1D and 2D Array**

In [145]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

arr + arr2


array([[2, 4, 6],
       [5, 7, 9]])

In [147]:
row_add*4

array([[16., 12., 24.],
       [16., 12., 24.],
       [16., 12., 24.],
       [16., 12., 24.]])

**1D Array and Scalar**

In [148]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 20  # Scalar value 20 is broadcast to every element
result

array([21, 22, 23, 24, 25])

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([1, 2])

# This will throw an error because the second dimension does not match
result = arr_2d + arr_1d 

### Linear Algebra: Matrix Operations

**Matrix Multiplication:**

In [152]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B) 
result

array([[19, 22],
       [43, 50]])

**Determinant of a Matrix:**

In [5]:
arr = np.array([[1, 2], [3, 4]])
det = np.linalg.det(arr)
det


-2.0000000000000004

**Inverse of a Matrix:**

In [6]:
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Eigenvalues and Eigenvectors:**

In [9]:

eigenvalues=np.linalg.eigvals(arr)
eigenvalues

array([-0.37228132,  5.37228132])

In [10]:
eigenvectors= np.linalg.eig(arr)


**System of Linear Equations:**

**3x+y=9, x+2y=8**

In [159]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)  # Solves Ax = b
x

array([2., 3.])

### Advanced Indexing and Slicing:

**Boolean indexing:**

In [160]:
arr = np.array([10, 20, 30, 40, 50])
result = arr[arr > 25]
result

array([30, 40, 50])

**Fancy indexing:**

In [161]:
indices = [0, 2, 4]  # Indices of elements to select
result = arr[indices]
result

array([10, 30, 50])

**Advanced slicing:**

In [162]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slice every second element from index 2 to 8
sliced = arr[2:9:2]
sliced


array([2, 4, 6, 8])

### Random Sampling:

**Uniform distribution:**

In [12]:
np.random.uniform(3, 3) #min,max

3.0

**Normal distribution:**

In [14]:
np.random.normal(3, 3) #mean,std

2.8714363358473634

**Random sample:**

In [166]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Randomly sample 5 elements from the dataset
sample = np.random.choice(data, size=5, replace=False)
sample


array([7, 9, 2, 3, 1])

**Shuffle:**

In [169]:
np.random.shuffle(data)
data

array([ 2,  5,  6,  9,  4, 10,  1,  7,  8,  3])