## ASSIGNMENT 01

##### Name : Hira Arif

##### Email hiraarif077@gmail.com

##### Install Library

In [4]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


##### Import Numpy as np

In [5]:
import numpy as np

### Sales Data Analysis

In [6]:
salesdata=np.array([120, 134, 110, 145, 156, 123, 90, 167, 150, 132, 145, 170, 160, 115, 200, 125, 135, 180, 140, 145,150, 178, 190, 165, 155, 160, 175, 140, 155, 180])
salesdata

array([120, 134, 110, 145, 156, 123,  90, 167, 150, 132, 145, 170, 160,
       115, 200, 125, 135, 180, 140, 145, 150, 178, 190, 165, 155, 160,
       175, 140, 155, 180])

In [7]:
np.sum(salesdata)

np.int64(4490)

In [8]:
np.mean(salesdata)

np.float64(149.66666666666666)

In [9]:
np.max(salesdata)

np.int64(200)

### 2.	Weather Data Processing

In [10]:
weatherdata = np.array([[20,30,40,50,60,70,80],[22,33,44,55,66,77,88]])
print("weatherdata in 2D\n",weatherdata)

weatherdata in 2D
 [[20 30 40 50 60 70 80]
 [22 33 44 55 66 77 88]]


In [11]:
np.mean(weatherdata,axis=0)

array([21. , 31.5, 42. , 52.5, 63. , 73.5, 84. ])

### 3.	Financial Analysis


In [12]:
closing_prices=np.array([100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,2100,2200,2300,2400,2500,2600,2700,2800,2900,3000])
closing_prices

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1100,
       1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200,
       2300, 2400, 2500, 2600, 2700, 2800, 2900, 3000])

In [22]:
first_price=closing_prices[0]
first_price

np.int64(100)

In [21]:
last_price=closing_prices[-1]
last_price

np.int64(3000)

In [26]:
monthlyreturn = ((last_price - first_price) / first_price) * 100
monthlyreturn
print(f"Monthly Return of Stock: {monthlyreturn}%")

Monthly Return of Stock: 2900.0%


### 4.	Student Grades Analysis


In [84]:
student_grades_analysis = np.array([[76,65,50,39],[80,75,99,88],[90,81,70,69],[97,90,86,80]])
student_grades_analysis

array([[76, 65, 50, 39],
       [80, 75, 99, 88],
       [90, 81, 70, 69],
       [97, 90, 86, 80]])

In [85]:
student_names = ["SARA", "SANA", "SAIMA", "SABA"]
student_names

['SARA', 'SANA', 'SAIMA', 'SABA']

In [86]:
student_grades_average=np.mean(student_grades_analysis,axis=1)
student_grades_average

array([57.5 , 85.5 , 77.5 , 88.25])

In [87]:
class_average = np.mean(student_grades_analysis,axis=0)
print("Class Average\n", class_average )

Class Average
 [85.75 77.75 76.25 69.  ]


In [88]:
print("Average grades od every student") 
for name,avg in zip(student_names,student_grades_average):
    print(f"{name}:{avg}")


Average grades od every student
SARA:57.5
SANA:85.5
SAIMA:77.5
SABA:88.25


In [95]:
highest_average_grade=np.max(student_grades_average)
highest_average_grade

np.float64(88.25)

### 5.	Image Processing

In [103]:
image_pixel=np.array([[25,36,14],[26,20,19]])
image_pixel

array([[25, 36, 14],
       [26, 20, 19]])

In [112]:
normalized=image_pixel/255
print("Normalized the Pixel values is\n",normalized)

Normalized the Pixel values is:
 [[0.09803922 0.14117647 0.05490196]
 [0.10196078 0.07843137 0.0745098 ]]


In [113]:
intensity=np.max(image_pixel)
print("Higest Intensity is \n",intensity)

Higest Intensity is 
 36


In [129]:
location=np.unravel_index(np.argmax(image_pixel),image_pixel.shape)
print(f"Higest Location is \n: {location}")


Higest Location is 
: (np.int64(0), np.int64(1))


### 6.	Population Growth Analysis

In [140]:
population_of_city=np.array([10500,12000,12500,142000,52300,62010,45260,48920,86321,78943])
population_of_city

array([ 10500,  12000,  12500, 142000,  52300,  62010,  45260,  48920,
        86321,  78943])

In [141]:
Difference= np.diff(population_of_city)

In [143]:
last_population= population_of_city[-1]

In [152]:
annual_growth_rate = Difference / last_population * 100
print(f"Annual Growth Rate is \n: {annual_growth_rate}")


Annual Growth Rate is 
: [   1.90010514    0.63336838  164.04241035 -113.62628732   12.30001393
  -21.21784072    4.63625654   47.37722154   -9.34598381]


In [162]:
maximum_growth_index = np.argmax(annual_growth_rate)
maximum_growth_index

np.int64(2)

In [163]:
maximum_growth_rate = annual_growth_rate[maximum_growth_index]
maximum_growth_rate

np.float64(164.04241034670585)

In [164]:
year_of_maximum_growth = maximum_growth_index + 1  
print(f"Annual Maximum Growth is \n: {year_of_maximum_growth}")


Annual Maximum Growth is 
: 3


In [156]:
higest_average=np.mean(annual_growth_rate)
higest_average


np.float64(9.633251558438085)

### 7.	Traffic Data Analysis

In [166]:
traffic_data=np.array([[200,150,140,160],[200,120,160,140],[250,300,360,120],[120,450,360,480],[250,140,690,320],[260,140,360,120],[260,320,233,420]])
traffic_data

array([[200, 150, 140, 160],
       [200, 120, 160, 140],
       [250, 300, 360, 120],
       [120, 450, 360, 480],
       [250, 140, 690, 320],
       [260, 140, 360, 120],
       [260, 320, 233, 420]])

In [173]:
total_traffic_per_day=np.sum(traffic_data,axis=1)
total_traffic_per_day

array([ 650,  620, 1030, 1410, 1400,  880, 1233])

In [175]:
Total_traffic_per_hour=np.sum(traffic_data,axis=0)
Total_traffic_per_hour

array([1540, 1620, 2303, 1760])

### 8.	Product Inventory Management

In [177]:
stock_level = np.array([50,60,40,50,30,80])
stock_level

array([50, 60, 40, 50, 30, 80])

In [180]:
current_threshold = 50
required_threshold = 100
products_below_threshold = stock_levels < current_threshold
products_below_threshold

array([False, False,  True, False,  True, False])

In [182]:
stock_levels[products_below_threshold] = required_threshold
stock_levels

array([ 50,  60, 100,  50, 100,  80])

### 9.	Game Score Analysis

In [183]:
players_scores=np.array([[20,30,50,40],[30,10,25,45],[25,30,16,12],[12,18,30,45]])
players_scores

array([[20, 30, 50, 40],
       [30, 10, 25, 45],
       [25, 30, 16, 12],
       [12, 18, 30, 45]])

In [186]:
average_score_each_player=np.mean(players_scores,axis=0)
average_score_each_player

array([21.75, 22.  , 30.25, 35.5 ])

In [190]:
highest_average_player = np.argmax(average_score_each_player)
highest_average_player


np.int64(3)

In [191]:
highest_average_score = average_score_each_player[highest_average_player]
highest_average_score

np.float64(35.5)

In [196]:
total_scores_per_round = np.sum(players_scores, axis=0)
highest_round_index = np.argmax(total_scores_per_round)
highest_round_index


np.int64(3)

In [197]:
highest_round_score = total_scores_per_round[highest_round_index]
highest_round_score

np.int64(142)

### 10.	Financial Portfolio Analysis

In [198]:
returns = np.array([[0.01, 0.02, -0.01, 0.03, 0.02], [-0.02, 0.01, 0.03, 0.01, 0.04],  [0.03, -0.01, 0.02, -0.02, 0.01]])
returns

array([[ 0.01,  0.02, -0.01,  0.03,  0.02],
       [-0.02,  0.01,  0.03,  0.01,  0.04],
       [ 0.03, -0.01,  0.02, -0.02,  0.01]])

In [199]:
overall_daily_return = np.sum(returns, axis=0)
overall_daily_return

array([0.02, 0.02, 0.04, 0.02, 0.07])

In [200]:
volatility = np.std(returns, axis=1)
asset_with_highest_volatility = np.argmax(volatility)
asset_with_highest_volatility

np.int64(1)

In [201]:
day_with_highest_return = np.argmax(overall_daily_return)
day_with_highest_return

np.int64(4)

### 11. Healthcare Data Analysis

In [203]:
patients_per_day = np.random.randint(10, 80, size=360) 
patients_per_day

array([23, 68, 21, 61, 26, 32, 46, 60, 11, 22, 51, 63, 46, 60, 77, 22, 16,
       29, 19, 78, 46, 38, 63, 17, 33, 45, 41, 45, 60, 12, 73, 65, 59, 19,
       51, 57, 40, 66, 38, 10, 43, 43, 16, 47, 25, 59, 56, 35, 57, 75, 43,
       48, 32, 57, 49, 14, 76, 77, 43, 47, 51, 69, 12, 40, 59, 23, 74, 17,
       58, 34, 64, 13, 24, 45, 67, 72, 72, 63, 63, 73, 27, 74, 77, 70, 35,
       27, 40, 30, 10, 49, 60, 65, 69, 42, 52, 52, 10, 77, 39, 20, 16, 23,
       17, 66, 16, 67, 37, 34, 27, 66, 24, 23, 28, 41, 10, 30, 33, 34, 24,
       47, 43, 64, 59, 18, 61, 17, 25, 42, 36, 14, 13, 40, 68, 43, 15, 14,
       59, 32, 34, 76, 26, 50, 38, 30, 59, 33, 32, 14, 58, 37, 10, 44, 58,
       70, 60, 76, 59, 52, 28, 46, 15, 76, 26, 18, 67, 39, 72, 45, 55, 76,
       10, 33, 73, 27, 74, 34, 13, 61, 27, 20, 49, 57, 71, 78, 28, 49, 70,
       78, 67, 53, 42, 47, 46, 55, 18, 24, 79, 64, 71, 76, 43, 36, 75, 64,
       74, 46, 76, 52, 22, 66, 28, 39, 28, 29, 46, 16, 17, 17, 38, 54, 45,
       76, 26, 23, 75, 29

In [205]:
total_patients = np.sum(patients_per_day)
total_patients

np.int64(16327)

In [211]:
average_patients = np.mean(patients_per_day)
average_patients

np.float64(45.352777777777774)

In [212]:
max_patients = np.max(patients_per_day)
day_with_max_patients = np.argmax(patients_per_day) + 1
day_with_max_patients

np.int64(197)

In [213]:
days_above_average = np.sum(patients_per_day > average_patients)
days_above_average

np.int64(178)

In [214]:
days_below_50_patients = np.sum(patients_per_day < 50)
percentage_below_50_patients = (days_below_50_patients / len(patients_per_day)) * 100
percentage_below_50_patients

np.float64(57.77777777777777)