#### Importing Numpy

In [3]:
import numpy as np

#### Creating 1-D array in numpy

In [4]:
Array1=np.array([1,2,3,4,5,6,7])
print("1D Array is: \n",Array1)

1D Array is: 
 [1 2 3 4 5 6 7]


#### Creating 2D Array

In [5]:
Array2=np.array([[1,2,3,],[4,5,6]])
print("2D Array is: \n",Array2)

2D Array is: 
 [[1 2 3]
 [4 5 6]]


#### Creating 3D Array

In [6]:
Array3=np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D Array is: \n",Array3)

3D Array is: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### *Slicing Arrays*

#### Slicing 1D array

##### Slicing array from 2nd index 1 to index 5

In [7]:
print(Array1[1:4])

[2 3 4]


#### Slicing array from 2nd index upto end of array

In [8]:
print(Array1[2:,])

[3 4 5 6 7]


#### Slicing array from start of array upto index 4

In [9]:
print(Array1[:4])

[1 2 3 4]


### *Slicing 2D Arrays*

In [10]:
print(Array2[1,0:2])

[4 5]


### *Basic Arithmetic Operations*

#### Addition Of Two Arrays

In [11]:
arr1=np.array([10,11,12])
arr2=np.array([5,6,7])
newarr=arr1+arr2
print("Result of addition is :\n",newarr)

Result of addition is :
 [15 17 19]


#### Subtraction of two arrays

In [12]:
Subarr=arr1-arr2
print("Result of Subtraction is :\n",Subarr)

Result of Subtraction is :
 [5 5 5]


#### Multiplication of two arrays

In [13]:
arr3=np.array([1,2,3])
arr4=np.array([[2,3],[4,5],[2,8]])
Mularr=np.dot(arr3,arr4)
print("Result of Multiplication is :\n",Mularr)

Result of Multiplication is :
 [16 37]


#### Division of two arrays

In [14]:
Darr=np.array([[40,20,55],[20,30,40]])
divarr=np.divide(Array2,Darr)
print("Result of Division is :\n",divarr)

Result of Division is :
 [[0.025      0.1        0.05454545]
 [0.2        0.16666667 0.15      ]]


  ### *Creating arrays using different functions*

#### arange

In [15]:
ar1=np.arange(0,10)
print(ar1)

[0 1 2 3 4 5 6 7 8 9]


#### linespace

In [16]:
ar2=np.linspace(0,2)
print(ar2)

[0.         0.04081633 0.08163265 0.12244898 0.16326531 0.20408163
 0.24489796 0.28571429 0.32653061 0.36734694 0.40816327 0.44897959
 0.48979592 0.53061224 0.57142857 0.6122449  0.65306122 0.69387755
 0.73469388 0.7755102  0.81632653 0.85714286 0.89795918 0.93877551
 0.97959184 1.02040816 1.06122449 1.10204082 1.14285714 1.18367347
 1.2244898  1.26530612 1.30612245 1.34693878 1.3877551  1.42857143
 1.46938776 1.51020408 1.55102041 1.59183673 1.63265306 1.67346939
 1.71428571 1.75510204 1.79591837 1.83673469 1.87755102 1.91836735
 1.95918367 2.        ]


### zeros

In [17]:
zar=np.zeros((2,4))
print(zar)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Ones

In [18]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### np.eye

In [19]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### random

In [20]:
np.random.rand(5,3)

array([[0.64530879, 0.32730745, 0.07475441],
       [0.04375913, 0.13050524, 0.72071646],
       [0.87863763, 0.3135435 , 0.52903444],
       [0.00252868, 0.80594179, 0.28790645],
       [0.86604328, 0.26515799, 0.28896576]])

#### Reshape an array

In [21]:
n=Array1.reshape(7,1)
n

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

  ### *Concatination of two arrays*

#### Concatinating 1D arrays

In [22]:
a=np.array([50,60,70])
b=np.array([44,55,66])
c=np.concatenate((a,b))
c

array([50, 60, 70, 44, 55, 66])

#### Concatinating 2D arrays

In [23]:
e=np.concatenate((Array2,Darr))
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [40, 20, 55],
       [20, 30, 40]])

### *Splitting Arrays*

#### Splitting 1D array

In [24]:
np.array_split(Array1,2)

[array([1, 2, 3, 4]), array([5, 6, 7])]

#### Splitting 2D array

In [25]:
np.array_split(Array2,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]

### *Statistical Operations*

#### Mean 

##### Mean of 1D array

In [26]:
MeanArray=np.mean(Array1)
print(MeanArray)

4.0


##### Mean of 2D Array

In [27]:
np.mean(Array2)

np.float64(3.5)

### Median

In [28]:
print(np.median(Array3))

6.5


#### Standard Deviation

In [29]:
np.std(Array1)

np.float64(2.0)

#### Variance

In [30]:
np.var(Array2)

np.float64(2.9166666666666665)

#### Minimum Value with index

In [31]:
MinVal=np.min(Array1)
print("Minimum value in array is : ",MinVal)
min_element_index=np.argmin(Array1)
print("Index of min element is:",min_element_index)

Minimum value in array is :  1
Index of min element is: 0


#### Maximum Value with index

In [32]:
MaxVal=np.max(Array1)
print("Maximum value in array is : ",MaxVal)
max_element_index=np.argmax(Array1)
print("Index of max element is:",max_element_index)

Maximum value in array is :  7
Index of max element is: 6


#### Sum And Product of array elements

In [33]:
print("Sum of array elemets is :",Array1.sum())
print("Product of array elemets is :",Array1.prod())


Sum of array elemets is : 28
Product of array elemets is : 5040


### *BroadCasting*

#### Broadcasting in 1D array

In [34]:
b=3
c= Array1+b
print(c)

[ 4  5  6  7  8  9 10]


#### Broadcasting in 2D arrays

In [35]:
d=Array2+b
print(d)

[[4 5 6]
 [7 8 9]]


### *Linear Algebra*

#### Matrix Multiplication

In [36]:
np.matmul(arr3,arr4)

array([16, 37])

#### Determinant

In [37]:
M = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print(np.linalg.det(M))

-306.0


#### Inverse

In [38]:
print(np.linalg.inv(M))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


#### Eigen Values

In [39]:
E=np.array([[1,2,3],[5,7,12],[3,2,1]])
print(np.linalg.eig(E))

EigResult(eigenvalues=array([11.52079729, -0.52079729, -2.        ]), eigenvectors=array([[-0.24890876, -0.37504507, -0.11035678],
       [-0.93599618,  0.84775137, -0.77249749],
       [-0.24890876, -0.37504507,  0.62535511]]))


#### Solving linear Equations
##### For Example : x+2y=1 , 3x+5y=2

In [40]:
A=np.array([[1,2],[3,5]])
B=np.array([1,2])
Sol=np.linalg.solve(A,B)
print("Solution is :",Sol)

Solution is : [-1.  1.]


### Advance Indexing and Slicing

#### Use Boolean indexing to filter an array.

In [41]:
boolean_mask = Array1 % 2 != 0

result = Array1[boolean_mask]

print(result)


[1 3 5 7]


#### Fance Indexing

In [42]:
findexing=Array1[[2,5,6]]
print(findexing)

[3 6 7]


#### Random Sampling

In [43]:
np.random.sample()

0.9178336152767674

In [47]:
from numpy import random
x= random.choice([3,5,7,9])
print(x)

7


In [48]:
y= random.choice([3, 5, 7, 9], size=(3, 5))

print(y)


[[7 5 9 5 9]
 [7 3 7 7 7]
 [9 9 9 5 7]]


In [50]:
z=np.random.shuffle(ar1)
print(z)

None
