<center> <h2>Numpy Paractise<h2><center>

In [8]:
import pandas as pd
import numpy as np


In [9]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2],[3,4]])
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2]
 [3 4]]


In [10]:
arr2 = np.array([[1,2],[3,4]])
arr2.shape

(2, 2)

In [15]:
arr3 = np.array([[[1,2,4],[3,4,5],[9,8,7]],[[1,2,3],[4,5,6],[1,9,8]]])
arr3

array([[[1, 2, 4],
        [3, 4, 5],
        [9, 8, 7]],

       [[1, 2, 3],
        [4, 5, 6],
        [1, 9, 8]]])

In [16]:
arr3.shape

(2, 3, 3)

In [17]:
emp =np.empty(3)
emp

array([0.00000000e+000, 6.98572498e-312, 0.00000000e+000])

In [18]:
arr3.size

18

In [21]:
arr0 = np.zeros([2,3])
arr0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr_indentity=np.eye(5)
arr_indentity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
arr_rdm = np.random.rand(3,4)
print(arr_rdm)

[[0.46196703 0.23099111 0.50735416 0.15417871]
 [0.46296102 0.2039688  0.18453593 0.06056223]
 [0.74125079 0.99674583 0.58903867 0.84399244]]


In [33]:
arr_sum = np.sum(arr_rdm)
arr_sum

np.float64(5.437546730351069)

In [36]:
arr_mean = np.mean(arr3)
arr_mean

np.float64(4.555555555555555)

In [37]:
month1 = [1200,1300,1400]
month2 = [1300,1400,1500]
print(month1)
print(month2)

[1200, 1300, 1400]
[1300, 1400, 1500]


In [5]:
arr_new =[9,8,7,6,5]
print(arr_new[3]+arr_new[4])

11


In [6]:
arr_new
arr_new[3:5]

[6, 5]

In [9]:
narr = np.array([1,2,3,4,5])
print(narr)


[1 2 3 4 5]


In [10]:
narr.ndim

1

In [12]:
new=np.arange(10)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
new[4]=11
new

array([ 0,  1,  2,  3, 11, 11,  6,  7,  8,  9])

In [23]:
b=new
b

array([ 0,  1,  2,  3, 11, 11,  6,  7,  8,  9])

In [25]:
b[4]=4
b

array([ 0,  1,  2,  3,  4, 11,  6,  7,  8,  9])

In [26]:
new

array([ 0,  1,  2,  3,  4, 11,  6,  7,  8,  9])

In [34]:
np.linspace(0,10,num= 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [36]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [38]:
np.concatenate((a,b))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
x=([[1,2,3,4,5],[6,7,8,9,10]])
y=([11,12,13,14,15])
np.concatenate((x,y), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [49]:
z=np.array([1,2,3,4,5,6])
z

array([1, 2, 3, 4, 5, 6])

In [52]:
newz=z.reshape(3,2)
newz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
z

array([1, 2, 3, 4, 5, 6])

In [55]:
newshape = z[:,np.newaxis]
newshape

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [56]:
z


array([1, 2, 3, 4, 5, 6])

In [57]:
print(a[a<5])

[1 2 3 4]


In [18]:
new[:3]

array([0, 1, 2])