# Assignment 1 

##### Name : Hira Arif

Email: hiraarif077@gmail.com

##### install library

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


### import numpy as np

In [2]:
import numpy as np

### Q1

In [67]:
A=np.array([[2,4,5,5,6],[3,5,8,7,5],[2,1,6,4,2],[6,4,3,1,2],[5,2,6,3,2]])
A

array([[2, 4, 5, 5, 6],
       [3, 5, 8, 7, 5],
       [2, 1, 6, 4, 2],
       [6, 4, 3, 1, 2],
       [5, 2, 6, 3, 2]])

In [64]:
b=np.array([2,5,8,1,2])
b

array([2, 5, 8, 1, 2])

In [70]:
solution = np.linalg.solve(A, b)
print("Masses\n",solution)

Masses
 [-21.55882353  16.58823529  32.26470588 -42.08823529   4.64705882]


### Q2

(A)	Use arange to create a variable named foo that stores an array of numbers from 0 to 29, inclusive.  Print
foo and its shape.


In [8]:
foo=np.arange(30)
print("foo =", foo)

foo = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [11]:
shape= np.shape(foo)
print("Shapeof foo",shape)

Shapeof foo (30,)


(B)	Use the reshape function to change foo to a validly-shaped two-dimensional matrix and store it in a new variable called bar. Print bar and its shape.


In [16]:
bar=foo.reshape(5,6)
print("bar\n",bar)

bar
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [18]:
g=np.shape(bar)
print("Shape of Bar\n",g)

Shape of Bar
 (5, 6)


(C)	Create a third variable, baz that reshapes it into a valid three-dimensional shape. Print baz and its shape.

In [24]:
baz=foo.reshape(5,2,3)
print("baz\n",bar)

baz
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [25]:
v=np.shape(baz)
print("Shape of Baz\n",v)

Shape of Baz
 (5, 2, 3)


(D)	There are several different ways to index into NumPy arrays. Use two-dimensional array indexing to set the first value in the second row of bar to -1. Now look at foo and baz. Did they change? Explain what’s going on. (Hint: does reshape return a view or a copy?)

In [45]:
bar[1,0] = -1
bar

array([[ 0, -1,  2,  3,  4,  5],
       [-1,  7,  8,  9, 10, 11],
       [-1, -1, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

(E)	Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular) and do the following:
(i)	Sum baz over its second dimension and print the result.
(ii)	Sum baz over its third dimension and print the result.
(iii)	Sum baz over both its first and third dimensions and print the result.


In [51]:
sum_baz_second_dim = np.sum(baz, axis=1)
sum_baz_second_dim

array([[ 3,  3,  7],
       [ 8, 17, 19],
       [14, 15, 31],
       [39, 41, 43],
       [51, 53, 55]])

In [50]:
sum_baz_third_dim = np.sum(baz, axis=2)
sum_baz_third_dim

array([[ 1, 12],
       [14, 30],
       [12, 48],
       [57, 66],
       [75, 84]])

In [52]:
sum_baz_first_and_third_dim = np.sum(baz, axis=(0, 2))
sum_baz_first_and_third_dim

array([159, 240])

(F)	Along with shaping and indexing, we also do a lot of slicing which is where you index with ranges to get subvectors and sometimes submatrices. Write code to do the following:
(i)	Slice out the second row of bar and print it.
(ii)	Slice out the last column of bar using the -1 notation and print it.
(iii)	Slice out the top right 2 × 2 submatrix of bar and print it.
 


In [56]:
second_row = bar[1, :]
second_row


array([-1,  7,  8,  9, 10, 11])

In [54]:
last_column = bar[:, -1]
last_column

array([ 5, 11, 17, 23, 29])

In [55]:
top_right_submatrix = bar[0:2, 4:6]
top_right_submatrix

array([[ 4,  5],
       [10, 11]])

### Q3

A

In [71]:
vec = np.arange(10) + 1
vec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

B

In [75]:
H = vec.reshape(10, 1) + vec.reshape(1, 10)
H

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

C

In [77]:
data = np.random.normal(size=(50, 5))
data = np.exp(data)
data

array([[ 4.61936374,  3.54207828,  0.50247931,  2.16394808,  6.68060321],
       [ 0.68620881,  0.2996183 ,  0.68078545,  0.54302631,  3.74329161],
       [ 1.12625112,  2.7080047 ,  0.70033441,  0.39481396,  0.37951654],
       [ 0.68178127,  2.36470777,  1.29123421,  0.54853489,  5.41149007],
       [ 0.44895341,  0.93449809,  0.55506471,  0.82178866,  1.40621806],
       [ 2.47548338,  8.04814069,  1.47045622,  0.71450235,  0.29755157],
       [ 0.13160651,  0.91707746,  0.98842587,  1.20445153,  2.78949056],
       [ 3.34567136,  0.7388375 ,  0.59490732,  0.64108224,  0.39363042],
       [ 0.77689856,  0.72037319,  0.3202596 ,  8.01753916,  1.16362876],
       [ 1.66307012,  3.36924927,  2.80546147,  0.64322692,  0.74491452],
       [ 2.3111156 ,  0.65388562,  1.61194141,  1.27025224,  0.78083294],
       [ 0.18320862,  1.51177427,  2.65496682,  0.29803177,  3.89342228],
       [ 1.70970237,  1.08791434,  3.65104779,  1.83092814,  0.89360947],
       [ 1.73192184,  1.06988132,  1.6

D

In [78]:
mean = np.mean(data, axis=0)
mean

array([1.75134687, 1.82738718, 1.25905199, 1.3506018 , 1.71385616])

In [79]:
std = np.std(data, axis=0)
std

array([2.87136275, 1.74152528, 0.94157656, 1.36810912, 1.65799724])

D

In [83]:
normalized = (data - mean) / std
normalized


array([[ 0.99883474,  0.98459157, -0.8035169 ,  0.59450396,  2.99563047],
       [-0.37095211, -0.87725909, -0.61414713, -0.59028587,  1.22402825],
       [-0.21770003,  0.50565877, -0.59338518, -0.69861959, -0.80479001],
       [-0.37249407,  0.30853448,  0.03417908, -0.58625946,  2.23018098],
       [-0.45358026, -0.51270521, -0.74766866, -0.38652848, -0.18554802],
       [ 0.25219263,  3.57201448,  0.22452155, -0.46494789, -0.85422615],
       [-0.56410161, -0.5227083 , -0.28741807, -0.10682647,  0.64875524],
       [ 0.55525011, -0.62505534, -0.70535387, -0.51861328, -0.79627741],
       [-0.33936789, -0.63565772, -0.99704308,  4.87310353, -0.33186268],
       [-0.03074385,  0.88535154,  1.64236193, -0.51704566, -0.58440486],
       [ 0.1949488 , -0.6738355 ,  0.37478569, -0.05873037, -0.56274112],
       [-0.54613032, -0.18122786,  1.4825293 , -0.76936117,  1.31457766],
       [-0.01450339, -0.42461217,  2.54041563,  0.35108774, -0.49472139],
       [-0.00676509, -0.4349669 ,  0.3

In [81]:
normalized_mean = np.mean(normalized, axis=0)
normalized_mean


array([ 3.77128884e-17, -3.97459843e-16, -1.35447209e-16, -4.44089210e-17,
       -2.70894418e-16])

In [82]:
normalized_std = np.std(normalized, axis=0)
normalized_std

array([1., 1., 1., 1., 1.])