# ***Numpy Assignment***
Dated: 26/09/2024

Submitted By : Muhammad Hassan Zahoor

Submitted To :Sir Tauseef Ahmed (Gold Medalist)


#### **Creating dimentionals**

In [1]:
import numpy as np
arry1 = np.array([1,2,3,4,5])
arry1

array([1, 2, 3, 4, 5])

In [2]:
arry2 = np.array([[6,7,8,9,10],[11,12,13,14,15]])
arry2

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [3]:
arry3 = np.array([[[16,17,18,19,20], [21,22,23,24,25], [ 26,27,28,29,30]]])
arry3

array([[[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

#### **Performing slicing opeations on array**

In [12]:
arry1[2:5]


array([3, 4, 5])

## ***Perform basic arithmetic operations***
 on arrays (addition, subtraction, multiplication, division).

In [8]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
multiplication =[a * b]
print(multiplication)

[array([ 6, 14, 24, 36, 50])]


In [10]:
addition = [a + b]
print(addition)

[array([ 7,  9, 11, 13, 15])]


In [11]:
subtraction = [a - b]
print(subtraction)

[array([-5, -5, -5, -5, -5])]


In [14]:
division =np.divide(a,b)
print(division)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## ***Array Creation and Manipulation***

In [16]:

arry3 = np.array([[[16,17,18,19,20], [21,22,23,24,25], [ 26,27,28,29,30]]])


3

In [17]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.empty(10)

array([1.39903116e-311, 1.39903116e-311, 1.39903116e-311, 1.26974871e-321,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

## ***Array Manipulation:***
Reshape an array.

In [39]:
a1 = np.array([1,2,3,4])
reshaped_arr = a1.reshape(2,2)
reshaped_arr

array([[1, 2],
       [3, 4]])

In [41]:
flattened_arr = reshaped_arr.flatten()
flattened_arr


array([1, 2, 3, 4])

In [45]:
transposed = np.concatenate((arry1,a))
transposed

array([1, 2, 3, 4, 5, 1, 2, 3, 4])

split arrays.


In [54]:
np.split(arry1, 2.5)

[array([1, 2, 3]), array([4, 5])]

In [61]:
np.array_split(arry1, 3)

[array([1, 2]), array([3, 4]), array([5])]

In [73]:
np.vsplit(arry3,)

[array([[[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]])]

In [76]:
split_arr_h = np.hsplit(arry3, 3)
print(split_arr_h)


[array([[[16, 17, 18, 19, 20]]]), array([[[21, 22, 23, 24, 25]]]), array([[[26, 27, 28, 29, 30]]])]


## ***Compute mean, median, variance, and standard deviation of an array.***

In [81]:
mean = np.median(arry3)
mean

np.float64(23.0)

In [82]:
median =  np.median(arry3)
median

np.float64(23.0)

In [83]:
modlue = np.var(arry3)
modlue

np.float64(18.666666666666668)

In [85]:
sd = np.std(arry3)
sd

np.float64(4.320493798938574)

## ***2. Minimum and Maximum Values with Indices***

In [86]:
minimum = np.min(arry3)
maximum = np.max(arry3)
print(minimum)
print(maximum)

16
30


## ***Sum and Product of Array Elements:***


In [87]:
summary = np.sum(arry3)
product = np.prod(arry3)
print(summary)
print(product)


345
-70979879077707776


## ***Broadcasting:***
Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations. It automatically expands the dimensions of smaller arrays to match larger ones.

In [90]:


result= arry3 + 10
print(result)
re = arry1 + arry2
print(re)

[[[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]
[[ 7  9 11 13 15]
 [12 14 16 18 20]]


## ***Scalar and Array***

In [98]:
scalar = 3
answer = scalar + arry1
answer

array([4, 5, 6, 7, 8])

## ***Linear Algebra in NumPy***
NumPy provides a set of functions for linear algebra, which are part of numpy.linalg.

1. Matrix Multiplication (np.dot() or @)
Matrix multiplication between two arrays can be done using np.dot() or @.

In [103]:
arr2t = arry2.T
multiplication = np.dot(arry1,arr2t)
multiplication

array([130, 205])

Determinant (np.linalg.det())
The determinant of a matrix.

In [110]:

square_matrix = arry3[0, :3, :3]
det_A = np.linalg.det(square_matrix)
det_A


np.float64(-3.552713678800502e-14)

In [113]:
inv_A = np.linalg.inv(square_matrix)
inv_A

array([[ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14]])

In [115]:
eigenvalues= np.linalg.eig(square_matrix)
eigenvectors = np.linalg.eig(square_matrix)
print(eigenvalues)
print(eigenvectors)


EigResult(eigenvalues=array([ 6.64514574e+01, -4.51457367e-01, -2.25669843e-15]), eigenvectors=array([[-0.43962137, -0.72789434,  0.40824829],
       [-0.56778723, -0.02126746, -0.81649658],
       [-0.6959531 ,  0.68535942,  0.40824829]]))
EigResult(eigenvalues=array([ 6.64514574e+01, -4.51457367e-01, -2.25669843e-15]), eigenvectors=array([[-0.43962137, -0.72789434,  0.40824829],
       [-0.56778723, -0.02126746, -0.81649658],
       [-0.6959531 ,  0.68535942,  0.40824829]]))


# ***Solve a linear equation***

In [116]:
import numpy as np


A = np.array([[2, 3], [1, 4]])

b = np.array([8, 9])

solution = np.linalg.solve(A, b)

print(solution)


[1. 2.]


***Use Boolean indexing to filter an array.***

In [120]:
values = arry3 > 20
print(values)
arry3[values]



[[[False False False False False]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [128]:
arry3

row = [2,0,1]
column =[0,3,4]

display = arry3[row, column]
print(display)




[26 19 25]


advance slicing


In [129]:

sliced_arr = arry3[0:2, -3:]
print(sliced_arr)


[[18 19 20]
 [23 24 25]]
