## HASNAIN HAFEEZ 
#ASSIGNMENT 1

Sales Data Analysis
You have a NumPy array representing the daily sales of a product over a month. Each element in 
the array represents the sales for a particular day.

In [3]:
import numpy as np

# Daily sales data for a month (30 days)
sales_data = np.array([200, 180, 220, 250, 230, 240, 260, 280, 300, 
                       290, 260, 250, 240, 230, 220, 210, 400, 
                       450, 420, 430, 440, 410, 405, 390, 380, 
                       370, 360, 350, 340, 330, 320, 310])

# Compute total sales for the month
total_sales = np.sum(sales_data)

# Calculate average daily sales
average_sales = np.mean(sales_data)

# Identify the day with the highest sales and its corresponding sales amount
highest_sales_day = np.argmax(sales_data) + 1  
highest_sales_amount = np.max(sales_data)

print("Total Sales for the Month:", total_sales)
print("Average Daily Sales:", average_sales)
print("Day with Highest Sales:", highest_sales_day, "Sales Amount:", highest_sales_amount)

Total Sales for the Month: 9965
Average Daily Sales: 311.40625
Day with Highest Sales: 18 Sales Amount: 450


### Weather Data Processing
Given a 2D NumPy array where each row represents daily temperature readings for a week (7 
days), and each column represents readings from different weeks.

In [4]:
# Daily temperature readings for 4 weeks (4 rows, 7 days each)
temperature_data = np.array([[1, 2, 3, 4, 5, 6, 2],   
                              [2, 3, 1, 5, 4, 6, 3],   
                              [4, 2, 5, 3, 1, 6, 4],   
                              [3, 5, 2, 6, 4, 1, 2]])  

# Find the average temperature for each day across all weeks
average_temperature = np.mean(temperature_data, axis=0)

# Identify the highest temperature recorded and the corresponding day
highest_temperature = np.max(temperature_data)
highest_temperature_day = np.unravel_index(np.argmax(temperature_data), temperature_data.shape)


print("Average Temperature for Each Day:", average_temperature)
print("Highest Temperature Recorded:", highest_temperature, "on Day:", highest_temperature_day[1] + 1)  # +1 for 1-indexing

Average Temperature for Each Day: [2.5  3.   2.75 4.5  3.5  4.75 2.75]
Highest Temperature Recorded: 6 on Day: 6


### Financial Analysis
You have a NumPy array representing the daily closing prices of a stock for a month.

In [6]:


# Daily closing prices of a stock for a month (30 days) with values between 7 and 19
closing_prices = np.array([10, 12, 11, 14, 13, 15, 18, 
                           16, 17, 19, 14, 15, 13, 
                           12, 16, 19, 18, 15, 14, 
                           13, 12, 11, 10, 19, 17, 
                           16, 15, 14, 13, 12, 11, 
                           10, 19])

# Compute monthly return: percentage change from the first to the last day
monthly_return = (closing_prices[-1] - closing_prices[0]) / closing_prices[0] * 100

# Calculate daily percentage changes throughout the month
daily_changes = np.diff(closing_prices) / closing_prices[:-1] * 100


print("Monthly Return (%):", monthly_return)
print("Daily Percentage Changes (%):", daily_changes)


Monthly Return (%): 90.0
Daily Percentage Changes (%): [ 20.          -8.33333333  27.27272727  -7.14285714  15.38461538
  20.         -11.11111111   6.25        11.76470588 -26.31578947
   7.14285714 -13.33333333  -7.69230769  33.33333333  18.75
  -5.26315789 -16.66666667  -6.66666667  -7.14285714  -7.69230769
  -8.33333333  -9.09090909  90.         -10.52631579  -5.88235294
  -6.25        -6.66666667  -7.14285714  -7.69230769  -8.33333333
  -9.09090909  90.        ]


### Student Grades Analysis
You have a 2D NumPy array where each row represents a student, and each column represents 
their grades in different subjects.


In [7]:


# 2D array where each row represents a student and each column represents grades in different subjects
grades = np.array([[75, 82, 88, 92],   
                   [68, 74, 80, 85],   
                   [90, 95, 92, 88],   
                   [78, 85, 80, 82],   
                   [84, 90, 92, 86]])  

# Calculate the average grade for each student
average_grades = np.mean(grades, axis=1)

# Compute the overall class average for each subject
class_average_per_subject = np.mean(grades, axis=0)

# Identify the student with the highest average grade
highest_avg_student = np.argmax(average_grades)  
highest_avg_grade = np.max(average_grades)  


print("Average Grade for Each Student:", average_grades)
print("Overall Class Average for Each Subject:", class_average_per_subject)
print("Student with Highest Average Grade:", highest_avg_student + 1, "with an average of:", highest_avg_grade)


Average Grade for Each Student: [84.25 76.75 91.25 81.25 88.  ]
Overall Class Average for Each Subject: [79.  85.2 86.4 86.6]
Student with Highest Average Grade: 3 with an average of: 91.25


### Image Processing
You have a grayscale image represented as a 2D NumPy array of pixel intensities (values range 
from 0 to 255).

In [8]:


# Example grayscale image (2D NumPy array) with pixel intensities ranging from 0 to 255
image = np.array([[0, 50, 100, 150],
                  [200, 255, 75, 125],
                  [30, 60, 90, 180],
                  [255, 200, 0, 255]])

# Normalize the pixel values to a range of 0 to 1
normalized_image = image / 255.0

# Identify the pixel with the highest intensity and its location
highest_intensity = np.max(image)
highest_intensity_location = np.unravel_index(np.argmax(image), image.shape)

# Output results
print("Normalized Image:\n", normalized_image)
print("Highest Intensity Pixel:", highest_intensity, "at location:", highest_intensity_location)


Normalized Image:
 [[0.         0.19607843 0.39215686 0.58823529]
 [0.78431373 1.         0.29411765 0.49019608]
 [0.11764706 0.23529412 0.35294118 0.70588235]
 [1.         0.78431373 0.         1.        ]]
Highest Intensity Pixel: 255 at location: (np.int64(1), np.int64(1))


### Population Growth Analysis
You have a NumPy array representing the population of a city over 10 years.

In [9]:


# Population of a city over 10 years (values less than 50)
population = np.array([10, 15, 20, 25, 30, 
                       35, 40, 45, 48, 49])

# Calculate the annual growth rate for each year
annual_growth_rate = np.diff(population) / population[:-1] * 100

# Identify the year with the highest growth
highest_growth_year_index = np.argmax(annual_growth_rate)  # Index of the highest growth
highest_growth_rate = annual_growth_rate[highest_growth_year_index]  # Highest growth rate

# Compute the average annual growth rate over the 10-year period
average_growth_rate = np.mean(annual_growth_rate)

# Output results
print("Annual Growth Rate for Each Year (%):", annual_growth_rate)
print("Year with Highest Growth:", highest_growth_year_index + 1, "with a growth rate of:", highest_growth_rate)
print("Average Annual Growth Rate (%):", average_growth_rate)


Annual Growth Rate for Each Year (%): [50.         33.33333333 25.         20.         16.66666667 14.28571429
 12.5         6.66666667  2.08333333]
Year with Highest Growth: 1 with a growth rate of: 50.0
Average Annual Growth Rate (%): 20.05952380952381


### Traffic Data Analysis
Given a 2D NumPy array where each row represents the number of vehicles passing through a 
checkpoint during different hours of the day over a week

In [10]:


# Smaller 2D array representing traffic data (vehicles passing through a checkpoint)
traffic_data = np.array([[10, 15, 20],  # Day 1
                          [12, 18, 22],  # Day 2
                          [5,  10, 15],  # Day 3
                          [20, 25, 30],  # Day 4
                          [15, 20, 25]]) # Day 5

# Calculate total traffic for each day
total_traffic_per_day = np.sum(traffic_data, axis=1)

# Find the busiest hour of the week
busiest_hour_index = np.argmax(np.sum(traffic_data, axis=0))
busiest_hour_traffic = np.sum(traffic_data, axis=0)[busiest_hour_index]

# Output results
print("Total Traffic for Each Day:", total_traffic_per_day)
print("Busiest Hour of the Week:", busiest_hour_index, "with traffic of:", busiest_hour_traffic)


Total Traffic for Each Day: [45 52 30 75 60]
Busiest Hour of the Week: 2 with traffic of: 112


### Product Inventory Management
You have a NumPy array representing the stock levels of different products in a warehouse.


In [11]:


# Stock levels of different products in the warehouse
stock_levels = np.array([20, 55, 40, 80, 10, 70])

# Define thresholds
threshold = 50
required_stock = 100

# Identify products with stock levels below the threshold
low_stock_indices = np.where(stock_levels < threshold)

# Increase stock levels to the required threshold
stock_levels[low_stock_indices] = required_stock

# Output results
print("Updated Stock Levels:", stock_levels)


Updated Stock Levels: [100  55 100  80 100  70]


### Game Score Analysis
You have a NumPy array representing the scores of different players in a game over multiple 
rounds. Each row represents a player, and each column represents their score in a specific round.


In [12]:


# Scores of different players over multiple rounds
scores = np.array([[10, 20, 30],  # Player 1
                   [15, 25, 35],  # Player 2
                   [20, 30, 40]]) # Player 3

# Calculate the average score for each player
average_scores = np.mean(scores, axis=1)

# Identify the player with the highest average score
highest_avg_player_index = np.argmax(average_scores)

# Find the round with the highest total score across all players
total_scores_per_round = np.sum(scores, axis=0)
highest_round_index = np.argmax(total_scores_per_round)

# Output results
print("Average Score for Each Player:", average_scores)
print("Player with Highest Average Score: Player", highest_avg_player_index + 1)
print("Round with Highest Total Score: Round", highest_round_index + 1)


Average Score for Each Player: [20. 25. 30.]
Player with Highest Average Score: Player 3
Round with Highest Total Score: Round 3


### Financial Portfolio Analysis
You have a NumPy array representing the daily returns of different assets in a financial portfolio 
over a month. Each row represents an asset, and each column represents the return on a specific 
day.

In [13]:


# Daily returns of different assets over a month
returns = np.array([[0.01, 0.02, -0.01],  # Asset 1
                    [0.02, 0.01, 0.03],  # Asset 2
                    [-0.01, 0.03, 0.02]]) # Asset 3

# Calculate overall daily return of the portfolio
overall_daily_return = np.sum(returns, axis=0)

# Identify the asset with the highest volatility (standard deviation)
volatility = np.std(returns, axis=1)
highest_volatility_index = np.argmax(volatility)

# Find the day with the highest portfolio return
highest_return_day_index = np.argmax(overall_daily_return)

# Output results
print("Overall Daily Return of the Portfolio:", overall_daily_return)
print("Asset with Highest Volatility: Asset", highest_volatility_index + 1)
print("Day with Highest Portfolio Return: Day", highest_return_day_index + 1)


Overall Daily Return of the Portfolio: [0.02 0.06 0.04]
Asset with Highest Volatility: Asset 3
Day with Highest Portfolio Return: Day 2


### Healthcare Data Analysis
You are provided with a NumPy array where each element represents the number of patients 
treated in a hospital for a specific day of the year

In [14]:


# Number of patients treated each day (for simplicity, using 30 days)
patients_treated = np.array([40, 55, 30, 45, 60, 20, 50, 70, 
                              10, 15, 25, 30, 80, 90, 30, 
                              45, 55, 20, 25, 30, 40, 
                              60, 45, 50, 20, 15, 10, 
                              5, 30, 40, 35])

# Compute total number of patients treated for the year
total_patients = np.sum(patients_treated)

# Calculate average number of patients treated per day
average_patients = np.mean(patients_treated)

# Identify the day with the highest number of patients treated
max_patients = np.max(patients_treated)
day_with_max_patients = np.argmax(patients_treated)

# Determine number of days where treated patients exceeded the average
days_exceeding_average = np.sum(patients_treated > average_patients)

# Calculate percentage of days with fewer than 50 patients
percentage_below_50 = np.sum(patients_treated < 50) / len(patients_treated) * 100

# Output results
print("Total Patients Treated:", total_patients)
print("Average Patients Treated Per Day:", average_patients)
print("Day with Highest Patients Treated: Day", day_with_max_patients + 1, "with", max_patients, "patients")
print("Number of Days Exceeding Average:", days_exceeding_average)
print("Percentage of Days with Fewer than 50 Patients:", percentage_below_50, "%")


Total Patients Treated: 1175
Average Patients Treated Per Day: 37.903225806451616
Day with Highest Patients Treated: Day 14 with 90 patients
Number of Days Exceeding Average: 15
Percentage of Days with Fewer than 50 Patients: 70.96774193548387 %
