# Senerio Assignment 2
## Name: Neha Izhar
### nehaizhar123@gmail.com

In [1]:
import numpy as np

#### 1. Sales Data Analysis
You have a NumPy array representing the daily sales of a product over a month. Each element in
the array represents the sales for a particular day.
 Compute the total sales for the month.
 Calculate the average daily sales.
 Identify the day with the highest sales and its corresponding sales amount.


In [4]:
product_sales=np.array([20,99,150,115,95,69,73,100,87,36,79,153,36,88,67])
total_sales=np.sum(product_sales)
average_sales=np.mean(product_sales)
highest_sale=np.argmax(product_sales) +1
highest_sales_amount=product_sales[highest_sale-1]
print("Monthly Product Sales:",product_sales)
print("\nTotal Monthly Sales of Product:",total_sales)
print("\nAverage Monthly sales of products:",average_sales)
print("\nHighest Product Sales is on Day:",highest_sale)
print("\nHighest Product Sales is on Day amount",highest_sales_amount)

Monthly Product Sales: [ 20  99 150 115  95  69  73 100  87  36  79 153  36  88  67]

Total Monthly Sales of Product: 1267

Average Monthly sales of products: 84.46666666666667

Highest Product Sales is on Day: 12

Highest Product Sales is on Day amount 153


### 2. Weather Data Processing
Given a 2D NumPy array where each row represents daily temperature readings for a week (7
days), and each column represents readings from different weeks.
 Find the average temperature for each day across all weeks.
 Identify the day with the highest temperature recorded in the entire dataset.

In [6]:
temperature_data=np.array([[52,36,42,33,21,35,40],[21,25,65,36,75,98,22],[27,33,46,58,11,30,67]])
average_daily_temperature=np.mean(temperature_data, axis=0)
highest_temperature=np.max(temperature_data)
print("Average Daily Temperature:",average_daily_temperature)
print("\n Highest Temperature Recorded:",highest_temperature)

Average Daily Temperature: [33.33333333 31.33333333 51.         42.33333333 35.66666667 54.33333333
 43.        ]

 Highest Temperature Recorded: 98


### 3. Financial Analysis
You have a NumPy array representing the daily closing prices of a stock for a month.
 Compute the monthly return, which is the percentage change from the first to the last day
of the month.
 Calculate the daily percentage changes throughout the month.

In [8]:
closing_pricing=np.array([150,680,450,167,111,213,364,368,999,450])
first_day_price = closing_pricing[0] 
last_day_price =closing_pricing[-1]
monthly_return = ((last_day_price - first_day_price) / first_day_price) * 100
daily_changes = np.diff(closing_pricing) / closing_pricing[:-1] * 100
print("Daily closing prices of a stock for a month: ",closing_pricing)
print("\nMonthly Return of Stock:" ,monthly_return)
print("Daily percentage changes:", daily_changes)

Daily closing prices of a stock for a month:  [150 680 450 167 111 213 364 368 999 450]

Monthly Return of Stock: 200.0
Daily percentage changes: [353.33333333 -33.82352941 -62.88888889 -33.53293413  91.89189189
  70.89201878   1.0989011  171.4673913  -54.95495495]


### 4. Student Grades Analysis
You have a 2D NumPy array where each row represents a student, and each column represents
their grades in different subjects.
 Calculate the average grade for each student.
 Compute the overall class average for each subject.
 Identify the student with the highest average grade.

In [11]:
grades=np.array([[80,66,47],[98,60,78],[98,93,97]])
average_grades_per_student = np.mean(grades, axis=1)
class_average = np.mean(grades, axis=0)
highest_average_index = np.argmax(average_grades_per_student)
highest_average_grade = average_grades_per_student[highest_average_index]
print("Average grade for each student:", average_grades_per_student)
print("Overall class average for each subject:", class_average)
print(f"Student with the highest average grade: Student {highest_average_index + 1} with an average of {highest_average_grade:.2f}")

Average grade for each student: [64.33333333 78.66666667 96.        ]
Overall class average for each subject: [92. 73. 74.]
Student with the highest average grade: Student 3 with an average of 96.00


### 5. Image Processing
You have a grayscale image represented as a 2D NumPy array of pixel intensities (values range
from 0 to 255).
 Normalize the pixel values to a range of 0 to 1.
 Identify the pixel with the highest intensity and its location in the image.

In [13]:
image = np.array([[60,78,45],[15, 98, 36],[98, 25, 36]])
normalized_image = image / 255.0
print("Normalized image (0 to 1):\n", normalized_image)
max_ = np.max(image)
max_location = np.unravel_index(np.argmax(image), image.shape)

print(f"Highest intensity pixel value:", max_)
print("Location of the highest intensity pixel (row, column): ", max_location)

Normalized image (0 to 1):
 [[0.23529412 0.30588235 0.17647059]
 [0.05882353 0.38431373 0.14117647]
 [0.38431373 0.09803922 0.14117647]]
Highest intensity pixel value: 98
Location of the highest intensity pixel (row, column):  (np.int64(1), np.int64(1))


### 6. Population Growth Analysis
You have a NumPy array representing the population of a city over 10 years.
 Calculate the annual growth rate for each year.
 Identify the year with the highest growth.
 Compute the average annual growth rate over the 10-year period.

In [16]:
population = np.array([1555,3890,8765,1279,1000,9875,6754,9999,3421])
annual_growth = np.diff(population) / population[:-1] * 100

max_growth = np.argmax(annual_growth)
highest_growth = annual_growth[max_growth]
year_of_highest_growth = max_growth + 1  
average_growth_rate = np.mean(annual_growth)
print("Annual growth rates (%):", annual_growth)
print("Year with the highest growth: Year {year_of_highest_growth} with a growth rate of {highest_growth:}%")
print(f"Average annual growth rate over the 10 years: {average_growth_rate:.2f}%")


Annual growth rates (%): [150.1607717  125.32133676 -85.40787222 -21.81391712 887.5
 -31.60506329  48.04560261 -65.78657866]
Year with the highest growth: Year {year_of_highest_growth} with a growth rate of {highest_growth:}%
Average annual growth rate over the 10 years: 125.80%


### 7. Traffic Data Analysis
Given a 2D NumPy array where each row represents the number of vehicles passing through a
checkpoint during different hours of the day over a week.
 Calculate the total traffic for each day.
 Find the busiest hour of the week, i.e., the hour with the maximum number of vehicles
passing through.

In [18]:
traffic_data = np.array([[52,36,42,33,21,35,40],[21,25,65,36,75,98,22],[27,33,46,58,11,30,67]])
total_traffic = np.sum(traffic_data, axis=1)
print("Total traffic for each day:", total_traffic)
busiest_hour = np.argmax(np.sum(traffic_data, axis=0))
busiest_vehicles = np.sum(traffic_data, axis=0)[busiest_hour]
print(f"Busiest hour of the week: Hour {busiest_hour} with {busiest_vehicles} vehicles.")


Total traffic for each day: [259 342 272]
Busiest hour of the week: Hour 5 with 163 vehicles.


### 8. Product Inventory Management
You have a NumPy array representing the stock levels of different products in a warehouse.
 Identify the products with stock levels below a given threshold (e.g., 50 units).
 Increase the stock levels of these products to the required threshold (e.g., 100 units).

In [19]:
stock = np.array([98, 52, 63])
stock_threshold = 50
required_stock = 100
below_threshold = np.where(stock < stock_threshold)[0]
print("Products with stock levels below threshold:", below_threshold)
stock[below_threshold] = required_stock
print("Updated stock levels:", stock)


Products with stock levels below threshold: []
Updated stock levels: [98 52 63]


### 9. Game Score Analysis
You have a NumPy array representing the scores of different players in a game over multiple
rounds. Each row represents a player, and each column represents their score in a specific round.
 Calculate the average score for each player.
 Identify the player with the highest average score.
 Find the round with the highest total score across all players.


In [20]:
scores = np.array([[60,78,45],[15, 98, 36],[98, 25, 36]])
   
average_scores = np.mean(scores, axis=1)
print("Average score for each player:", average_scores)
highest_average_ = np.argmax(average_scores)
highest_average = average_scores[highest_average_]
print(f"Player with the highest average score: Player {highest_average_ + 1} with an average score of {highest_average:.2f}")
total_scores_per_round = np.sum(scores, axis=0)
highest_round_index = np.argmax(total_scores_per_round)
highest_round_score = total_scores_per_round[highest_round_index]

print(f"Round with the highest total score: Round {highest_round_index + 1} with a total score of {highest_round_score}")


Average score for each player: [61.         49.66666667 53.        ]
Player with the highest average score: Player 1 with an average score of 61.00
Round with the highest total score: Round 2 with a total score of 201


### 10. Financial Portfolio Analysis
You have a NumPy array representing the daily returns of different assets in a financial portfolio
over a month. Each row represents an asset, and each column represents the return on a specific
day.
 Calculate the overall daily return of the portfolio (sum of returns for all assets).
 Identify the asset with the highest volatility (standard deviation of daily returns).
 Find the day with the highest portfolio return.

In [21]:
daily_returns = np.array([[60,78,45],[15, 98, 36],[98, 25, 36]])
overall_daily_return = np.sum(daily_returns, axis=0)
print("Overall daily return of the portfolio:", overall_daily_return)
volatility = np.std(daily_returns, axis=1)
highest_volatility_index = np.argmax(volatility)
highest_volatility = volatility[highest_volatility_index]
print(f"Asset with the highest volatility: Asset {highest_volatility_index + 1} with a volatility of {highest_volatility:.4f}")
highest_return_index = np.argmax(overall_daily_return)
highest_return_value = overall_daily_return[highest_return_index]
print(f"Day with the highest portfolio return: Day {highest_return_index + 1} with a return of {highest_return_value:.4f}")


Overall daily return of the portfolio: [173 201 117]
Asset with the highest volatility: Asset 2 with a volatility of 35.2357
Day with the highest portfolio return: Day 2 with a return of 201.0000


### Healthcare Data Analysis
You are provided with a NumPy array where each element represents the number of patients
treated in a hospital for a specific day of the year.
 Compute the total number of patients treated for the entire year.
 Calculate the average number of patients treated per day.
 Identify the day with the highest number of patients treated and its corresponding count.
 Determine the number of days where the number of treated patients exceeded the average
daily count.
 Find the percentage of days where the hospital treated fewer than 50 patients.

In [22]:
patients_treated = np.array([20,99,150,115,95,69,73,100,87,36,79,153,36,88,67])
total_patients = np.sum(patients_treated)
print("Total number of patients treated in the year:", total_patients)
average_patients_per_day = np.mean(patients_treated)
print("Average number of patients treated per day:", average_patients_per_day)
highest_patients_index = np.argmax(patients_treated)
highest_patients_count = patients_treated[highest_patients_index]
print(f"Day with the highest number of patients treated: Day {highest_patients_index + 1} with {highest_patients_count} patients.")
days_above_average = np.sum(patients_treated > average_patients_per_day)
print("Number of days exceeding the average daily count:", days_above_average)
days_below_50 = np.sum(patients_treated < 50)
percentage_below_50 = (days_below_50 / len(patients_treated)) * 100
print(f"Percentage of days where treated patients < 50: {percentage_below_50:.2f}%")


Total number of patients treated in the year: 1267
Average number of patients treated per day: 84.46666666666667
Day with the highest number of patients treated: Day 12 with 153 patients.
Number of days exceeding the average daily count: 8
Percentage of days where treated patients < 50: 20.00%
