<div style="text-align: center;">
<strong>Name: Wajiha</strong><br>
<strong>E-mail: wajihachangez@gmail.com</strong>
</div>

### **Assignment Questions:-**
#### ***Basic Array Operations!***

##### **Q1: Create a 1D array, a 2D array and a 3D array?**
***

##### Loading Library of Numpy.

In [1]:
import numpy as np #Importing numpy library.

In [2]:
array_1d = np.array([4, 23, 3, 4, 15]) #Creating a 1D array
print("1D Array:\n", array_1d) #Printing 1D array
array_2d = np.array([[4, 23, 3],[1,0,8]]) #Creating a 2D array
print("2D Array:\n", array_2d) #Printing 2D array
array_3d = np.array([[[9,7,11],[2,6,54],[2,55,0]]]) # Creating a 3D array
print("3D Array:\n", array_3d) #Printing D array

1D Array:
 [ 4 23  3  4 15]
2D Array:
 [[ 4 23  3]
 [ 1  0  8]]
3D Array:
 [[[ 9  7 11]
  [ 2  6 54]
  [ 2 55  0]]]


##### **Q2: Perform slicing operations on arrays?**
***

In [3]:
array_1d[:2]

array([ 4, 23])

In [4]:
array_2d[1:3]

array([[1, 0, 8]])

In [5]:
array_3d[:]

array([[[ 9,  7, 11],
        [ 2,  6, 54],
        [ 2, 55,  0]]])

##### **Q3: Perform basic arithmetic operations on arrays (addition, subtraction, multiplication, division)?**
***

In [6]:
#Creating two 1-D arrays.
A1 = np.array([10, 20, 30, 40])
A2 = np.array([1, 2, 3, 4])
print("Array 01:    ",A1) #Printing first 1-D array.
print("Array 02:    ", A2) #Printing second 1-D array.
add_arrays = A1 + A2 #For element wise addition.
sub_arrays = A1 - A2 #For element wise subtraction.
mult_arrays= A1 * A2 #For element-wise multiplication.
dot_product = np.dot(A1, A2) #For overall matrix multiplication.
div_arrays = A1 / A2 #For element-wise division.
#Printing results.
print("Addition:    ",add_arrays)
print("Sbtraction:  ",sub_arrays)
print("Multiplication:",mult_arrays)
print("Matrix Multiplication using dot():", dot_product)
print("Division:    ", div_arrays)

Array 01:     [10 20 30 40]
Array 02:     [1 2 3 4]
Addition:     [11 22 33 44]
Sbtraction:   [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Matrix Multiplication using dot(): 300
Division:     [10. 10. 10. 10.]


#### ***Array Creation and Manipulation!***
##### **Q1: Create arrays using different functions: arange, linspace, zeros, ones, eye, random?**
***

In [7]:
array_arange = np.arange(0, 10, 2) #arrange function for array creation.
print("Array using arange Function: ", array_arange) #Printing array.
array_linspace = np.linspace(3,24,num=7) #linspace function for array creation.
print("Array Using linspace Function: ", array_linspace) #Printing array.
array_zero = np.zeros((4,3))  #Creating a 2-D array using zeros function.
print("Array Using zeros Function:\n",array_zero) #Printing array.
array_one = np.ones(5) #Creating a 1-D array using ones function.
print("Array Using ones Function: ", array_one) #Printing array.
array_eye = np.eye(2) #eye function for array creation(identity matrix).
print("Identity Matrix Using eye Function:\n", array_eye) #Printing array.
array_random = np.random.rand(3, 4) #random function for array creation.
print("Random Array Using random Function:\n", array_random) #Printing array.

Array using arange Function:  [0 2 4 6 8]
Array Using linspace Function:  [ 3.   6.5 10.  13.5 17.  20.5 24. ]
Array Using zeros Function:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array Using ones Function:  [1. 1. 1. 1. 1.]
Identity Matrix Using eye Function:
 [[1. 0.]
 [0. 1.]]
Random Array Using random Function:
 [[0.1958729  0.47206495 0.44474876 0.9951591 ]
 [0.05371342 0.11821165 0.57614811 0.01917955]
 [0.36401101 0.0409786  0.29552557 0.17762496]]


##### **Q2: Reshape an array?**
***

In [8]:
array_ages = np.arange(3,15,1) #Creating a 1D array of ages with 15 elements.
print("Original 1D Array of Ages: ", array_ages) #Printing original array.
array_ages_reshaped = array_ages.reshape(4,3) #Reshaping the 1D array of ages into a 2D array(4 rows, 3 columns)
print("Reshaped Array of Ages:\n", array_ages_reshaped) #Printing reshaped array.

Original 1D Array of Ages:  [ 3  4  5  6  7  8  9 10 11 12 13 14]
Reshaped Array of Ages:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


##### **Q3: Concatenate and split arrays?**
***

In [9]:
A_1 = np.array([[3,2,5,6],[3,2,1,9]]) #Creating first 2-D array.
A_2= np.array([[9,0,4,5],[0,77,1,9]]) #Creating second 2-D array.
Cncat_rows = np.concatenate((A_1,A_2), axis=0) #Concatenates along rows[increases the number of rows].
print("Concatenation of Array01 and Array02(Row-Wise):\n",Cncat_rows)
Cncat_cols = np.concatenate((A_1,A_2), axis=1) #Concatenates along columns[increases the number of columns].
print("Concatenation of Array01 and Array02(Coloumn-Wise):\n",Cncat_cols)

Concatenation of Array01 and Array02(Row-Wise):
 [[ 3  2  5  6]
 [ 3  2  1  9]
 [ 9  0  4  5]
 [ 0 77  1  9]]
Concatenation of Array01 and Array02(Coloumn-Wise):
 [[ 3  2  5  6  9  0  4  5]
 [ 3  2  1  9  0 77  1  9]]


In [10]:
oar = np.arange(12) #Creating a 1D array using arrange().
print("Original Array: ", oar)
split_oar = np.split(oar, 6) #Splitting the array into 6 equal parts.
print("Split Array: ", split_oar) #Printing splitting array.

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Split Array:  [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]), array([10, 11])]


#### ***Statistical Operations!***
##### **Q1: Compute mean, median, variance, and standard deviation of an array?**
***

In [11]:
marks = np.array([422,300,140,495,288,369,99,313,215,478]) #Creating a 1D array of marks
mean_value = np.mean(marks) #Calculating mean
median_value = np.median(marks) #Calculating median
variance_value = np.var(marks) #Calculating variance
std_value = np.std(marks) #Calculating standard deviation
#Printing Results.
print("Array of Marks:", marks)
print("Mean Value of marks:", mean_value)
print("Median of marks:", median_value)
print("Variance of marks:", variance_value)
print("Standard Deviation of marks:", std_value)


Array of Marks: [422 300 140 495 288 369  99 313 215 478]
Mean Value of marks: 311.9
Median of marks: 306.5
Variance of marks: 16147.690000000002
Standard Deviation of marks: 127.07356137293077


##### **Q2: Find the minimum and maximum values in an array along with their indices?**
***

In [12]:
ARRY = np.array([13, 70, 0, 12, -8, 4, 10, 1, 31,49,3]) #Creating 1D array.
minv = np.min(ARRY) #Finding minimum value.
mini = np.argmin(ARRY) #Finding index/position of minimum value.
maxv = np.max(ARRY) #Finding maximum value.
maxi = np.argmax(ARRY) #Finding index/position of maximum value.
print("Array: ", ARRY)
print("Minimum Value:", minv, "at index", mini)
print("Maximum Value:", maxv, "at index", maxi)

Array:  [13 70  0 12 -8  4 10  1 31 49  3]
Minimum Value: -8 at index 4
Maximum Value: 70 at index 1


##### **Q3: Compute the sum and product of array elements?**
***

In [13]:
b1 = np.array([3,67,8,9,1,2]) #Creating 1D array.
sum_b1 = np.sum(b1) #Sum of array elements.
product_b1 = np.prod(b1) #Product of array elements.
#Printing results of 1D array.
print("1D Array:", b1)
print("Sum of elements of 1D array:", sum_b1)
print("Product of elements of 1D array:", product_b1)
b2 = np.array([[6,5,3],[1,4,2]])
total_sumb2 = np.sum(b2) #Sum of all elements of 2D array.
row_sumb2 = np.sum(b2, axis=1) #Sum along rows of 2D array.
total_productb2 = np.prod(b2) #Product of all elements of 2D array.
column_productb2 = np.prod(b2, axis=0) #Product along columns of 2D array.
#Printing results of 2D array.
print("2D Array:\n", b2)
print("Total Sum of 2D array:", total_sumb2)
print("Sum along rows of 2D array:", row_sumb2)
print("Total Product of 2D array:", total_productb2)
print("Product along columns of 2D array:", column_productb2)

1D Array: [ 3 67  8  9  1  2]
Sum of elements of 1D array: 90
Product of elements of 1D array: 28944
2D Array:
 [[6 5 3]
 [1 4 2]]
Total Sum of 2D array: 21
Sum along rows of 2D array: [14  7]
Total Product of 2D array: 720
Product along columns of 2D array: [ 6 20  6]


#### ***Broadcasting!***
##### **Q1: Demonstrate broadcasting with examples of different shapes of arrays?**
***

>**Broadcasting:**
>>"The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations."<br>
>>**Example 01: Scalar and 1D Array.**<br>
When a scalar (a single number) is added to a 1D array, the scalar is broadcasted to each element in the array.

In [14]:
z1 = np.array([5, 2, 9, 4])  #Creating a 1D array.
res = z1 + 5 #Adding a scaler (5) to 1D array.
print("Original 1D Array: ",z1)
print("Result of adding scalar(5) to 1D array: ", res)

Original 1D Array:  [5 2 9 4]
Result of adding scalar(5) to 1D array:  [10  7 14  9]


>>**Example 2: 1D Array and 2D Array.**<br>
When a 1D array is added to a 2D array, the 1D array is broadcasted across the rows of the 2D array.

In [15]:
a_1d = np.array([12,9,8]) #1D Array
a_2d = np.array([[0,29,1],[8,9,3]]) #2D Array
result = a_1d + a_2d # Adding a 1D array to a 2D array.
print("Result of adding 1D array to 2D array:\n", result)

Result of adding 1D array to 2D array:
 [[12 38  9]
 [20 18 11]]


>>**Example 3: 1D Array and 2D Array with Different Dimensions.**<br>
In this case, we have a column vector and a row vector.The column vector is broadcasted across the columns, while the row vector is broadcasted across the rows.

In [16]:
arr1 = np.array([[1],[2]]) #1D Array(column vector)
arr2 = np.array([10,30]) #1D Array(row vector)
print("Array 01: \n ",arr1)
print("Array 02: \n ",arr2)
result = arr1 + arr2 #Adding column and row vectors(broadcasting along axes)
print("Result of adding column vector to row vector:\n", result)

Array 01: 
  [[1]
 [2]]
Array 02: 
  [10 30]
Result of adding column vector to row vector:
 [[11 31]
 [12 32]]


>>**Example 4: 3D Array and 2D Array.**<br>
Broadcasting can also work with multidimensional arrays like 3D and 2D arrays.

In [17]:
arr2d = np.array([[10, 20, 30],[40, 50, 60]]) #Creating 2D array.
arr3d = np.array([[[1],[2],[3]],[[4],[5],[6]]]) #Creating 3D array.
arr2d_reshaped = arr2d[:, :, np.newaxis]  #Adding a new axis to arr2d to make it 3D.
res3d_2d = arr2d_reshaped + arr3d #Adding 3D array to 2D array
print("Result of adding 3D array to 2D array:\n", res3d_2d)

Result of adding 3D array to 2D array:
 [[[11]
  [22]
  [33]]

 [[44]
  [55]
  [66]]]


>>**Arrays with Incompatible Shapes (Error)**<br>
If arrays have shapes that are not compatible for broadcasting, a ValueError will occur.

In [18]:
c1 = np.array([1, 2, 3])  #1D array.
c2 = np.array([[1, 2], [3, 4]]) #2D array.
r_t = c1 + c2 #Attempting to add arrays with incompatible shapes.
#Gives error because arrays shapes are not equal.

##### **Q2: Explain the concept of broadcasting and how it works in NumPy?**
***

>**Broadcasting in Numpy:**
>>--->In numpy, broadcasting lets in arrays with one-of-a-kind shapes to be combined in element-sensible operations(addition, subtraction, multiplication,etc)without explicitly reshaping them. This mechanism routinely expands smaller arrays to  the shape of larger arrays, making array operations extra efficient and much less bulky.<br>

>**How Broadcasting Works:**<br>
>>For broadcasting to occur, numpy compares the shapes of the arrays element-wise starting from the trailing dimensions. The following rules are apply:
>>>1) If the two dimensions are equal, they are compatible.
>>>2) If one of the dimensions is 1, it is stretched to match the other dimension.
>>>3) If the dimensions are unequal and neither is 1, broadcasting fails and an error is raised.

>**Steps for Broadcasting:**<br>
>>1. Alignment of shapes: 
>>>The smaller array is aligned to the larger array by adding dimensions with size 1 where necessary.
>>2. Stretching: 
>>>Any size 1 dimension in the smaller array is stretched (repeated) to match the corresponding dimension in the larger array.

>**Explaination of Example Solved Below in Code:**<br>
>> aa1 has a shape of (3, 1), and bb1 has a shape of (1, 4).
>>Numpy aligns the shapes as (3, 4) and (3, 4) by stretching:<br>
>>* aa1: Each element in the 3x1 array is repeated across 4 columns.<br>
>>* bb1: The single row in the 1x4 array is repeated across 3 rows.<br>

In [20]:
aa1 = np.array([[1], [2], [3]]) #Array a of shape (3, 1) stored in aa1.
bb1 = np.array([[1, 2, 3, 4]])  #Array b of shape (1, 4) stored in bb1.
res_ab = aa1 + bb1 #Performing broadcasting and storing it in res_ab variable.
print("Array aa1:\n", aa1)
print("Array bb1:\n", bb1)
print("Result of broadcasting:\n", res_ab)

Array aa1:
 [[1]
 [2]
 [3]]
Array bb1:
 [[1 2 3 4]]
Result of broadcasting:
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


>**Common Use Cases for Broadcasting:**<br>
>> The most commonly cases of broadcasting are mentioned below:
>>> * Adding a scalar to an array.
>>> * Applying an operation across a specific axis of a multidimensional array.

>**Benifits of Broadcasting:**<br>
>>The most common benefits of broadcasting are:
>>>1. **Memory-efficient:** No need to duplicate data.
>>>2. **Simpler code:** Less reshaping.
>>>3. **Faster:** Optimized for speed with large arrays.
>>>4. **Flexible:** Handles arrays of different dimensions easily.

#### ***Linear Algebra!***
##### **Q1: Perform matrix multiplication?**
***

In [24]:
AM1 = np.array([[10, 12],[3, 7]]) #Creating first matrix/2D array.
BM1 = np.array([[15, 6],[2, 5]])  #Creating second matrix/2D array.
Matrix_Multiplication = np.matmul(AM1 , BM1) #Performing matrix multiplication.
print("Matrix 01:\n", AM1) #Printing matrix 01.
print("Matrix 02:\n", BM1) #Printing matrix 02.
print("Result of AM1 * BM1:\n", Matrix_Multiplication) #Printing matrix multiplication.

Matrix 01:
 [[10 12]
 [ 3  7]]
Matrix 02:
 [[15  6]
 [ 2  5]]
Result of AM1 * BM1:
 [[174 120]
 [ 59  53]]


##### **Q2: Compute the determinant, inverse, and eigenvalues of a matrix?**
***

In [30]:
from numpy.linalg import det, inv, eig #importing specific functions from numpy linear algebra module.
LAM = np.array([[10, 12],[3, 7]]) #Creating first matrix/2D array/square matrix.
Determinant_LAM = det(LAM) #Calculating the determinant.
Inverse_LAM = inv(LAM) #Calculating the determinant.
Eigen_Value_LAM , Eigen_Vector_LAM  = eig(LAM) #Calculating eigen vector and value.
#Printing Results.
print("Matrix:\n", LAM)
print("Determinant of matrix:\n", Determinant_LAM)
print("Inverse of matrix:\n", Inverse_LAM)
print("Eigen value of matrix:\n", Eigen_Value_LAM)
print("Eigen Vector of matrix:\n", Eigen_Vector_LAM)

Matrix:
 [[10 12]
 [ 3  7]]
Determinant of matrix:
 34.00000000000001
Inverse of matrix:
 [[ 0.20588235 -0.35294118]
 [-0.08823529  0.29411765]]
Eigen value of matrix:
 [14.68465844  2.31534156]
Eigen Vector of matrix:
 [[ 0.93153209 -0.84212294]
 [ 0.36365914  0.5392856 ]]


##### **Q3: Solve a system of linear equations?**
***

In [34]:
ma1 = np.array([[3, 2],[4, 1]]) #Coefficient matrix01.
ma2 = np.array([4, 7]) #Constant matrix02.
solution_le = np.linalg.solve(ma1,ma2)
print("Linear Equation Solution(x, y):", solution_le) #Printing results, x = 2 and y = -1.

Linear Equation Solution(x, y): [ 2. -1.]


#### ***Advanced Indexing and Slicing!***
##### **Q1: Use Boolean indexing to filter an array?**
***

In [41]:
#Creating an array of ages.
ages_data = np.array([1,2,3,4,5,9,13,14,16,18,19, 22, 34, 39, 18, 45, 67, 77,80, 12, 29, 63, 36, 50])
#Filter out ages above 19 years.
adults = (ages_data >= 19) & (ages_data <= 39) #Creating a boolean array of adults.
toddlers = (ages_data >= 2) & (ages_data <= 4)#Creating a boolean array of toddlers.
#Using boolean indexing to filter the array.
filtered_adults = ages_data[adults]
filtered_toddlers = ages_data[toddlers]
#Printing results.
print("Filtered Ages of Adults:", filtered_adults)
print("Filtered Ages of Toddlers:", filtered_toddlers)

Filtered Ages of Adults: [19 22 34 39 29 36]
Filtered Ages of Toddlers: [2 3 4]


##### **Q2: Use fancy indexing to select specific elements from an array?**
***

In [61]:
weight = np.array([22, 47, 65, 101, 90, 50, 67,72]) #Creating an array of weight
position = [2, 4, 3] #Selecting indices and storing it in a position variable
selected_weights = weight[position] #Using fancy indexing to select specific elements of array weight.
print("Selected Weights: ", selected_weights) #Printing results of fancy indexing.

Selected Weights:  [ 65  90 101]


##### **Q3: Perform advanced slicing operations?**
***

In [79]:
#Number 01: "Basic Slicing"
d1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_d1 = d1[1:9:2]  #Slicing from position 1 to 9 with a step of 3.
print("Sliced Array with step of 3:", sliced_d1)
#Number 02: "Multi-dimensional Slicing"
m1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
subm1 = m1[0:2, 1:4]  #Slicing from rows 0 to 1 and columns 1 to 3
print("Sliced Matrix:\n",subm1)
#Number 03: "Reversing an Array"
reversed_d1 = d1[::-1]  #Reverse the 1D array.
print("Reversed Array:", reversed_d1)
#Number 04: "Advanced Slicing with Boolean Indexing"
agE= np.array([15, 22, 34, 18, 45, 67, 12, 29, 36, 50])
mask = agE > 30  #Create a Boolean mask for ages greater than 30
filtered_agE = agE[mask]
print("Ages greater than 30:", filtered_agE)
#Number 05: "Fancy Indexing with a 2D Array"
row = [0,2] #First and third row.
col = [2,3] #Third and fourth col.
fancy_sliced = m1[row,col]
print("Fancy Slicing Result:", fancy_sliced)
#Number 06: "Combining Slicing with Ellipsis"
w1 = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]]) #Creating a 3D array.
sliced_3d = w1[...,1]  #Selects previous all dimensions and  the second element in the last dimension.
print("Original 3D array:\n",w1)
print("Sliced 3D Array:\n",sliced_3d)

Sliced Array with step of 3: [1 3 5 7]
Sliced Matrix:
 [[2 3 4]
 [6 7 8]]
Reversed Array: [9 8 7 6 5 4 3 2 1 0]
Ages greater than 30: [34 45 67 36 50]
Fancy Slicing Result: [ 3 12]
Original 3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Sliced 3D Array:
 [[2 4]
 [6 8]]


#### ***Random Sampling!***
##### **Q1: Generate random numbers from different distributions?**
***

In [133]:
#Random Integers Distribution:
int_random_numbers = np.random.randint(1, 7, size=14)
print("Random Integers Distribution:", int_random_numbers)
#Normal Random Distribution:
normal_random_numbers = np.random.normal(0 , 5 , size=3)
print("Normal Random Distribution:", normal_random_numbers)
#Uniform Random Distribution
uniform_random_numbers = np.random.uniform(2 , 4 , size=5)
print("Uniform Random Distribution:", uniform_random_numbers)
#Binomial Random Distribution
binomial_random_numbers = np.random.binomial(n=10, p=0.5, size=5) #(n): number of trials,(p): probability of success,(size):number of samples.
print("Binomial Random Distribution:", binomial_random_numbers)
#Exponential Random Distribution
exponential_random_numbers = np.random.exponential(1.0, size=9)
print("Exponential Random Distribution:", exponential_random_numbers)
#Poisson Random Distribution
poisson_random_numbers = np.random.poisson(lam=4, size=6) #lam: lambda(rate of occurance)
print("Poisson Random Distribution:", poisson_random_numbers)
#Chi-Squared Random Distribution
chi_squared_random_numbers = np.random.chisquare(df=1, size=5) #df: degree of freedom
print("Chi-Squared Random Distribution:", chi_squared_random_numbers)

Random Integers Distribution: [2 4 6 6 4 2 1 6 4 6 5 5 1 2]
Normal Random Distribution: [-3.79989599  7.17033729 -1.27110424]
Uniform Random Distribution: [3.27485606 2.84373454 3.00902072 2.91091039 2.00605675]
Binomial Random Distribution: [6 5 3 6 5]
Exponential Random Distribution: [0.66526592 2.70624857 0.54529457 0.13248762 0.90820326 2.86195946
 0.61385738 1.48924296 0.46891131]
Poisson Random Distribution: [3 2 6 4 4 2]
Chi-Squared Random Distribution: [0.15786628 0.18623946 0.04107872 0.07265241 0.22921887]


##### **Q2: Create random samples from a dataset?**
***

In [143]:
data_set = np.array([10,0 ,54, 65, 1,20, 30, 40, 50, 60, 54, 13, 21, 70, 80, 90, 100]) #Creating a dataset.
samples_extract = 7 #Set the number of samples you want to extract from dataset.
#Generating random samples from the dataset.
random_dataset_samples = np.random.choice(data_set, size = samples_extract, replace=False) #replace=False: means we want unique samples.
print("Random Samples Extracting from Original Dataset:", random_dataset_samples)

Random Samples Extracting from Original Dataset: [90 50 20 10 21 60 80]


##### **Q3: Perform random shuffling of an array?**
***

In [148]:
#Creating original array.
arry1 = np.array([5,7,6,5,1,2,0,9,8,10])
print("Original Array: ",arry1)
#Shuffling the original array.
np.random.shuffle(arry1)
print("Shuffled Array: ", arry1)

Original Array:  [ 5  7  6  5  1  2  0  9  8 10]
Shuffled Array:  [ 6  1  2  0  5  9  7  5 10  8]


***