<div style="text-align: center; font-size: 30px;">
<strong>Name: Wajiha</strong><br>
<strong>E-mail: wajihachangez@gmail.com</strong>
</div>

### ***Assignment Questions:-***
##### Problem 1:
You have five objects of unknown mass m1,m2,m3,m4,m5. You would like to find the mass of each of these
objects using the scale. If you put one or more of the objects on each side of the scale you will be able to measure the difference in weight.This scale does not work,however,if one side is left empty<br>
* (A) You make a measurement of objects {1, 2} against objects {3, 4} and get a difference of 1 kg. Write this as a linear equation for the masses. 
* (B) What is the minimum number of such measurements necessary to recover all five masses?
* (C) If the answer to the above question is N, come up with N−1 measurements that, when combined with the answer to (A) above, would make it possible to recover the masses.
* (D) What would A and b be in the matrix form of the linear system corresponding to the N measurements? That is, if you were to set this up as Am = b where m is the vector of unknown masses. Denote the result of the ith measurement as bi. (Typeset these using the bmatrix environment.)

In [101]:
#Loading library of numpy.
import numpy as np
#Creating matrix A.
A = np.array([[1,  1, -1, -1,  0],[0,  1,  0,  1, -1], [0,  0,  1, -1,  0], [1, -1,  0,  0,  0],[0,  0,  0,  0,  1] ])
#Creating Vector b.
b = np.array([1, 0, 0, 0, 0])  
#Solving linear equation for the unknown masses.
masses = np.linalg.solve(A, b)
#Printing Results.
print("Matrix A[coefficients]:\n", A)
print("Vector b[constants]:\n", b)
print("Masses of the objects:", masses)

Matrix A[coefficients]:
 [[ 1  1 -1 -1  0]
 [ 0  1  0  1 -1]
 [ 0  0  1 -1  0]
 [ 1 -1  0  0  0]
 [ 0  0  0  0  1]]
Vector b[constants]:
 [1 0 0 0 0]
Masses of the objects: [ 0.25  0.25 -0.25 -0.25  0.  ]


***

##### Problem 2:
The core library for numerical computation in Python is called NumPy. NumPy provides useful abstractions to create and manipulate multidimensional arrays (e.g., vectors, matrices, tensors), and functions that are thin layers over high-performance C/C++/Fortran BLAS and LAPACK libraries. Conventionally, you would start your numeric Python code with an import numpy as np. The most basic object is the NumPy array, which is a multi-dimensional array usually made up of type double, i.e., 64-bit floating point numbers. A vector is usually a one-dimensional array, and a matrix is a two-dimensional array:<br>
example_vector = np.array([50.0, 1.4, 0.4, 0.23, 1.04])<br>
example_matrix = np.array([[3.4, 1.10, 0.8], 
                           [4.2, 100.0, -1.4], 
                           [1.1, 0.44, 9.4]])<br>
Higher-dimensional arrays (tensors) are possible, but come up less often than vectors and matrices. The tuple made up of the size of each dimension is called the shape and can be accessed as an attribute, so:<br>
print(example_vector.shape, example_matrix.shape)<br>
Output: (5,) (3, 3) <br>
Create a Colab notebook following the same pattern as the previous assignment, and do the following:
* A. Use arange to create a variable named foo that stores an array of numbers from 0 to 29, inclusive. Print foo and its shape.

In [102]:
foo = np.arange(30)
print("Numbers from 0 to 29 using arange() function: ",foo)
print("Shape of foo:", foo.shape)

Numbers from 0 to 29 using arange() function:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Shape of foo: (30,)


* B. Use the reshape function to change foo to a validly-shaped two-dimensional matrix and store it in a new variable called bar. Print bar and its shape.

In [103]:
bar = foo.reshape(6, 5)
print("Changing foo(1D) into bar(2D):\n", bar)
print("Shape of bar:", bar.shape)

Changing foo(1D) into bar(2D):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Shape of bar: (6, 5)


* C. Create a third variable, baz that reshapes it into a valid three-dimensional shape. Print baz and its shape.

In [104]:
baz = foo.reshape(2, 5, 3)
print("Changing foo(1D) into baz(3D):\n",baz)
print("Shape of baz:", baz.shape)

Changing foo(1D) into baz(3D):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
Shape of baz: (2, 5, 3)


* D. There are several different ways to index into NumPy arrays. Use two-dimensional array indexing to set the first value in the second row of bar to -1. Now look at foo and baz. Did they change? Explain what’s going on. (Hint: does reshape return a view or a copy?)

In [105]:
bar[1, 0] = -1
#Printing bar, foo and baz after modification:
print("bar:\n", bar)
print("foo:\n", foo)
print("baz:\n", baz)
#Explaination:
"""After setting the first value of the second row of bar to -1, both foo and baz will also change.
This is because reshape() in NumPy returns a view, not a copy. A view is a new array object that looks at the same data as the original array. 
Any modifications to one will reflect in all views nation:"""

bar:
 [[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
foo:
 [ 0  1  2  3  4 -1  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
baz:
 [[[ 0  1  2]
  [ 3  4 -1]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


'After setting the first value of the second row of bar to -1, both foo and baz will also change.\nThis is because reshape() in NumPy returns a view, not a copy. A view is a new array object that looks at the same data as the original array. \nAny modifications to one will reflect in all views nation:'

* E. Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular) and do the following:<br>
1. Sum baz over its second dimension and print the result.
2.  Sum baz over its third dimension and print the result.
3.  Sum baz over both its first and third dimensions and print the result.

In [106]:
#Part 1.
sum_baz_axis1 = baz.sum(axis=1)
print("Sum of baz over its second dimension:\n", sum_baz_axis1)
#Part 2.
sum_baz_axis2 = baz.sum(axis=2)
print("Sum of baz over its third dimension:\n", sum_baz_axis2)
#Part 3.
sum_baz_axis0_2 = baz.sum(axis=(0, 2))
print("Sum of baz over both its first and thirddimensions:\n", sum_baz_axis0_2)

Sum of baz over its second dimension:
 [[ 30  35  34]
 [105 110 115]]
Sum of baz over its third dimension:
 [[ 3  6 21 30 39]
 [48 57 66 75 84]]
Sum of baz over both its first and thirddimensions:
 [ 51  63  87 105 123]


* F. Along with shaping and indexing, we also do a lot of slicing, which is where you index with ranges to get subvectors and sometimes submatrices. Write code to do the following:
1. Slice out the second row of bar and print it.
2. Slice out the last column of bar using the -1 notation and print it.
3. Slice out the top right 2×2 submatrix of bar and print it.

In [107]:
#Part 1.
print("Second row of bar:\n", bar[1])
#Part 2.
print("Last column of bar:\n", bar[:,-1])
#Part 3.
print("Top right 2x2 submatrix of bar:\n", bar[0:2,-2:])

Second row of bar:
 [-1  6  7  8  9]
Last column of bar:
 [ 4  9 14 19 24 29]
Top right 2x2 submatrix of bar:
 [[3 4]
 [8 9]]


***

##### Problem 3:
One feature of NumPy that is powerful but tricky is the ability to perform broadcasting, which really just refers to repeatedly performing an operation over one or more dimensions. Start a new problem in your Colab notebook, and when you’re done with the entire assignment, follow the same procedure for appending a PDF and inserting the URL as you did in the previous assignment. The notebook URL is near the end of the assignment.<br>
* A. The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply,...) on an array and a scalar; the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, ..., 10 by adding 1 to the result of the arange function.

In [108]:
vector = np.arange(0,10) + 1
print("Vector using broadcasting:",vector)

Vector using broadcasting: [ 1  2  3  4  5  6  7  8  9 10]


* B. Now, create a 10×10 matrix 
A in which 𝐴𝑖𝑗 = 𝑖+𝑗. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself.

In [109]:
A = vector.reshape(10, 1) + vector  
print("Matrix A(10*10):\n", A)

Matrix A(10*10):
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


* D. A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. First, create a fake 'dataset' with 50 examples, each with five dimensions.<br>
import numpy.random as npr<br>
data = np.exp(npr.randn(50, 5))<br>
You don’t worry too much about what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number generation library, then generates a 50×5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend dataset of 50 independent and identically-distributed vectors from a log-normal distribution.

In [110]:
import numpy.random as npr
data = np.exp(npr.randn(50, 5))
print("Fake Dataset:\n", data)
#Standarizing the dataset:
mean = data.mean(axis=0)  
std = data.std(axis=0)
standardized_data = (data - mean) / std
print("Mean of standardized data:", standardized_data.mean(axis=0))
print("Standard deviation of standardized data:", standardized_data.std(axis=0))

Fake Dataset:
 [[ 0.95546458  1.24595608  0.51077476  0.61112956  1.77839304]
 [ 0.14322961  6.62916986  2.12708455  0.27905005  1.01718028]
 [ 0.51692319  2.69850333  4.88788803  1.37379108  0.38826309]
 [ 0.41409938  0.16121619  1.28396002  0.73602174  0.66816431]
 [ 0.86386972  0.9159779   0.43024101  0.5090306   0.48810113]
 [ 0.96839505  0.77779668  2.31050742  0.19301065  0.53590128]
 [ 2.02529113  2.15599336  1.84811342  1.8051634   0.31104348]
 [ 1.98099599  2.12885511  3.35904016  5.54699543  1.50341072]
 [ 0.50543782  1.02063434  1.20944179  1.3156545   0.35105449]
 [ 1.97797508  0.10910601  5.26631757  1.3494622   0.3561087 ]
 [ 0.10576801  0.53222499  2.13421659  0.4662761   2.83716493]
 [ 5.06056648  1.31704798  0.14288088  0.26213048  0.1887616 ]
 [ 1.46923806  1.388324    0.27656464  7.98772344 15.68370368]
 [ 0.34509438  0.24972012  0.42693955  1.15394338  4.81977137]
 [ 0.22504231  1.77213357  0.06226811  0.72112302  3.69021125]
 [ 3.66768498  1.37982774  0.33905742  1

* E. Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit about how to use the axis argument to mean and std. Store these vectors into variables and print both of them.

In [111]:
#Mean for each column.
mean_vector = data.mean(axis=0)  
#Standard deviation for each column.
std_vector = data.std(axis=0)     
#Printing results:
print("Mean of each column:", mean_vector)
print("Standard deviation of each column:", std_vector)

Mean of each column: [1.43912497 1.76165276 1.93578856 1.9473702  1.69674176]
Standard deviation of each column: [1.15113912 1.70876542 2.74593802 3.49067483 2.34932484]


* F. Now standardize the data matrix by 1. subtracting the mean off of each column, and 2.dividing each column by its standard deviation. Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of the columns of normalized and print them out.

In [112]:
normalized = (data - mean_vector) / std_vector
mean_normalized = normalized.mean(axis=0)
std_normalized = normalized.std(axis=0)
#Printing Results:
print("Normalized Data:\n", normalized)
print("Mean of normalized data:", mean_normalized)
print("Standard deviation of normalized data:", std_normalized)

Normalized Data:
 [[-4.20158069e-01 -3.01794899e-01 -5.18953375e-01 -3.82802955e-01
   3.47552087e-02]
 [-1.12575043e+00  2.84855782e+00  6.96650787e-02 -4.77936282e-01
  -2.89258205e-01]
 [-8.01121043e-01  5.48261661e-01  1.07507870e+00 -1.64317547e-01
  -5.56959452e-01]
 [-8.90444575e-01 -9.36604026e-01 -2.37379190e-01 -3.47024149e-01
  -4.37818318e-01]
 [-4.99726951e-01 -4.94904011e-01 -5.48281694e-01 -4.12052018e-01
  -5.14462969e-01]
 [-4.08925306e-01 -5.75770128e-01  1.36462971e-01 -5.02584640e-01
  -4.94116634e-01]
 [ 5.09205316e-01  2.30775149e-01 -3.19290297e-02 -4.07390574e-02
  -5.89828303e-01]
 [ 4.70725923e-01  2.14893362e-01  5.18311627e-01  1.03121184e+00
  -8.22921714e-02]
 [-8.11098442e-01 -4.33657197e-01 -2.64516811e-01 -1.80972372e-01
  -5.72797448e-01]
 [ 4.68101643e-01 -9.67099836e-01  1.21289300e+00 -1.71287225e-01
  -5.70646101e-01]
 [-1.15829350e+00 -7.19483062e-01  7.22623853e-02 -4.24300221e-01
   4.85425916e-01]
 [ 3.14596338e+00 -2.60190651e-01 -6.52930862e-

***

##### Problem 4:
Fairly often in machine learning and other disciplines that use linear algebra to formalize computational problems, you see explicit matrix inverses like 𝐴−1bin papers and books. Of course, you learn in linear algebra classes how to perform such an inverse, and in the NumPy linear algebra library, you’ll see a function that will compute the inverse. It seems sensible, right? And it’s right there on the page: Invert the matrix 𝐴
A and then multiply by the vector 𝑏. How hard can it be?
Well... don’t do that. When you see 𝐴−1b, you should read that as “the 𝑥
that is the result of solving the linear system 𝐴𝑥=𝑏”. You should use something like the solve function in the NumPy linear algebra package. If you have to solve multiple such systems with the same matrix, you might think about performing an LU decomposition, a topic we’ll return to in a couple of weeks.
The issue is one of numerical stability, which boils down to the fact that 1. floating point numbers on computers don’t have infinite precision, and 2. some quantities (e.g., infinite sums or numerical integrals) require us to truncate and approximate if we want the computation to complete. These issues are deep, and this course won’t delve into them significantly. However, the “explicit inverse” issue is worth looking at just to see an example.
* A. A Vandermonde matrix is a matrix generated from a vector in which each column of the matrix is an integer power starting from zero. So, if I have a column vector [𝑥1,𝑥2,…,𝑥𝑁]𝑇 and then the associated (square) Vandermonde matrix would be: V= ......
Use what you learned about broadcasting in the previous problem to write a function that will produce a Vandermonde matrix for a vector [1,2,…,𝑁]𝑇[1,2,…,N] T for any 𝑁. Do it without using a loop. Here’s a stub to get you started:
def vandermonde(N):
    vec = np.arange(N) + 1
    Finish me.
Use your function for N=12, store it in a variable named vander, and print the result.

In [113]:
def vandermonde(N):
    vec = np.arange(N) + 1 
    vander = vec[:, np.newaxis] ** np.arange(N)  
    return vander
# Use the function for N=12
vander = vandermonde(12)
print("Vandermonde Matrix for N=12:")
print(vander)

Vandermonde Matrix for N=12:
[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    3627

* B. Now, let’s make a pretend linear system problem with this matrix. Create a vector of all ones, of length 12, and call it x. Perform a matrix-vector multiplication of vander with the vector you just created and store that in a new vector and call it b. Print the vector 𝑏.

In [114]:
# Create a vector of all ones of length 12
N = 12
x = np.ones(N)
# Perform matrix-vector multiplication
b = vander @ x 
#Printing Results:
print("Vector b:\n",b)


Vector b:
 [1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


* C.  First, solve the linear system the naïve way, pretending like you don’t know x. Import numpy.linalg, invert V and multiply it by b. Print out your result. What should you get for your answer? If the answer is different than what you expected, write a sentence about that difference.

In [115]:
#Inverting the Vandermonde matrix and multiply by b.
x_naive = np.linalg.inv(vander) @ b
#Printing the result.
print("Naive solution for x:\n",x_naive)
#Checking the difference from the original x.
difference = np.abs(x_naive - x)
print("Difference from expected x:",difference)
#"The naive method of inverting the Vandermonde matrix did not return the expected vector of ones, indicating that the inversion may have introduced numerical instability or inaccuracies due to the properties of the matrix."

Naive solution for x:
 [-17.93115234 -15.3359375   45.20117188  -8.62402344   1.66650391
   1.03100586   0.99163818   1.00068283   0.99995947   1.00000198
   0.99999994   1.        ]
Difference from expected x: [1.89311523e+01 1.63359375e+01 4.42011719e+01 9.62402344e+00
 6.66503906e-01 3.10058594e-02 8.36181641e-03 6.82830811e-04
 4.05311584e-05 1.98185444e-06 6.05359674e-08 8.14907253e-10]


* D. Now, solve the same linear system using solve. Print out the result. Does it seem more or less in line with what you’d expect?

In [116]:
x_solve = np.linalg.solve(vander, b)
#Printing the result.
print("Solution using solve:", x_solve)
#Check if it matches the expected vector of ones
if np.allclose(x_solve, x):
    print("The solution is in line with what I expected: it matches the vector of ones.")  
else:
    print("The solution is not in line with what I expected.") 

Solution using solve: [0.94745958 1.14735264 0.83240703 1.10431846 0.95985529 1.0101629
 0.99825441 1.00020516 0.99998372 1.00000083 0.99999997 1.        ]
The solution is not in line with what I expected.


***

##### Problem 05:
Approximately how many hours did this assignment take you to complete?

Approximately 3  hours for the entire assignment.

***