<div style="text-align: center;">
<strong>Name: Wajiha</strong><br>
<strong>E-mail: wajihachangez@gmail.com</strong>
</div>

### ***Assignment Questions:-***
##### Problem1:
You have five objects of unknown mass m1,m2,m3,m4,m5. You would like to find the mass of each of these
objects using the scale. If you put one or more of the objects on each side of the scale you will be able to measure the difference in weight.This scale does not work,however,if one side is left empty<br>
* (A) You make a measurement of objects {1, 2} against objects {3, 4} and get a difference of 1 kg. Write this as a linear equation for the masses. 
* (B) What is the minimum number of such measurements necessary to recover all five masses?
* (C) If the answer to the above question is N, come up with N−1 measurements that, when combined with the answer to (A) above, would make it possible to recover the masses.
* (D) What would A and b be in the matrix form of the linear system corresponding to the N measurements? That is, if you were to set this up as Am = b where m is the vector of unknown masses. Denote the result of the ith measurement as bi. (Typeset these using the bmatrix environment.)

In [6]:
#Loading library of numpy.
import numpy as np
# (A) Create the coefficients matrix A and the results vector b
# The equations based on the problem statement:
# 1. m1 + m2 - m3 - m4 = 1    (from the first measurement)
# 2. m2 + m4 - m5 = 0         (from the second measurement)
# 3. m3 - m4 = 0              (from the third measurement)
# 4. m1 - m2 = 0              (from the fourth measurement)
# 5. m5 = 0                   (from the fifth measurement, arbitrary choice for simplicity)
#Coefficient matrix A
A = np.array([
    [1,  1, -1, -1,  0],  # m1 + m2 - m3 - m4 = 1
    [0,  1,  0,  1, -1],  # m2 + m4 - m5 = 0
    [0,  0,  1, -1,  0],  # m3 - m4 = 0
    [1, -1,  0,  0,  0],  # m1 - m2 = 0
    [0,  0,  0,  0,  1]   # m5 = 0
])
#Results vector b
b = np.array([1, 0, 0, 0, 0])  
# (B) Minimum number of measurements necessary to recover all five masses
# Based on linear algebra, we typically need at least N-1 independent equations for N unknowns.
# In this case, we have 5 unknowns, so we need a minimum of 4 independent measurements.
# (C) N - 1 measurements can be any set of linear combinations of the above. Here are 3 additional measurements:
# - m1 = m2 (as derived from the fourth equation)
# - m3 = m4 (from the third equation)
# - m5 = 0 (as assumed)
# Additional measurements can be reflected in the A matrix if needed.
# (D) To find the masses, we can solve the linear system Am = b
# Step 2: Solve for the unknown masses
masses = np.linalg.solve(A, b)
#Printing Results:
print("Masses of the objects:", masses)
print("Matrix A (coefficients):\n", A)
print("Vector b (results):\n", b)


Masses of the objects: [ 0.25  0.25 -0.25 -0.25  0.  ]
Matrix A (coefficients):
 [[ 1  1 -1 -1  0]
 [ 0  1  0  1 -1]
 [ 0  0  1 -1  0]
 [ 1 -1  0  0  0]
 [ 0  0  0  0  1]]
Vector b (results):
 [1 0 0 0 0]


***