<div style="text-align: center;">
<strong>Name: Wajiha</strong><br>
<strong>E-mail: wajihachangez@gmail.com</strong>
</div>

### ***Assignment Questions:-***
##### Q1: Sales Data Analysis:
You have a NumPy array representing the daily sales of a product over a month. Each element in 
the array represents the sales for a particular day.<br>
* Compute the total sales for the month. 
* Calculate the average daily sales. 
* Identify the day with the highest sales and its corresponding sales amount.

In [112]:
#Loading numpy library
import numpy as np
#Creating an array that reprents product monthly sales.
product_sales = np.array([120, 80, 95, 100, 85, 90, 150, 200, 75, 60, 110, 130, 105, 100, 95, 85, 120, 110, 150, 190, 75, 85, 100, 140, 160, 130, 90, 80, 100, 110])
total_product_sales = np.sum(product_sales) #Total product sales over the month.
average_product_sales = np.mean(product_sales) #Average product sales over the month.
highest_sales = np.max(product_sales) #Product with highest sale.
highest_product_sales_day = np.argmax(product_sales) + 1 #Day with the highest sales (Note: we added +1 since days start from 1, not from 0).
#Printing Results:
print("Monthly Product Sales: ",product_sales)
print("Total Monthly Sales of the Product: ", total_product_sales)
print("Average Monthly Sales of the Product: ",average_product_sales)
print("Highest Product Sales is on Day: ",highest_product_sales_day,"with product sales of", highest_sales)

Monthly Product Sales:  [120  80  95 100  85  90 150 200  75  60 110 130 105 100  95  85 120 110
 150 190  75  85 100 140 160 130  90  80 100 110]
Total Monthly Sales of the Product:  3320
Average Monthly Sales of the Product:  110.66666666666667
Highest Product Sales is on Day:  8 with product sales of 200


***

##### Q2: Weather Data Processing:
Given a 2D NumPy array where each row represents daily temperature readings for a week (7 
days), and each column represents readings from different weeks. <br>
* Find the average temperature for each day across all weeks.
* Identify the day with the highest temperature recorded in the entire dataset.

In [113]:
#Creating a 2D array with 4 rows and 7 coloumn[rows: represents weeks, coloumns: represents daily temperature].
temperatures_detail_weekly = np.array([[71, 73, 75, 74, 72, 70, 69],[70, 72, 76, 75, 71, 69, 68],[69, 74, 77, 72, 70, 71, 67],[72, 75, 73, 76, 74, 68, 66]])
#Calculating the average temperature for each day across all weeks.
average_temperatures_allweeks = np.mean(temperatures_detail_weekly, axis=0)
#Identify the highest temperature index the entire dataset using reshape.
high_temp_index = np.argmax(temperatures_detail_weekly.reshape(-1))
#Highest temperature value.
highest_temperature_value = temperatures_detail_weekly.flatten()[high_temp_index]
#Get week and day of highest temperature
day_of_highest_temperature = divmod(high_temp_index, temperatures_detail_weekly.shape[1])  
#Displaying Results:
print("Average temperatures for each day across all weeks:", average_temperatures_allweeks)
print(f"Highest temperature recorded: {highest_temperature_value} on Day {day_of_highest_temperature[1] + 1} of Week {day_of_highest_temperature[0] + 1}")


Average temperatures for each day across all weeks: [70.5  73.5  75.25 74.25 71.75 69.5  67.5 ]
Highest temperature recorded: 77 on Day 3 of Week 3


***

##### Q3:  Financial Analysis:
You have a NumPy array representing the daily closing prices of a stock for a month.<br>
* Compute the monthly return, which is the percentage change from the first to the last day 
of the month. 
* Calculate the daily percentage changes throughout the month.

In [114]:
#Creating an array representing daily closing prices of a stock for a month.
daily_closing_prices = np.array([100, 102, 104, 103, 105, 106, 107, 108, 110, 109,108, 107, 106, 104, 105, 106, 108, 110, 112, 111,113, 114, 115, 117, 118, 116, 115, 114, 113, 115])
#Closing price of first day.
first_day_price = daily_closing_prices[0] 
#Closing price of last day.
last_day_price = daily_closing_prices[-1] 
#Formula for monthly return of stock.
monthly_return = ((last_day_price - first_day_price) / first_day_price) * 100 
#Calculating the daily percentage changes.
daily_percentage_changes = np.diff(daily_closing_prices) / daily_closing_prices[:-1] * 100
#Displaying results:
print("Daily closing prices of a stock for a month: ",daily_closing_prices)
print(f"Monthly Return of Stock: {monthly_return:.2f}%")
print("Daily Percentage Changes through out the month:",daily_percentage_changes)

Daily closing prices of a stock for a month:  [100 102 104 103 105 106 107 108 110 109 108 107 106 104 105 106 108 110
 112 111 113 114 115 117 118 116 115 114 113 115]
Monthly Return of Stock: 15.00%
Daily Percentage Changes through out the month: [ 2.          1.96078431 -0.96153846  1.94174757  0.95238095  0.94339623
  0.93457944  1.85185185 -0.90909091 -0.91743119 -0.92592593 -0.93457944
 -1.88679245  0.96153846  0.95238095  1.88679245  1.85185185  1.81818182
 -0.89285714  1.8018018   0.88495575  0.87719298  1.73913043  0.85470085
 -1.69491525 -0.86206897 -0.86956522 -0.87719298  1.7699115 ]


***

##### Q4: Student Grades Analysis:
You have a 2D NumPy array where each row represents a student, and each column represents 
their grades in different subjects.<br>
* Calculate the average grade for each student.
* Compute the overall class average for each subject. 
* Identify the student with the highest average grade.

In [115]:
#Creating a 2D array for students grades analysis:[Rows represents students, coloumns represent marks].
students_grades = np.array([[90,95,99,85,89,86],[33,45,50,29,12,34],[80,75,99,88,89,91],[76,65,50,39,87,60],[50,67,35,43,41,23],[97,90,86,80,89,94]])
#List of student names corresponding to each row.
student_names = ["Alizay", "Saba", "Minahil", "Khansa", "Deeba", "Maryam"] 
#Calculating the average grade for each student.
student_average = np.mean(students_grades,axis=1) 
#Calculating the average of overall class grade for each subject.
class_average = np.mean(students_grades,axis=0) 
#Identifying the student with the highest average grade.
#Index of the student with the highest average.
highest_avg_index = np.argmax(student_average)  
#Name of that student.
highest_avg_student = student_names[highest_avg_index]  
#Highest average grade
highest_avg_grade = student_average[highest_avg_index]  
#Displaying Results.
print("Average grade for each student:")
for name,avg in zip(student_names,student_average):
    print(f"{name}: {avg:.2f}")
print("Overall class average for each subject: ",class_average)
print(f"Student with the highest average grade: {highest_avg_student} with an average of {highest_avg_grade:.2f}")

Average grade for each student:
Alizay: 90.67
Saba: 33.83
Minahil: 87.00
Khansa: 62.83
Deeba: 43.17
Maryam: 89.33
Overall class average for each subject:  [71.         72.83333333 69.83333333 60.66666667 67.83333333 64.66666667]
Student with the highest average grade: Alizay with an average of 90.67


***

##### Q5: Image Processing:
You have a grayscale image represented as a 2D NumPy array of pixel intensities (values range 
from 0 to 255). <br>
* Normalize the pixel values to a range of 0 to 1.
* Identify the pixel with the highest intensity and its location in the image. 

In [116]:
#Creating a 2D array containing pixel intensities[0 to 255].
gray_image = np.array([[120, 64, 255],[0, 192, 128],[255, 57, 89]])
#Normalize the pixel values to a range of 0 to 1.
normalized_gray_image = gray_image / 255.0 
# Flatten the image to a 1D array to find the highest intensity and its index
flat_gray_image = gray_image.flatten()
# Identify the pixel with the highest intensity and its index in the flattened array
highest_intensity = np.max(flat_gray_image) 
highest_gray_index = np.argmax(flat_gray_image)  
#Finding the location in an image.
location_of_highest_intensity = (highest_gray_index // gray_image.shape[1], highest_gray_index % gray_image.shape[1])
#Printing results.
print("Normalize Image:\n", normalized_gray_image)
print(f"Highest Intensity: {highest_intensity} at Location: {int(location_of_highest_intensity[0])}, {int(location_of_highest_intensity[1])}")

Normalize Image:
 [[0.47058824 0.25098039 1.        ]
 [0.         0.75294118 0.50196078]
 [1.         0.22352941 0.34901961]]
Highest Intensity: 255 at Location: 0, 2


***

##### Q6:  Population Growth Analysis:
You have a NumPy array representing the population of a city over 10 years. <br>
* Calculate the annual growth rate for each year. 
* Identify the year with the highest growth. 
* Compute the average annual growth rate over the 10-year period. 

In [117]:
#Creating a 1D array containing population of cities over 10 years.
pop = np.array([2000,10000,6000,5000,4500,3200,1100,1500,1900,6700])
#Annual growth rates as percentages for each year.
#Calculating the annual growth rate of population.
annual_growth_rate = ((pop[1:]-pop[:-1])/pop[:-1]) * 100 
#Identify the year with the highest growth.
ywhg = np.argmax(annual_growth_rate) +1 
#Calculating the average annual growth rate over the 10-year period.
average_annual_growth_rate = np.mean(annual_growth_rate)
#Display the results.
print("Annual growth rates of each year (%):", annual_growth_rate)
print("Year with highest growth:", ywhg)
print(f"Average annual growth rate: {average_annual_growth_rate:.2f}%")

Annual growth rates of each year (%): [400.         -40.         -16.66666667 -10.         -28.88888889
 -65.625       36.36363636  26.66666667 252.63157895]
Year with highest growth: 1
Average annual growth rate: 61.61%


***

##### Q7:  Traffic Data Analysis:
Given a 2D NumPy array where each row represents the number of vehicles passing through a 
checkpoint during different hours of the day over a week. <br>
* Calculate the total traffic for each day.
* Find the busiest hour of the week, i.e., the hour with the maximum number of vehicles 
passing through.

In [118]:
#Creating 2D array representing traffic data[rows: days, columns: vehicles per hour]
traffic_data_analysis = np.array([[120, 150, 200, 300, 250, 150, 100],[130, 160, 220, 280, 260, 170, 120],[140, 170, 240, 290, 270, 180, 130],[150, 180, 260, 310, 280, 190, 140],[160, 190, 280, 320, 290, 200, 150],[170, 200, 300, 330, 300, 210, 160],[180, 210, 320, 340, 310, 220, 170]])
#Calculating total traffic of each day.
total_traffic_data_analysis = np.sum(traffic_data_analysis,axis=1)
#For finding the busiest hour of the week
busy_hour_index = np.argmax(traffic_data_analysis)
busy_hour_value = traffic_data_analysis.flatten()[busy_hour_index] #traffic_data_analysis.flatten() converts 2D array into 1D array.
# Convert the index to hour and day
busiest_hour = busy_hour_index % traffic_data_analysis.shape[1]  # Hour of the day (0 to 6)
busiest_day = busy_hour_index // traffic_data_analysis.shape[1]  # Day of the week (0 to 6)
#Printing results.
print("Total traffic for each day:", total_traffic_data_analysis)
print("Busiest hour of the week: Day", busiest_day + 1, "Hour", busiest_hour +1)
print("Number of vehicles at the busiest hour:", busy_hour_value)

Total traffic for each day: [1270 1340 1420 1510 1590 1670 1750]
Busiest hour of the week: Day 7 Hour 4
Number of vehicles at the busiest hour: 340


***

##### Q8:  Product Inventory Management:
You have a NumPy array representing the stock levels of different products in a warehouse.<br>
* Identify the products with stock levels below a given threshold (e.g., 50 units).
* Increase the stock levels of these products to the required threshold (e.g., 100 units).

In [119]:
#Creating an array of stock levels of different products in a ware house.
stock_levels_products_warehouse = np.array([150, 23, 39, 140, 60, 15, 90, 45,29, 58])
#Setting threshld accordingly.
threshold = 50
#Finding the indices where threshold is below 50.
stock_products_reorder = np.where(stock_levels_products_warehouse<50)[0] #np.where()[0] returns indices where condition is true.
stock_prod_below_threshold = stock_levels_products_warehouse[stock_products_reorder]
# The stock level to increase to 100.
required_threshold = 100  
#Increasing the stock levels of these products to the required threshold.
stock_levels_products_warehouse[stock_products_reorder] = required_threshold
#Printing Results.
# Display the products that need to be reordered
print("Products to reorder (indices):", stock_products_reorder)
print("Stock levels below threshold:", stock_prod_below_threshold)
print("Updated stock levels:", stock_levels_products_warehouse)

Products to reorder (indices): [1 2 5 7 8]
Stock levels below threshold: [23 39 15 45 29]
Updated stock levels: [150 100 100 140  60 100  90 100 100  58]


***

##### Q9:  Game Score Analysis:
You have a NumPy array representing the scores of different players in a game over multiple 
rounds. Each row represents a player, and each column represents their score in a specific round. <br>
* Calculate the average score for each player.
* Identify the player with the highest average score. 
* Find the round with the highest total score across all players. 

In [120]:
#Creating an array of scores of players in different rounds[row: player, col: rounds].
scores_player = np.array([[10, 15, 20],[20, 25, 30],[30, 35, 40]])
#Calculating average score of each player.
average_scores_players = np.mean(scores_player, axis=1)
#Identify the player with highest average score.
player_highest_avg_score = np.argmax(average_scores_players)+1
#Calculating total score per round.
total_score_players = np.sum(scores_player, axis=0)
#Finding highest total score.
highest_total_score = np.argmax(total_score_players) +1
#Printing results.
print("Average scores of each player:", average_scores_players)
print("Player with the highest average score:", player_highest_avg_score)
print("Round with the highest total score:", highest_total_score)

Average scores of each player: [15. 25. 35.]
Player with the highest average score: 3
Round with the highest total score: 3


***

##### Q10: Financial Portfolio Analysis:
You have a NumPy array representing the daily returns of different assets in a financial portfolio 
over a month. Each row represents an asset, and each column represents the return on a specific 
day.<br>
* Calculate the overall daily return of the portfolio (sum of returns for all assets). 
* Identify the asset with the highest volatility (standard deviation of daily returns). 
* Find the day with the highest portfolio return.

In [121]:
#Creating an array representing daily returns of different assets over a month.
daily_returns = np.random.normal(0.001, 0.02, size=(30, 3))
#Calculating the overall daily return of the portfolio (sum of returns for all assets).
overall_daily_return = daily_returns.sum(axis=1) 
#Calculating standard deviation for each asset.
volatility = daily_returns.std(axis=0)
#Identify the asset with the highest volatility.
highest_volatility_asset_index = np.argmax(volatility) + 1 
#Find the day with the highest portfolio return
highest_return_day_index = np.argmax(overall_daily_return) 
# Printing results.
print("Generated daily returns:\n", daily_returns)
print("Overall daily return of the portfolio: \n", overall_daily_return)
print("Asset with the highest volatility is Asset:", highest_volatility_asset_index)
print("Day: ", highest_return_day_index + 1, "with highest portfolio return of" ,overall_daily_return[highest_return_day_index]) 

Generated daily returns:
 [[-0.01381548 -0.02482883 -0.01392038]
 [-0.03724284  0.01604936 -0.04432382]
 [-0.02161788  0.02813767  0.02552224]
 [ 0.00856892  0.01522472  0.04065915]
 [ 0.01454394 -0.01858335  0.00669507]
 [-0.01294517 -0.00921262 -0.00712203]
 [ 0.01828311 -0.01718459 -0.01532669]
 [ 0.01469879  0.00752153 -0.00293228]
 [-0.03130464 -0.02194263 -0.02191335]
 [-0.03456345  0.00220689 -0.01331667]
 [ 0.01657004 -0.00315009  0.02334081]
 [-0.02094679 -0.02225408 -0.01858802]
 [-0.02051112  0.01268713 -0.05894608]
 [-0.01382523 -0.00102915  0.01665431]
 [-0.0229303   0.00369062  0.0038786 ]
 [-0.00197284  0.00245474 -0.00822798]
 [ 0.0017909   0.03085315  0.02245779]
 [-0.00317858 -0.01759421  0.0102531 ]
 [ 0.00326498  0.01017095  0.00842585]
 [-0.01518061 -0.00330594 -0.00278667]
 [-0.01714007 -0.00066499  0.00989935]
 [-0.02871601 -0.01332617  0.0189529 ]
 [-0.01066721 -0.02106444 -0.00466804]
 [ 0.03787657  0.01913797  0.04460307]
 [ 0.00756576  0.02382507  0.00611649]

***

##### Q11: Healthcare Data Analysis:
You are provided with a NumPy array where each element represents the number of patients 
treated in a hospital for a specific day of the year. <br>
* Compute the total number of patients treated for the entire year. 
* Calculate the average number of patients treated per day.
* Identify the day with the highest number of patients treated and its corresponding count.
* Determine the number of days where the number of treated patients exceeded the average 
daily count. 
* Find the percentage of days where the hospital treated fewer than 50 patients.

In [122]:
#Creating a array where each element represents the number of patients treated per day of the year.
patients_treated = np.random.randint(0, 100, size=365) 
#Calculating the total number of patients treated for the entire year.
total_patients = np.sum(patients_treated)
#Calculating the average number of patients treated per day.
average_patients_per_day = np.mean(patients_treated)
#Identifying the day with the highest number of patients treated and its corresponding count.
highest_patients_index = np.argmax(patients_treated)
highest_patients_count = patients_treated[highest_patients_index]
#Determining the number of days where the number of treated patients exceeded the average daily count.
days_above_average = np.sum(patients_treated > average_patients_per_day)
#Finding the percentage of days where the hospital treated fewer than 50 patients.
days_fewer_than_50 = np.sum(patients_treated < 50)
percentage_fewer_than_50 = (days_fewer_than_50 / len(patients_treated)) * 100
#Printing results.
print("Total number of patients treated in the year:", total_patients)
print("Average number of patients treated per day:", average_patients_per_day)
print("Day with the highest number of patients treated:", highest_patients_index + 1, "with count", highest_patients_count)  
print("Number of days with treated patients exceeding the average:", days_above_average)
print("Percentage of days with fewer than 50 patients treated:", percentage_fewer_than_50)

Total number of patients treated in the year: 18327
Average number of patients treated per day: 50.21095890410959
Day with the highest number of patients treated: 41 with count 99
Number of days with treated patients exceeding the average: 183
Percentage of days with fewer than 50 patients treated: 48.21917808219178


***