# **Atif Jamil**

**Email:** [aatifkh8n@gmail.com](mailto:aatifkh8n@gmail.com)

**GitHub:** [aatifkh8n](https://github.com/aatifkh8n) |
**Kaggle:** [aatifkh8n](https://kaggle.com/aatifkh8n) |
**LinkedIn:** [Atif Jamil](https://linkedin.com/in/atif--jamil)

### **Purpose:** NumPy Scenario Assignment

In [1]:
# importing the numpy library
import numpy as np

In [80]:
# Defining a global constant for week day name to number mapping
WEEK_DAY_NAME_TO_NUMBER = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6
}

# Defining a global constant for week day number to name mapping
WEEK_DAY_NUMBER_TO_NAME = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

### Q1: Sales Data Analysis: You have a NumPy array representing the daily sales of a product over a month. Each element in the array represents the sales for a particular day. Compute the total sales, average sales, and the day with the highest sales.

In [3]:
daily_sales = np.random.randint(500, 5000, 30)

daily_sales

array([4519,  654, 2893, 1811, 4975, 3590, 4175, 4217, 3103, 4934, 1778,
        761, 3073, 3249, 3940, 4314, 2938, 4541, 4392, 4950, 4780, 3471,
       2051,  859,  650, 2387,  739, 4890, 1168, 1097], dtype=int32)

In [5]:
# Sales at day 10
print("Sales at day 10:", daily_sales[9])

Sales at day 10: 4934


In [6]:
print("Total Sales:", np.sum(daily_sales))
print("Average Sale:", np.average(daily_sales))
print("Highest Sale:", np.max(daily_sales))
print("Highest Sale Day:", np.where(daily_sales == np.max(daily_sales))[0][0] + 1)

Total Sales: 90899
Average Sale: 3029.9666666666667
Highest Sale: 4975
Highest Sale Day: 5


### Q2: Weather Data Processing: Given a 2D NumPy array where each row represents daily temperature readings for a week (7 days), find the average temperature for each day across all weeks.

In [18]:
month_temperatures_weekwise = np.array([
    [34.53, 16.22, 33.65,  8.41 , 19.83, 28.22, 25.98],
    [45.95, 22.88, 30.78, 27.85, 21.09, 22.76, 12.83],
    [11.78, 30.88, 32.37,  4.80, 40.13, 46.26, 23.10],
    [37.06, 34.34, 16.90, 17.37, 32.55, 50.01, 46.93]
])

month_temperatures_weekwise

array([[34.53, 16.22, 33.65,  8.41, 19.83, 28.22, 25.98],
       [45.95, 22.88, 30.78, 27.85, 21.09, 22.76, 12.83],
       [11.78, 30.88, 32.37,  4.8 , 40.13, 46.26, 23.1 ],
       [37.06, 34.34, 16.9 , 17.37, 32.55, 50.01, 46.93]])

In [82]:
# axis=0 is for column and axis=1 is for row
daywise_average = np.mean(month_temperatures_weekwise, axis=0)

for i in range(daywise_average.size):
    print(WEEK_DAY_NUMBER_TO_NAME[i], "Average:", daywise_average[i])

Monday Average: 32.33
Tuesday Average: 26.08
Wednesday Average: 28.425000000000004
Thursday Average: 14.607500000000002
Friday Average: 28.400000000000002
Saturday Average: 36.8125
Sunday Average: 27.21


### Q3: Financial Analysis: You have a NumPy array representing the daily closing prices of a stock for a month. Calculate the monthly return, which is the percentage change from the first to the last day of the month.

In [25]:
stock_closing_arr = np.array([1661, 1502, 2753, 2046, 2424, 2941, 2849, 2386, 1172, 1039, 1886, 1122, 1382, 2756, 2268, 1453, 2510, 1887, 1300, 1975, 2770, 2789, 1419, 1972, 2380, 1526, 2151, 1360, 1817, 2990])

stock_closing_arr

array([1661, 1502, 2753, 2046, 2424, 2941, 2849, 2386, 1172, 1039, 1886,
       1122, 1382, 2756, 2268, 1453, 2510, 1887, 1300, 1975, 2770, 2789,
       1419, 1972, 2380, 1526, 2151, 1360, 1817, 2990])

In [30]:
first_day_price = stock_closing_arr[0]
last_day_price = stock_closing_arr[-1]

closing_price_percentage = (last_day_price - first_day_price) / first_day_price * 100

print("First day price:", first_day_price)
print("Last day price:", last_day_price)
print("Closing price percentage:", closing_price_percentage)

First day price: 1661
Last day price: 2990
Closing price percentage: 80.01204093919326


### Q4: Student Grades Analysis: You have a 2D NumPy array where each row represents a student and each column represents their grades in different subjects. Calculate the average grade for each student and the overall class average for each subject.

In [35]:
students_grades = np.array([
    [77, 48, 74, 59],
    [62, 46, 73, 49],
    [53, 83, 64, 89],
    [38, 53, 46, 78],
    [72, 54, 33, 71]
])

students_grades

array([[77, 48, 74, 59],
       [62, 46, 73, 49],
       [53, 83, 64, 89],
       [38, 53, 46, 78],
       [72, 54, 33, 71]])

In [37]:
# Average of all students
student_avg_grades = np.mean(students_grades, axis=1)

print("Average of grades of all students:", student_avg_grades)

Average of grades of all students: [64.5  57.5  72.25 53.75 57.5 ]


In [38]:
# Overall class average per subject
avg_grades_per_subject = np.mean(students_grades, axis=0)

print("Average grades of all subjects:", avg_grades_per_subject)

Average grades of all subjects: [60.4 56.8 58.  69.2]


### Q5: Image Processing: You have a grayscale image represented as a 2D NumPy array of pixel intensities. Normalize the pixel values to a range of 0 to 1.

In [40]:
# 8x8 grayscale image
image = np.random.randint(0, 255, (8, 8))

image

array([[241, 201,  24,   6,  81, 190, 150, 189],
       [218, 149, 119, 250,  56, 192, 125, 115],
       [208,  18,   3, 191, 201,  61, 209, 226],
       [  3, 210,   0,  95, 248, 173, 163, 120],
       [223,   1,  77, 193, 239,  41, 186, 167],
       [ 64, 157, 245, 247,  84, 202,  90,  93],
       [220,  93,  87, 205,  54,  52, 244, 207],
       [217,  82, 224, 110, 107, 247, 208, 194]], dtype=int32)

In [41]:
image[image < 127] = 0
image[image >= 127] = 1

image

array([[1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 0],
       [1, 0, 0, 1, 1, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 1],
       [0, 1, 1, 1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 1, 1, 1]], dtype=int32)

### Q6: Population Growth Analysis: You have a NumPy array representing the population of a city over 10 years. Calculate the annual growth rate and identify the year with the highest growth.

In [43]:
city_10_years_population = np.array([90_703, 141_118, 203_737, 352_764, 428_163, 494_867, 584_870, 614_585, 625_397, 752_756])

city_10_years_population

array([ 90703, 141118, 203737, 352764, 428163, 494867, 584870, 614585,
       625397, 752756])

In [45]:
growth_rate_per_year = np.zeros(city_10_years_population.size)

growth_rate_per_year

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
for i in range(1, city_10_years_population.size):
    curr_population = city_10_years_population[i]
    prev_populaiton = city_10_years_population[i - 1]
    
    growth_rate = (curr_population - prev_populaiton) / prev_populaiton * 100
    growth_rate_per_year[i] = growth_rate

growth_rate_per_year

array([ 0.        , 55.58250554, 44.37350303, 73.14675292, 21.37377964,
       15.57911356, 18.18731093,  5.08061621,  1.75923591, 20.36450447])

In [47]:
highest_growth_rate = np.max(growth_rate_per_year)
highest_growth_rate_index = np.where(growth_rate_per_year == highest_growth_rate)[0][0]

print("Highest growth rate:", highest_growth_rate)
print("Highest growth rate year:", highest_growth_rate_index+1)

Highest growth rate: 73.1467529216588
Highest growth rate year: 4


### Q7: Traffic Data Analysis: Given a 2D NumPy array where each row represents the number of vehicles passing through a checkpoint in different hours of the day over a week, calculate the total traffic for each day and the busiest hour of the week.

In [50]:
# Week data about the number of vehicles passing through the checkpoint 24/7
# Order of data: 7x24 (7 days, 24 hours)
traffic_checkpoint_week_data = np.array([
    [50, 88, 63, 67, 55, 30, 36, 84,  2, 19, 74, 49, 27, 21, 75,  7, 72, 92, 86, 98, 24, 53, 36, 11],
    [89, 25,  4, 86, 32, 73, 39, 60, 84, 81, 81, 40, 98,  1, 64, 89, 52, 45, 51, 46, 71, 69, 54, 12],
    [59, 83, 61, 10, 47,  1, 52, 80, 34, 29, 34, 21, 26, 46, 72, 59, 34, 24, 95, 91, 47, 82, 75, 39],
    [94, 28, 93, 76, 91, 86, 68, 45,  4, 63, 96, 85,  4, 20, 23, 29, 47, 77, 13, 48, 15, 94, 77, 50],
    [82,  1, 34, 70,  2, 80, 25, 66, 47, 69, 79, 36, 26, 70, 92, 37, 24,  6, 14, 97, 17, 73,  7, 73],
    [60, 27, 10, 65, 44, 26, 82, 96, 18, 74, 69, 48, 92,  0,  4, 94, 97,  2, 80, 70, 99, 63, 88, 57],
    [38, 70, 19, 53,  6, 80, 13, 94, 80, 12, 87, 88, 56, 98, 25, 30, 61, 22, 51, 37, 25, 49, 44, 67]
])

traffic_checkpoint_week_data

array([[50, 88, 63, 67, 55, 30, 36, 84,  2, 19, 74, 49, 27, 21, 75,  7,
        72, 92, 86, 98, 24, 53, 36, 11],
       [89, 25,  4, 86, 32, 73, 39, 60, 84, 81, 81, 40, 98,  1, 64, 89,
        52, 45, 51, 46, 71, 69, 54, 12],
       [59, 83, 61, 10, 47,  1, 52, 80, 34, 29, 34, 21, 26, 46, 72, 59,
        34, 24, 95, 91, 47, 82, 75, 39],
       [94, 28, 93, 76, 91, 86, 68, 45,  4, 63, 96, 85,  4, 20, 23, 29,
        47, 77, 13, 48, 15, 94, 77, 50],
       [82,  1, 34, 70,  2, 80, 25, 66, 47, 69, 79, 36, 26, 70, 92, 37,
        24,  6, 14, 97, 17, 73,  7, 73],
       [60, 27, 10, 65, 44, 26, 82, 96, 18, 74, 69, 48, 92,  0,  4, 94,
        97,  2, 80, 70, 99, 63, 88, 57],
       [38, 70, 19, 53,  6, 80, 13, 94, 80, 12, 87, 88, 56, 98, 25, 30,
        61, 22, 51, 37, 25, 49, 44, 67]])

In [83]:
total_traffic_per_day = np.sum(traffic_checkpoint_week_data, axis=1)

for i in range(traffic_checkpoint_week_data.shape[0]):
    print("Total traffic on day", WEEK_DAY_NUMBER_TO_NAME[i], ":", total_traffic_per_day[i])

Total traffic on day Monday : 1219
Total traffic on day Tuesday : 1346
Total traffic on day Wednesday : 1201
Total traffic on day Thursday : 1326
Total traffic on day Friday : 1127
Total traffic on day Saturday : 1365
Total traffic on day Sunday : 1205


In [69]:
highest_traffic = np.max(traffic_checkpoint_week_data)

print("Highest traffic hour in the week:", highest_traffic)

Highest traffic hour in the week: 99


In [84]:
busiest_hour = np.where(traffic_checkpoint_week_data == highest_traffic)

print("Day:", WEEK_DAY_NUMBER_TO_NAME[busiest_hour[0][0]])
print("Hour:", busiest_hour[1][0]+1)

Day: Saturday
Hour: 21


### Q8: Product Inventory Management: You have a NumPy array representing the stock levels of different products in a warehouse. Reorder the products with stock levels below a threshold (e.g., 50 units).

In [86]:
stock_levels_arr = np.random.randint(1, 100, size=10)

stock_levels_arr

array([46, 20, 31, 74, 29, 53,  6, 46, 34, 52], dtype=int32)

In [93]:
THRESHOLD = 50

products_stock_below_threshold = stock_levels_arr[stock_levels_arr < THRESHOLD]
products_to_reorder = np.where(stock_levels_arr < THRESHOLD)[0]

print("Stock below threshold:", products_stock_below_threshold)
print("Products that need to be reordered (stock levels below the threshold):", products_to_reorder)

Stock below threshold: [46 20 31 29  6 46 34]
Products that need to be reordered (stock levels below the threshold): [0 1 2 4 6 7 8]


### Q9: Game Score Analysis: You have a NumPy array representing the scores of different players in a game over multiple rounds. Identify the player with the highest average score and the round with the highest total score.

In [103]:
# axis=0, column is player
# axis=1, row is round
game_scores_in_rounds_per_player = np.array([
    [ 13, 98,  11,  34,  73],
    [105,  73,  72,  53,  70],
    [ 10,  16,  20, 109,  64],
    [ 26, 113,  34, 103,  0],
    [ 14,  58, 0,  72,  0]
])

game_scores_in_rounds_per_player

array([[ 13,  98,  11,  34,  73],
       [105,  73,  72,  53,  70],
       [ 10,  16,  20, 109,  64],
       [ 26, 113,  34, 103,   0],
       [ 14,  58,   0,  72,   0]])

In [99]:
highest_scores = np.max(game_scores_in_rounds_per_player)

print("Highest score:", highest_scores)

Highest score: 113


In [102]:
highest_scores_index = np.where(game_scores_in_rounds_per_player == highest_scores)

print("Player who got the highest score:", highest_scores_index[1][0])
print("Round:", highest_scores_index[0][0]+1)

Player who got the highest score: 1
Round: 4


### Q10: Financial Portfolio Analysis: You have a NumPy array representing the daily returns of different assets in a financial portfolio over a month. Calculate the portfolio's overall daily return, and identify the asset with the highest volatility.

In [112]:
# Array of order 30x5
# 30 days, 5 assets
daily_returns_arr = np.array([
    [3800, 8400, 5400, 1700, 5600],
    [4500, 2800, 2400,  800, 5500],
    [4400,  900, 1600, 1500, 4800],
    [5400, 2100, 9200, 5600, 6600],
    [6900, 3700, 1400, 9200, 6600],
    [1500, 3500, 3000, 5900, 7600],
    [4800, 5900,  700, 2800, 7400],
    [3900, 1900, 6700, 7900, 2000],
    [1900, 9700,  100, 8100, 7900],
    [7300, 8400, 9500, 8800, 1600],
    [2000, 4500, 1700, 4900, 1000],
    [9900, 5500, 7600, 6100, 6900],
    [7300, 9800, 7700, 9700, 6800],
    [2500, 4400, 3600, 6300, 1300],
    [5800, 1700, 9200, 4400, 1800],
    [7800, 5300,  700, 1300, 7100],
    [7800, 2000, 7600,  800, 3100],
    [8300, 1700, 2800, 5000,  100],
    [3800, 6000, 7200, 5200, 1300],
    [4800, 6700, 5200, 2400, 2900],
    [1000, 7900, 9200, 3800, 8600],
    [2200, 9700, 5600, 1500, 2700],
    [6900, 6700, 5400, 3800, 3500],
    [9300, 7000,  600, 3500, 6100],
    [7800, 8600, 7300, 4800, 2800],
    [1700, 9900, 9700, 8800, 9500],
    [7200,  800, 1900, 7000, 7200],
    [6400, 9500, 5200, 7800, 1700],
    [6500, 7400, 3100, 8200, 7900],
    [6100, 9800, 5100, 9500, 7300]
])

daily_returns_arr

array([[3800, 8400, 5400, 1700, 5600],
       [4500, 2800, 2400,  800, 5500],
       [4400,  900, 1600, 1500, 4800],
       [5400, 2100, 9200, 5600, 6600],
       [6900, 3700, 1400, 9200, 6600],
       [1500, 3500, 3000, 5900, 7600],
       [4800, 5900,  700, 2800, 7400],
       [3900, 1900, 6700, 7900, 2000],
       [1900, 9700,  100, 8100, 7900],
       [7300, 8400, 9500, 8800, 1600],
       [2000, 4500, 1700, 4900, 1000],
       [9900, 5500, 7600, 6100, 6900],
       [7300, 9800, 7700, 9700, 6800],
       [2500, 4400, 3600, 6300, 1300],
       [5800, 1700, 9200, 4400, 1800],
       [7800, 5300,  700, 1300, 7100],
       [7800, 2000, 7600,  800, 3100],
       [8300, 1700, 2800, 5000,  100],
       [3800, 6000, 7200, 5200, 1300],
       [4800, 6700, 5200, 2400, 2900],
       [1000, 7900, 9200, 3800, 8600],
       [2200, 9700, 5600, 1500, 2700],
       [6900, 6700, 5400, 3800, 3500],
       [9300, 7000,  600, 3500, 6100],
       [7800, 8600, 7300, 4800, 2800],
       [1700, 9900, 9700,

In [117]:
# 1. Calculate the overall daily return for the portfolio
overall_daily_return = np.mean(daily_returns_arr, axis=1)

# 2. Calculate the volatility (standard deviation) for each asset's returns
volatility = np.std(daily_returns_arr, axis=0)

# 3. Identify the asset with the highest volatility
highest_volatility_index = np.argmax(volatility)
highest_volatility_value = volatility[highest_volatility_index]

# Print results
print("Overall Daily Return for the Portfolio:")
print(overall_daily_return)

print("\nVolatility of each asset:")
print(volatility)

print(f"\nAsset with the highest volatility is Asset {highest_volatility_index + 1} with a volatility of {highest_volatility_value:.2f}")

Overall Daily Return for the Portfolio:
[4980. 3200. 2640. 5780. 5560. 4300. 4320. 4480. 5540. 7120. 2820. 7200.
 8260. 3620. 4580. 4440. 4260. 3580. 4700. 4400. 6100. 4340. 5260. 5300.
 6260. 7920. 4820. 6120. 6620. 7560.]

Volatility of each asset:
[2445.27889798 3016.13439135 3032.97433773 2786.21407808 2705.74697019]

Asset with the highest volatility is Asset 3 with a volatility of 3032.97


---

<h2 style="text-align: center;">Status: <span style="color: green;">Task Completed</span></h2>