In [1]:
import numpy as np

In [3]:
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
ones = np.ones((4, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
zeros_dot_ones = np.dot(zeros, ones)
zeros_dot_ones

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
marks = np.array([60, 53, 71, 62, 83, 57])

marks

array([60, 53, 71, 62, 83, 57])

In [10]:
marks = marks.reshape(2, 3)

marks

array([[60, 53, 71],
       [62, 83, 57]])

In [11]:
marks.shape

(2, 3)

In [12]:
marks.ndim

2

In [13]:
marks.size

6

In [14]:
np.mean(marks)

np.float64(64.33333333333333)

In [15]:
np.median(marks)

np.float64(61.0)

In [20]:
# mode function doesn't exist in the numpy
# np.mode(marks)

In [21]:
np.min(marks)

np.int64(53)

In [22]:
np.max(marks)

np.int64(83)

In [23]:
np.sum(marks)

np.int64(386)

In [24]:
np.subtract(marks, 5)

array([[55, 48, 66],
       [57, 78, 52]])