### **Problem 1**

> > (A) You make a measurement of objects {1,2} against objects {3,4} and get a difference of 1 kg. Write this as a linear equation for the masses.

In [60]:
import numpy as np

# Linear equation for Part A
m1, m2, m3, m4 = 0, 0, 0, 0  # Unknown masses initialized

# Equation based on the measurement
# Here, we can just express it as a simple function
def measurement_a(m1, m2, m3, m4):
    return m1 + m2 - m3 - m4 == 1

# Display the function call result
print("Measurement A result:", measurement_a(m1, m2, m3, m4))



Measurement A result: False


> > (B) What is the minimum number of such measurements necessary to recover all five masses?

In [61]:
# Minimum number of measurements needed
N = 5  # Number of unknown masses
min_measurements = N - 1
print(f"The minimum number of measurements necessary to recover all five masses is: {min_measurements}")


The minimum number of measurements necessary to recover all five masses is: 4


 > > (C) Come up with N−1 measurements that, when combined with the answer to Part (A), would make it possible to recover the masses.

In [63]:
# Initialize unknown masses
m1, m2, m3, m4, m5 = 0, 0, 0, 0, 0  # Unknown masses initialized

# Additional measurements for Part C
# Using 'b' values as placeholders for actual measurement results
b1, b2, b3 = 0, 0, 0  # Initialize with placeholder values

# Define equations as functions
def measurement_b1(m1, m2, m3, m4):
    return m1 + m3 - m2 - m4 == b1

def measurement_b2(m1, m2, m3, m5):
    return m2 + m5 - m1 - m3 == b2

def measurement_b3(m1, m2, m4, m5):
    return m4 + m5 - m1 - m2 == b3

# Display the function call results
print("Measurement B1 result:", measurement_b1(m1, m2, m3, m4))
print("Measurement B2 result:", measurement_b2(m1, m2, m3, m5))
print("Measurement B3 result:", measurement_b3(m1, m2, m4, m5))


Measurement B1 result: True
Measurement B2 result: True
Measurement B3 result: True


> > (D) What would 𝐴 and b be in the matrix form of the linear system corresponding to the N measurements?

In [64]:
# Coefficients matrix A
A = np.array([[1, 1, -1, -1, 0],
              [1, 0, 1, -1, 0],
              [-1, 0, -1, 0, 1],
              [-1, -1, 0, 0, 1]])

# Right-hand side vector b
b = np.array([1, b1, b2, b3])  # Replace b1, b2, b3 with actual measurement values

print("Matrix A:")
print(A)
print("\nVector b:")
print(b)


Matrix A:
[[ 1  1 -1 -1  0]
 [ 1  0  1 -1  0]
 [-1  0 -1  0  1]
 [-1 -1  0  0  1]]

Vector b:
[1 0 0 0]


### **Problem 2**

> > (A) Use arange to create a variable named foo that stores an array of numbers from 0 to 29, inclusive.
 Print foo and its shape.

In [3]:

foo = np.arange(0,30)


print(foo)
print(f" Shape of foo {np.shape(foo)}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
 Shape of foo (30,)


> > (B) Use the reshape function to change foo to a validly-shaped two-dimensional matrix and store it in a new variable called bar. Print bar and its shape.

In [5]:
bar = np.reshape(foo, (6,5))

print(bar)
print(f" Shape of bar {np.shape(bar)}")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
 Shape of bar (6, 5)


> > (C) Create a third variable, baz that reshapes it into a valid three-dimensional shape. Print baz and its shape.


In [12]:
baz = np.reshape(foo, (3, 2, 5))
baz

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

> >  (D) There are several different ways to index into NumPy arrays. Use two-dimensional array indexing to set the
 first value in the second row of bar to -1. Now look at foo and baz. Did they change? Explain what’s
 going on. (Hint:does reshape return a view or a copy?)

In [13]:
#First value on row 2 is 5 so I will change it to -1

bar[1,0] = -1

print(bar)

[[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [14]:
print(foo)
print(baz)

[ 0  1  2  3  4 -1  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[[ 0  1  2  3  4]
  [-1  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


#### Explanation:

The value in the array **foo** and **baz** also changed to -1 which shows that the Numpy funtion **reshape()** doesn't create a copy of orignal array but atuallu it manipulates the same array. 

>> (E) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific
 dimensions. Figure out how the NumPy sum function works(and the axis argument inparticular) and
 do the following:
 > >1.  Sum baz over its second dimension and print the result.
 > >2.  Sum baz over its third dimension and print the result.
 > >3.  Sum baz over both its first and third dimensions and print the result.

In [15]:
sum_baz_axis_1 = np.sum(baz, axis=1)
print("Sum of baz over its second dimension (axis=1):\n", sum_baz_axis_1)

# Sum baz over its third dimension (axis=2)
sum_baz_axis_2 = np.sum(baz, axis=2)
print("Sum of baz over its third dimension (axis=2):\n", sum_baz_axis_2)

# Sum baz over both its first and third dimensions (axis=0 and axis=2)
sum_baz_axis_0_2 = np.sum(baz, axis=(0, 2))     
print("Sum of baz over its first and third dimensions (axis=0 and axis=2):\n", sum_baz_axis_0_2)

Sum of baz over its second dimension (axis=1):
 [[-1  7  9 11 13]
 [25 27 29 31 33]
 [45 47 49 51 53]]
Sum of baz over its third dimension (axis=2):
 [[ 10  29]
 [ 60  85]
 [110 135]]
Sum of baz over its first and third dimensions (axis=0 and axis=2):
 [180 249]


> > (F) Along with shaping and indexing, we also do alot of slicing which is where you index with ranges to get
 sub vectors and sometimes sub matrices. Write code to do the following:
> >1. Slice out the second row of bar and print it.
> >2. Slice out the last column of bar using the 1 notation and print it.
> >3. Slice out the top right 2×2 sub matrix of bar and print it.

In [16]:
#Slicing Second row of bar

second_row = bar[1, :]
second_row

array([-1,  6,  7,  8,  9])

In [17]:
#Slicing Last Column of bar
 
last_column = bar[:, -1]
last_column

array([ 4,  9, 14, 19, 24, 29])

In [18]:
#Slicing top right 2x2 matrix

top_right_submatrix = bar[:2, -2:]
top_right_submatrix

array([[3, 4],
       [8, 9]])

___________________________________________________________________________________________________________________________

### **Problem 3**


> > (A) The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g.,add,
 multiply,...) on an array and a scalar, the effect is to perform that operation with the scalar for every element
 of the array. To try this out, create a vector 1,2,...,10 by adding 1 to the result of the arange function.

In [23]:
vector = np.arange(10) + 1
vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

 > > (B) Now, create a 10×10 matrix A in which Aij = i + j. You’ll be able to do this using the vector you just 
 created, and adding it to a reshaped version of itself.

In [27]:
A = vector.reshape(10, 1) + vector
A

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

> > (C) A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance.
  First, create a fake “dataset” with 50 examples, each with five dimensions.
> >
> > import numpy.random as npr
> >
> > data = np.exp(npr . randn(50,5))
> >
> >You don’t worry too much about what this code is doing at this stage of the course, but for completeness: it
> >imports the NumPy random number generation library, then generates a 50×5 matrix of standard normal 
> >random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent
> >and identically-distributed vectors from a log-normal distribution.

In [41]:
import numpy.random as npr
data = np.exp(npr.randn(50, 5))


mean = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)

# Step 2: Standardize the dataset
standardized_data = (data - mean) / std_dev

print("\nStandardized dataset (zero mean, unit variance):\n", standardized_data)




Standardized dataset (zero mean, unit variance):
 [[ 1.1805275  -0.81473812 -0.79633358 -0.6302976  -0.37807505]
 [ 0.64492065 -1.22870675  1.02827321  0.91786348 -0.64599499]
 [-0.47111087 -0.18465372 -0.47051214 -0.71254228 -0.6382737 ]
 [-0.41004339  0.06994509 -0.71362773 -0.59204605  0.25229226]
 [-0.26447475 -0.43696548 -0.55520213 -0.71591168 -0.55019784]
 [-0.23688038 -0.28305223 -0.13236485 -0.61085577  0.18016349]
 [-0.43312982 -0.40776016  2.07029163  0.12941102 -0.69673635]
 [ 5.04002476 -0.21149509 -0.79433708 -0.24962397  0.11126849]
 [-0.4884855   3.0010445   0.62158658 -0.56044525 -0.27185432]
 [-0.69079384 -1.08010537  1.44557744 -0.16504971 -0.60228572]
 [-0.66160616  0.20464926  0.15803105 -0.80663206 -0.64719661]
 [-0.54662315  0.49843859  0.1670017  -0.70741735  0.12270389]
 [-0.67005412 -1.11159904 -0.14487999  0.52339931 -0.39895472]
 [-0.20740991  1.86115568 -0.74875987 -0.55244258  3.52496242]
 [-0.56046075 -0.18103347 -0.64478619 -0.66283792  3.05732143]
 [-0

> >(D) Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit about how to use the axis argument to mean and std. Store these vectors in to variables and print both of them.

In [44]:
column_means = np.mean(data, axis=0)
column_std_devs = np.std(data, axis=0)

# Print the results
print("Mean", column_means)
print()
print("Standard deviation", column_std_devs)

Mean [1.5262268  1.64269918 1.96706527 1.43477033 1.5113365 ]

Standard deviation [1.89047276 1.15647835 2.220507   1.65322961 1.85330954]


> > (E) Now standardize the data matrix by 
> > 1. subtracting the mean off of each column, and
> > 2. dividing each column by its standard deviation.
> > Do this via broadcasting, and store the result in a matrix called normalized.
> >
> > To verify that you successfully did it, compute the mean and standard deviation of the columns of normalized and print them out.

In [49]:
#Standardizing
normalized = (data - column_means) / column_std_devs

#Verification
normalized_means = np.mean(normalized, axis=0)
normalized_std_devs = np.std(normalized, axis=0)

print("Mean of each column after normalization:\n", normalized_means)
print("\nStandard deviation of each column after normalization:\n", normalized_std_devs)


Mean of each column after normalization:
 [ 2.19824159e-16  1.46549439e-16 -2.44249065e-16  2.40918396e-16
 -2.06501483e-16]

Standard deviation of each column after normalization:
 [1. 1. 1. 1. 1.]


_________________________________________________________________________________________________________________________________________________

### **Problem4**

> > (A) Use what you learned about broadcasting in the previous problem to write a function that will produce a Vandermonde matrix for a vector[1,2,...,N] T for any N. Do it without using a loop. Here’s a stub to get you started:
 def vandermonde(N):
 vec = np.arange(N)+1
 Finish me.
 Use your function for N=12, store it in variable named vander, and print the result.


In [51]:
import numpy as np

# Vandermonde matrix function
def vandermonde(N):
    vec = np.arange(N) + 1  # Create vector [1, 2, ..., N]
    vander = np.vander(vec, increasing=True)  # Generate Vandermonde matrix
    return vander

# Use N = 12
N = 12
vander = vandermonde(N)
print("Vandermonde matrix for N=12:")
print(vander)


Vandermonde matrix for N=12:
[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    3627

 > > (B) Now, let’s make a pretend linear system problem with this matrix. Create a vector of all ones, of length 12, and call it x. Perform a matrix-vector multiplication of vander with the vector you just created and store that in a new vector and call it b. Print the vector b.

In [52]:
# Create a vector of all ones, perform matrix-vector multiplication
x = np.ones(N)  # Vector of all ones
b = np.dot(vander, x)  # Matrix-vector multiplication
print("\nVector b (result of matrix-vector multiplication):")
print(b)



Vector b (result of matrix-vector multiplication):
[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


> > (C) First, solve the linear system the naïve way, pretending like you don’t know x. Import numpy.linalg, invert vander, and multiply it by b. Print out your result. What should you get for your answer? If the answer is different than what you expected, write a sentence about that difference.

In [53]:
import numpy.linalg as la

# Part (C): Naive solution using matrix inversion
vander_inv = la.inv(vander)  # Invert the Vandermonde matrix
x_naive = np.dot(vander_inv, b)  # Multiply inverse by b
print("\nNaive solution using matrix inversion:")
print(x_naive)



Naive solution using matrix inversion:
[-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


> > (D) Now, solve the same linear system using the solve function from the numpy.linalg library (i.e., solve 𝐴𝑥=𝑏 Ax=b directly without inverting the matrix). Print out the result. Compare it to the result in Part (C) and write a sentence about any differences.

In [54]:
# Part (D): Solving the system using numpy.linalg.solve
x_solve = la.solve(vander, b)  # Solve Ax = b without inverting
print("\nSolution using numpy.linalg.solve:")
print(x_solve)



Solution using numpy.linalg.solve:
[0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816
 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]


_________________________________________________________________________________________________________________________________________________
END