# **Atif Jamil**

**Email:** [aatifkh8n@gmail.com](mailto:aatifkh8n@gmail.com)

**GitHub:** [aatifkh8n](https://github.com/aatifkh8n) |
**Kaggle:** [aatifkh8n](https://kaggle.com/aatifkh8n) |
**LinkedIn:** [Atif Jamil](https://linkedin.com/in/atif--jamil)

### **Purpose:** NumPy Class Assignment

---

# Assignment Questions

## Basic Array Operations

Create a 1D array, a 2D array, and a 3D array.

Perform slicing operations on arrays.

Perform basic arithmetic operations on arrays (addition, subtraction, multiplication, division).

Array Creation and Manipulation

Create arrays using different functions: arange, linspace, zeros, ones, eye, random.

Reshape an array.

Concatenate and split arrays.

## Statistical Operations

Compute mean, median, variance, and standard deviation of an array.

Find the minimum and maximum values in an array along with their indices.

Compute the sum and product of array elements.

## Broadcasting

Demonstrate broadcasting with examples of different shapes of arrays.

Explain the concept of broadcasting and how it works in NumPy.

## Linear Algebra

Perform matrix multiplication.

Compute the determinant, inverse, and eigenvalues of a matrix.

Solve a system of linear equations.

## Advanced Indexing and Slicing

Use Boolean indexing to filter an array.

Use fancy indexing to select specific elements from an array.

Perform advanced slicing operations.

## Random Sampling

Generate random numbers from different distributions.

Create random samples from a dataset.

Perform random shuffling of an array.

In [130]:
import numpy as np

## Basic Array Operations

#### Q1: Create a 1D array, a 2D array, and a 3D array.

In [131]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [132]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Q2: Perform slicing operations on arrays.

In [135]:
# accessing 1d array elements from index 3 to 8 excluded
arr_1d[3:8]

array([4, 5, 6, 7, 8])

In [136]:
# accessing 2d array elements from row 1 to end and column and row 2 to 4 excluded
arr_2d[1:, 2:4]

array([[ 7,  8],
       [11, 12]])

In [137]:
# accessing 3d array elements from all 2d arrays, 1st row and column 0 to 2 excluded
arr_3d[:, 0, 0:2]

array([[1, 2],
       [7, 8]])

#### Q3: Perform basic arithmetic operations on arrays (addition, subtraction, multiplication, division).

In [138]:
# Addition of arr_1d array with itself
arr_1d + arr_1d

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [139]:
# Multiplication of arr_2d array with temp_2d array
temp_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

arr_2d * temp_2d

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [140]:
# Multiplication of arr_3d array with temp_3d array
temp_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

arr_3d * temp_3d

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[ 49,  64,  81],
        [100, 121, 144]]])

## Array Creation and Manipulation

#### Q1: Create arrays using different functions: arange, linspace, zeros, ones, eye, random.

In [141]:
arr_1_to_10 = np.arange(1, 11)

arr_1_to_10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
arr_10_elements = np.linspace(10, 100, 10)

arr_10_elements

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [143]:
zeros_2d = np.zeros((3, 3))

zeros_2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [144]:
ones_3d = np.ones((2, 2, 2))

ones_3d

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [145]:
identity_3x3 = np.eye(3)

identity_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [146]:
arr_rand_3x3 = np.random.randint(10, 20, (3, 3))

arr_rand_3x3

array([[16, 19, 12],
       [17, 10, 18],
       [15, 17, 14]], dtype=int32)

#### Q2: Reshape an array.

In [147]:
arr_1d_reshaped = arr_rand_3x3.reshape(9)

arr_1d_reshaped

array([16, 19, 12, 17, 10, 18, 15, 17, 14], dtype=int32)

#### Q3: Concatenate and split arrays.

In [148]:
# Concatenation of arr_1d, arr_1_to_10, arr_1d_reshaped and [55]
concat_arr_1d = np.concat((arr_1d, arr_1_to_10, arr_1d_reshaped, [55]))

concat_arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 16, 19, 12, 17, 10, 18, 15, 17, 14, 55])

In [149]:
# Splitting concat_arr_1d in 3 equal subarrays
np.split(concat_arr_1d, 3)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([16, 19, 12, 17, 10, 18, 15, 17, 14, 55])]

## Statistical Operations

Q1: Compute mean, median, variance, and standard deviation of an array.

In [150]:
print("Mean of 1d Array:", arr_1d.mean())
print("Median of 1d Array:", np.median(arr_1d))
print("Variance of 1d Array:", arr_1d.var())
print("Standard Deviation of 1d Array:", arr_1d.std())

Mean of 1d Array: 5.5
Median of 1d Array: 5.5
Variance of 1d Array: 8.25
Standard Deviation of 1d Array: 2.8722813232690143


#### Q2: Find the minimum and maximum values in an array along with their indices.

In [151]:
# Minimum value and its index
min = arr_1d.min()
min_index = np.where(arr_1d == min)[0][0]

print("Minimum value in 1d Array:", min)
print("Index of minimum value in 1d Array:", min_index)

Minimum value in 1d Array: 1
Index of minimum value in 1d Array: 0


In [152]:
# Maximum value and its index
max = arr_1d.max()
max_index = np.where(arr_1d == max)[0][0]

print("Maximum value in 1d Array:", max)
print("Index of maximum value in 1d Array:", max_index)

Maximum value in 1d Array: 10
Index of maximum value in 1d Array: 9


#### Q3: Compute the sum and product of array elements.

In [153]:
sum = arr_10_elements.sum()
product = arr_10_elements.prod()

print("Sum of 10 elements:", sum)
print("Product of 10 elements:", product)

Sum of 10 elements: 550.0
Product of 10 elements: 3.6288e+16


## Broadcasting

#### Q1: Demonstrate broadcasting with examples of different shapes of arrays.

In [154]:
# 2d Array with order 2x3
arr_1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 2d Array with order 3x3
arr_2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

np.dot(arr_1, arr_2)

array([[30, 36, 42],
       [66, 81, 96]])

#### Q2: Explain the concept of broadcasting and how it works in NumPy.

Actually, broadcasting is the feature of NumPy that can do the arthimetic operations on two matrics even if their order is not same.

Like, if we have a = [1] and b = [1, 2]. For a + b, it will make a = [1, 1] and then it will add element-wise:

```py
a + b = [1+1, 1+2]
a + b = [2, 3]
```

## Linear Algebra

#### Q1: Perform matrix multiplication.

In [155]:
mat_2x3 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

mat_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Matrix multiplication using numpy.matmul()
np.matmul(mat_2x3, mat_3x3)

array([[30, 36, 42],
       [66, 81, 96]])

In [156]:
# Matrix multiplication using numpy.dot()
np.dot(mat_2x3, mat_3x3)

array([[30, 36, 42],
       [66, 81, 96]])

In [157]:
# Matrix multiplication using @ operator
mat_2x3 @ mat_3x3

array([[30, 36, 42],
       [66, 81, 96]])

#### Q2: Compute the determinant, inverse, and eigenvalues of a matrix.

In [158]:
np.linalg.det(arr_rand_3x3)

np.float64(-379.9999999999997)

In [159]:
np.linalg.inv(arr_rand_3x3)

array([[ 0.43684211,  0.16315789, -0.58421053],
       [-0.08421053, -0.11578947,  0.22105263],
       [-0.36578947, -0.03421053,  0.42894737]])

In [160]:
eigenvalues, eigenvectors = np.linalg.eig(arr_rand_3x3)

print("Eigen Values:", eigenvalues)
print()
print("Eigen Vectors:", eigenvectors)

Eigen Values: [46.01425937  1.15233405 -7.16659342]

Eigen Vectors: [[-0.58897726 -0.7597891   0.51609057]
 [-0.56621882  0.20380416 -0.80827869]
 [-0.57662989  0.61740131  0.28343621]]


#### Q3: Solve a system of linear equations.

In [161]:
# Coefficient matrix A and constant vector b
A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

# Solve the system
x = np.linalg.solve(A, b)
print("Solution:", x)

Solution: [1. 2.]


## Advanced Indexing and Slicing

#### Q1: Use Boolean indexing to filter an array.

In [162]:
# Select elements greater than 30
filtered = arr_10_elements[arr_10_elements > 30]
print("Filtered Array:", filtered)

Filtered Array: [ 40.  50.  60.  70.  80.  90. 100.]


#### Q2: Use fancy indexing to select specific elements from an array.

In [163]:
# Accessing the value at index 3 and at index 5
arr_1d_reshaped[[3, 5]]

array([17, 18], dtype=int32)

#### Q3: Perform advanced slicing operations.

In [164]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Select the first two rows and last two columns
subarray = arr[:2, -2:]
subarray

array([[2, 3],
       [5, 6]])

## Random Sampling

#### Q1: Generate random numbers from different distributions.

In [165]:
# Uniform distribution between 0 and 1
uniform_random = np.random.rand(5)

uniform_random

array([0.81007283, 0.56838538, 0.25696178, 0.88460061, 0.29885508])

In [166]:
# Normal distribution with mean 0 and standard deviation 1
normal_random = np.random.randn(5)

normal_random

array([ 1.07150615, -1.93403333,  0.5752198 , -0.58065837, -1.24960516])

#### Q2: Create random samples from a dataset.

In [167]:
sample = np.random.choice(arr_1d_reshaped, 4, replace=False)

sample

array([19, 15, 16, 18], dtype=int32)

#### Q3: Perform random shuffling of an array.

In [168]:
print("Before shuffling, arr_10_elements:", arr_10_elements)

np.random.shuffle(arr_10_elements)

print("After shuffling, arr_10_elements:", arr_10_elements)

Before shuffling, arr_10_elements: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
After shuffling, arr_10_elements: [ 10.  30.  90.  80.  20.  70.  50. 100.  60.  40.]


---

<h2 style="text-align: center;">Status: <span style="color: green;">Task Completed</span></h2>